/**
 * early-career-developer: summaries, job descriptions, contacts, resumes and notes.
 */

import type { ContactSpec, JdSpec, NoteSpec, ResumeSpec, SummarySpec } from '../../corpus/types'

export const summaries: SummarySpec[] = [
  {
    key: 's-platform',
    title: 'Platform-focused early-career engineer',
    role: 'Associate Platform Engineer',
    description:
      'Early-career engineer who builds the internal services, pipelines and dashboards that keep teams moving. Python, PostgreSQL, Docker and Linux; studying distributed systems part-time.',
    industryKey: 'data-analytics',
    roleTypeKey: 'platform-engineer',
    skills: ['python', 'docker', 'linux', 'postgresql', 'grafana'],
    daysAgo: 90,
  },
  {
    key: 's-solutions',
    title: 'Customer-minded developer',
    role: 'Associate Solutions Engineer',
    description:
      'Developer who enjoys translating what users need into working software, with experience supporting staff, students and the public.',
    industryKey: 'healthcare',
    roleTypeKey: 'solutions-engineer',
    skills: ['javascript', 'react', 'rest-apis', 'customer-support', 'technical-writing'],
    daysAgo: 75,
  },
  {
    key: 's-support-template',
    title: 'Support-to-software template',
    role: 'Software Engineer',
    description: 'Lead with hands-on support experience, then the automation and software built to reduce it.',
    is_template: true,
    roleTypeKey: 'it-support',
    notes: 'Use for roles that value operations experience.',
    skills: ['customer-support', 'bash', 'linux'],
    daysAgo: 150,
  },
]

export const jds: JdSpec[] = [
  {
    key: 'jd-kestrel-platform',
    title: 'Associate Platform Engineer',
    orgKey: 'kestrel',
    url: 'https://jobs.example.com/kestrel-analytics/associate-platform-engineer',
    file: 'kestrel-associate-platform-engineer.md',
    status: 'interviewing',
    salary_min: 72000,
    salary_max: 86000,
    salary_range: '$72,000 - $86,000',
    location: 'Cincinnati, OH (hybrid)',
    skills: ['python', 'docker', 'kubernetes', 'terraform', 'linux', 'grafana'],
    daysAgo: 62,
    updatedDaysAgo: 12,
  },
  {
    key: 'jd-harborview-solutions',
    title: 'Associate Solutions Engineer',
    orgKey: 'harborview',
    url: 'https://jobs.example.com/harborview-health/associate-solutions-engineer',
    file: 'harborview-associate-solutions-engineer.md',
    status: 'applied',
    salary_min: 70000,
    salary_max: 82000,
    salary_range: '$70,000 - $82,000',
    location: 'Cleveland, OH (hybrid)',
    skills: ['rest-apis', 'sql', 'customer-support', 'technical-writing', 'javascript'],
    daysAgo: 48,
    updatedDaysAgo: 28,
  },
  {
    key: 'jd-blueheron-ml',
    title: 'Junior Machine Learning Engineer',
    orgKey: 'blue-heron',
    url: 'https://jobs.example.com/blue-heron-robotics/junior-ml-engineer',
    file: 'blueheron-junior-ml-engineer.md',
    status: 'analyzing',
    salary_min: 78000,
    salary_max: 92000,
    salary_range: '$78,000 - $92,000',
    location: 'Pittsburgh, PA',
    skills: ['python', 'pandas', 'scikit-learn', 'llm-apis'],
    daysAgo: 16,
    updatedDaysAgo: 14,
  },
  {
    key: 'jd-ironleaf-security',
    title: 'Junior Security Analyst',
    orgKey: 'ironleaf',
    url: 'https://jobs.example.com/ironleaf-insurance/junior-security-analyst',
    file: 'ironleaf-junior-security-analyst.md',
    status: 'rejected',
    salary_min: 65000,
    salary_max: 75000,
    salary_range: '$65,000 - $75,000',
    location: 'Columbus, OH',
    skills: ['linux', 'networking', 'owasp', 'bash'],
    daysAgo: 85,
    updatedDaysAgo: 52,
  },
  {
    key: 'jd-tallgrass-intern',
    title: 'Software Engineering Intern',
    orgKey: 'tallgrass',
    url: 'https://jobs.example.com/tallgrass-software/software-engineering-intern',
    file: 'tallgrass-software-engineering-intern.md',
    status: 'closed',
    salary_range: '$28 per hour',
    location: 'Remote (US)',
    skills: ['python', 'java', 'git'],
    daysAgo: 115,
    updatedDaysAgo: 96,
  },
  {
    key: 'jd-quarry-backend',
    title: 'Backend Developer I',
    orgKey: 'quarry',
    url: 'https://jobs.example.com/quarry-labs/backend-developer-1',
    file: 'quarry-backend-developer.md',
    status: 'discovered',
    salary_min: 75000,
    salary_max: 90000,
    salary_range: '$75,000 - $90,000',
    location: 'Remote (US)',
    skills: ['python', 'postgresql', 'rest-apis', 'docker'],
    daysAgo: 6,
  },
  {
    key: 'jd-brightline-newgrad',
    title: 'Software Engineer I (New Grad)',
    orgKey: 'brightline',
    url: 'https://jobs.example.com/brightline-logistics/software-engineer-1',
    file: 'brightline-software-engineer-new-grad.md',
    status: 'offered',
    salary_min: 76000,
    salary_max: 84000,
    salary_range: '$76,000 - $84,000',
    location: 'Columbus, OH (hybrid)',
    skills: ['python', 'postgresql', 'docker', 'flask'],
    daysAgo: 70,
    updatedDaysAgo: 4,
  },
  {
    key: 'jd-pinecrest-web',
    title: 'Web Developer',
    orgKey: 'pinecrest',
    url: 'https://jobs.example.com/pinecrest-media/web-developer',
    file: 'pinecrest-web-developer.md',
    status: 'withdrawn',
    salary_min: 58000,
    salary_max: 66000,
    salary_range: '$58,000 - $66,000',
    location: 'Columbus, OH',
    skills: ['javascript', 'react', 'typescript'],
    daysAgo: 76,
    updatedDaysAgo: 58,
  },
  {
    key: 'jd-kestrel-data',
    title: 'Data Engineer I',
    orgKey: 'kestrel',
    url: 'https://jobs.example.com/kestrel-analytics/data-engineer-1',
    file: 'kestrel-data-engineer.md',
    status: 'applying',
    salary_min: 74000,
    salary_max: 88000,
    salary_range: '$74,000 - $88,000',
    location: 'Cincinnati, OH (hybrid)',
    skills: ['python', 'sql', 'postgresql', 'pandas'],
    daysAgo: 20,
    updatedDaysAgo: 9,
  },
  {
    key: 'jd-tallgrass-support',
    title: 'Cloud Support Associate',
    orgKey: 'tallgrass',
    url: 'https://jobs.example.com/tallgrass-software/cloud-support-associate',
    file: 'tallgrass-cloud-support-associate.md',
    status: 'discovered',
    salary_min: 62000,
    salary_max: 70000,
    salary_range: '$62,000 - $70,000',
    location: 'Remote (US)',
    skills: ['linux', 'networking', 'customer-support', 'docker', 'dns', 'http'],
    daysAgo: 3,
  },
]

export const contacts: ContactSpec[] = [
  {
    key: 'c-morgan-ashby',
    name: 'Morgan Ashby',
    title: 'Technical Recruiter',
    email: 'morgan.ashby@example.com',
    phone: '(513) 555-0117',
    linkedin: 'https://social.example.com/in/morgan-ashby',
    team: 'Talent Acquisition',
    notes: 'Prefers email; usually replies within a day.',
    orgKey: 'kestrel',
    orgLinks: [{ orgKey: 'kestrel', relationship: 'recruiter' }],
    jdLinks: [
      { jdKey: 'jd-kestrel-platform', relationship: 'recruiter' },
      { jdKey: 'jd-kestrel-data', relationship: 'recruiter' },
    ],
    resumeLinks: [],
    daysAgo: 58,
  },
  {
    key: 'c-elena-marsh',
    name: 'Dr. Elena Marsh',
    title: 'Associate Professor of Computer Science',
    email: 'elena.marsh@example.com',
    phone: '(937) 555-0164',
    dept: 'Computer Science',
    notes: 'Capstone and research advisor. Happy to be a reference; send her the posting first.',
    orgKey: 'ashgrove',
    orgLinks: [{ orgKey: 'ashgrove', relationship: 'other' }],
    jdLinks: [],
    resumeLinks: [
      { resumeKey: 'r-kestrel-platform', relationship: 'reference' },
      { resumeKey: 'r-harborview-solutions', relationship: 'reference' },
    ],
    daysAgo: 300,
  },
  {
    key: 'c-tomas-varga',
    name: 'Tomás Varga',
    title: 'Engineering Manager, Operations Tooling',
    email: 'tomas.varga@example.com',
    team: 'Operations Tooling',
    orgKey: 'brightline',
    orgLinks: [{ orgKey: 'brightline', relationship: 'manager' }],
    jdLinks: [{ jdKey: 'jd-brightline-newgrad', relationship: 'hiring_manager' }],
    resumeLinks: [{ resumeKey: 'r-kestrel-platform', relationship: 'recommender' }],
    daysAgo: 350,
  },
  {
    key: 'c-keisha-bramwell',
    name: 'Keisha Bramwell',
    title: 'Solutions Engineering Manager',
    email: 'keisha.bramwell@example.com',
    phone: '(216) 555-0139',
    orgKey: 'harborview',
    orgLinks: [{ orgKey: 'harborview', relationship: 'other' }],
    jdLinks: [{ jdKey: 'jd-harborview-solutions', relationship: 'hiring_manager' }],
    resumeLinks: [],
    daysAgo: 40,
  },
  {
    key: 'c-lena-fairchild',
    name: 'Lena Fairchild',
    title: 'HR Business Partner',
    email: 'lena.fairchild@example.com',
    dept: 'Human Resources',
    orgKey: 'ironleaf',
    orgLinks: [{ orgKey: 'ironleaf', relationship: 'hr' }],
    jdLinks: [{ jdKey: 'jd-ironleaf-security', relationship: 'interviewer' }],
    resumeLinks: [],
    daysAgo: 70,
  },
  {
    key: 'c-owen-pak',
    name: 'Owen Pak',
    title: 'Software Engineer',
    email: 'owen.pak@example.com',
    linkedin: 'https://social.example.com/in/owen-pak',
    notes: 'Hackathon teammate from Pantry Finder; offered to refer me at Quarry Labs.',
    orgKey: 'quarry',
    orgLinks: [
      { orgKey: 'quarry', relationship: 'referral' },
      { orgKey: 'midwest-civic-hack', relationship: 'peer' },
    ],
    jdLinks: [{ jdKey: 'jd-quarry-backend', relationship: 'referral' }],
    resumeLinks: [],
    daysAgo: 25,
  },
  {
    key: 'c-grace-holloway',
    name: 'Grace Holloway',
    title: 'IT Coordinator',
    email: 'grace.holloway@example.com',
    phone: '(937) 555-0182',
    orgKey: 'cedar-hollow-library',
    orgLinks: [{ orgKey: 'cedar-hollow-library', relationship: 'manager' }],
    jdLinks: [{ jdKey: 'jd-tallgrass-support', relationship: 'other' }],
    resumeLinks: [{ resumeKey: 'r-tallgrass-intern', relationship: 'other' }],
    daysAgo: 360,
  },
]

const SUMMARY = 'Summary'
const EXPERIENCE = 'Experience'
const SKILLS = 'Technical Skills'
const EDUCATION = 'Education & Certifications'
const PROJECTS = 'Selected Projects'
const CERTIFICATIONS = 'Certifications'

export const resumes: ResumeSpec[] = [
  {
    key: 'r-kestrel-platform',
    name: 'Kestrel Analytics - Associate Platform Engineer',
    target_role: 'Associate Platform Engineer',
    target_employer: 'Kestrel Analytics',
    archetype: 'infrastructure',
    template: 'Standard Tech Resume',
    summaryKey: 's-platform',
    status: 'approved',
    extraSections: [{ title: CERTIFICATIONS, entry_type: 'certifications' }],
    entries: [
      { section: EXPERIENCE, perspectiveKey: 'p-bl-metrics-infra' },
      { section: EXPERIENCE, perspectiveKey: 'p-bl-query-infra' },
      { section: EXPERIENCE, perspectiveKey: 'p-bl-docker-infra' },
      { section: EXPERIENCE, perspectiveKey: 'p-bl-grafana-infra' },
      { section: EXPERIENCE, perspectiveKey: 'p-hd-script-infra' },
      { key: 'r1-exp-ta-container', section: EXPERIENCE, perspectiveKey: 'p-ta-container-infra' },
      { section: EDUCATION, sourceKey: 'bs-cs' },
      { section: EDUCATION, sourceKey: 'ms-se' },
      { section: EDUCATION, sourceKey: 'bootcamp' },
      { section: PROJECTS, perspectiveKey: 'p-cap-ci-infra' },
      { section: PROJECTS, perspectiveKey: 'p-cap-api-infra' },
      { section: PROJECTS, perspectiveKey: 'p-bc-final-infra' },
      { section: PROJECTS, perspectiveKey: 'p-talk-infra' },
    ],
    skills: { [SKILLS]: ['python', 'bash', 'sql', 'postgresql', 'docker', 'kubernetes', 'terraform', 'linux', 'git', 'grafana'] },
    certifications: { [CERTIFICATIONS]: ['ocsc-acp', 'osg-linux'] },
    jdKeys: ['jd-kestrel-platform', 'jd-brightline-newgrad', 'jd-kestrel-data'],
    daysAgo: 60,
    updatedDaysAgo: 20,
  },
  {
    key: 'r-harborview-solutions',
    name: 'Harborview Health Partners - Associate Solutions Engineer',
    target_role: 'Associate Solutions Engineer',
    target_employer: 'Harborview Health Partners',
    archetype: 'solutions-architect',
    template: 'Standard Tech Resume',
    summaryKey: 's-solutions',
    status: 'in_review',
    extraSections: [{ title: CERTIFICATIONS, entry_type: 'certifications' }],
    entries: [
      { key: 'r2-exp-metrics', section: EXPERIENCE, perspectiveKey: 'p-bl-metrics-sa' },
      { section: EXPERIENCE, perspectiveKey: 'p-ta-labs-lead' },
      { section: EXPERIENCE, perspectiveKey: 'p-ta-autograder-sa' },
      { section: EXPERIENCE, perspectiveKey: 'p-ta-container-sa' },
      { section: EXPERIENCE, perspectiveKey: 'p-hd-tickets-sa' },
      { section: EDUCATION, sourceKey: 'bs-cs' },
      { section: EDUCATION, sourceKey: 'ms-se' },
      { section: PROJECTS, perspectiveKey: 'p-cap-app-sa' },
      { section: PROJECTS, perspectiveKey: 'p-cap-api-sa' },
      { section: PROJECTS, perspectiveKey: 'p-cap-pred-sa' },
      { section: PROJECTS, perspectiveKey: 'p-hack-app-sa' },
      { section: PROJECTS, perspectiveKey: 'p-hack-award-sa' },
      { section: PROJECTS, perspectiveKey: 'p-talk-sa' },
    ],
    skills: {
      [SKILLS]: ['typescript', 'javascript', 'react', 'express', 'python', 'postgresql', 'rest-apis', 'technical-writing', 'customer-support', 'agile'],
    },
    certifications: { [CERTIFICATIONS]: ['ocsc-acp', 'learnwell-web'] },
    jdKeys: ['jd-harborview-solutions'],
    daysAgo: 45,
    updatedDaysAgo: 30,
  },
  {
    key: 'r-blueheron-ml',
    name: 'Blue Heron Robotics - Junior ML Engineer',
    target_role: 'Junior Machine Learning Engineer',
    target_employer: 'Blue Heron Robotics',
    archetype: 'agentic-ai',
    template: 'Standard Tech Resume',
    status: 'draft',
    extraSections: [],
    entries: [
      {
        key: 'r3-summary',
        section: SUMMARY,
        content:
          'Recent computer science graduate who has trained, evaluated and shipped small predictive models, and enjoys the data cleaning that makes them work.',
      },
      { section: EXPERIENCE, perspectiveKey: 'p-bl-query-infra' },
      { section: EXPERIENCE, perspectiveKey: 'p-ta-autograder-se' },
      { section: EDUCATION, sourceKey: 'bs-cs' },
      { section: PROJECTS, perspectiveKey: 'p-cap-pred-ai' },
      { section: PROJECTS, perspectiveKey: 'p-poster-models-ai' },
      { section: PROJECTS, perspectiveKey: 'p-hack-import-ai' },
    ],
    skills: { [SKILLS]: ['python', 'pandas', 'scikit-learn', 'llm-apis', 'sql'] },
    certifications: {},
    jdKeys: ['jd-blueheron-ml'],
    daysAgo: 15,
  },
  {
    key: 'r-ironleaf-security',
    name: 'Ironleaf Insurance Group - Junior Security Analyst',
    target_role: 'Junior Security Analyst',
    target_employer: 'Ironleaf Insurance Group',
    archetype: 'security-engineer',
    template: 'Standard Tech Resume',
    status: 'rejected',
    extraSections: [],
    entries: [
      {
        key: 'r4-summary',
        section: SUMMARY,
        content: 'Help desk and Linux automation background, with bootcamp training in hardening and least-privilege access.',
      },
      { section: EXPERIENCE, perspectiveKey: 'p-hd-script-sec' },
      { section: EXPERIENCE, perspectiveKey: 'p-hd-tickets-pub' },
      { section: EDUCATION, sourceKey: 'bootcamp' },
    ],
    skills: { [SKILLS]: ['linux', 'bash', 'owasp', 'ssh-hardening', 'networking'] },
    certifications: {},
    jdKeys: ['jd-ironleaf-security'],
    daysAgo: 80,
    updatedDaysAgo: 50,
  },
  {
    key: 'r-tallgrass-intern',
    name: 'Tallgrass Software - Software Engineering Intern',
    target_role: 'Software Engineering Intern',
    target_employer: 'Tallgrass Software',
    archetype: 'infrastructure',
    template: 'Standard Tech Resume',
    status: 'archived',
    extraSections: [],
    entries: [
      {
        key: 'r5-summary',
        section: SUMMARY,
        content: 'Computer science student looking for a summer internship building backend features.',
      },
      { section: EXPERIENCE, perspectiveKey: 'p-hd-tickets-sa' },
      { section: EDUCATION, sourceKey: 'bs-cs' },
      { section: PROJECTS, perspectiveKey: 'p-hack-app-pub' },
    ],
    skills: { [SKILLS]: ['python', 'java', 'git'] },
    certifications: {},
    jdKeys: ['jd-tallgrass-intern'],
    daysAgo: 110,
    updatedDaysAgo: 95,
  },
]

export const notes: NoteSpec[] = [
  {
    key: 'n-kestrel-prep',
    title: 'Kestrel interview prep',
    content:
      'Second-round interview with the platform team next week. Review the Grafana alerting work and the PostgreSQL index story; ask how on-call works for associates. Morgan said the panel includes a short take-home review.',
    refs: [
      { type: 'job_description', key: 'jd-kestrel-platform' },
      { type: 'organization', key: 'kestrel' },
      { type: 'contact', key: 'c-morgan-ashby' },
      { type: 'resume', key: 'r-kestrel-platform' },
    ],
    daysAgo: 12,
  },
  {
    key: 'n-capstone-points',
    title: 'Capstone talking points',
    content:
      'Lead with the pilot numbers (about 400 students), then the prediction model. Keep the team-coordination story short; that bullet is archived.',
    refs: [
      { type: 'source', key: 'capstone' },
      { type: 'bullet', key: 'cap-web-app' },
      { type: 'perspective', key: 'p-cap-pred-ai' },
      { type: 'skill', key: 'react' },
    ],
    daysAgo: 40,
  },
  {
    key: 'n-harborview-tailoring',
    title: 'Tailor the Harborview resume',
    content:
      'Keisha mentioned the team explains technical trade-offs to clinicians every week. Move the metrics-service entry to the top and keep the summary under three lines.',
    refs: [
      { type: 'resume', key: 'r-harborview-solutions' },
      { type: 'resume_entry', key: 'r2-exp-metrics' },
      { type: 'contact', key: 'c-keisha-bramwell' },
    ],
    daysAgo: 30,
  },
  {
    key: 'n-cert-plan',
    title: 'Certification plan',
    content:
      'Finish the Linux administrator exam before the cloud practitioner renewal window opens. Practice labs: SSH hardening, systemd units, log rotation.',
    refs: [
      { type: 'certification', key: 'osg-linux' },
      { type: 'certification', key: 'ocsc-acp' },
      { type: 'skill', key: 'linux' },
    ],
    daysAgo: 50,
  },
  {
    key: 'n-relocation',
    title: 'Relocation and commute',
    content:
      'Pittsburgh would mean moving; Cincinnati and Columbus are a reasonable drive. Ask whether Blue Heron offers relocation help before the first call.',
    refs: [
      { type: 'credential', key: 'ohio-license' },
      { type: 'organization', key: 'blue-heron' },
    ],
    daysAgo: 15,
  },
  {
    key: 'n-marsh-followup',
    title: 'Follow up with Dr. Marsh',
    content:
      'Send the updated poster PDF and thank her for the reference. Ask whether the symposium wants alumni judges next spring.',
    refs: [
      { type: 'contact', key: 'c-elena-marsh' },
      { type: 'source', key: 'research-poster' },
    ],
    daysAgo: 8,
  },
  {
    key: 'n-pinecrest-withdrawal',
    content:
      'Withdrew from the Pinecrest web developer process: the role turned out to be mostly CMS theming. Watch for openings on their platform team instead.',
    refs: [
      { type: 'job_description', key: 'jd-pinecrest-web' },
      { type: 'organization', key: 'pinecrest' },
    ],
    daysAgo: 57,
  },
]
