/**
 * early-career-developer: sources, bullets and perspectives.
 *
 * Source statuses other than `draft`, and the `archived` bullets and perspectives, are set
 * by the post-pass overlay (no API route reaches them).
 */

import type { BulletSpec, PerspectiveSpec, SourceSpec } from '../../corpus/types'

export const sources: SourceSpec[] = [
  {
    key: 'bs-cs',
    title: 'B.S. in Computer Science',
    description:
      'Bachelor of Science in Computer Science from Ashgrove State University. Coursework in data structures, algorithms, operating systems, databases and computer networks; senior capstone on campus shuttle tracking. Graduated with a 3.62 GPA while working part-time.',
    source_type: 'education',
    status: 'approved',
    start: { monthsAgo: 64 },
    end: { monthsAgo: 16, day: 10 },
    education: {
      education_type: 'degree',
      orgKey: 'ashgrove',
      campusKey: 'ashgrove/main',
      field: 'Computer Science',
      degree_level: 'bachelors',
      degree_type: 'BS',
      gpa: '3.62',
      location: 'Dayton, OH',
    },
    skills: ['python', 'java', 'data-structures', 'sql', 'networking'],
    daysAgo: 400,
  },
  {
    key: 'ms-se',
    title: 'M.S. in Software Engineering (in progress)',
    description:
      "Part-time online master's program in software engineering at Ashgrove State University. Current coursework covers distributed systems, cloud architecture and software testing; expected completion in two years.",
    source_type: 'education',
    status: 'in_review',
    start: { monthsAgo: 13 },
    education: {
      education_type: 'degree',
      orgKey: 'ashgrove',
      campusKey: 'ashgrove/online',
      field: 'Software Engineering',
      degree_level: 'masters',
      degree_type: 'MS',
      is_in_progress: true,
      edu_description: 'Part-time, online. Two courses per semester.',
    },
    skills: ['kubernetes', 'redis', 'tdd'],
    daysAgo: 380,
  },
  {
    key: 'bootcamp',
    title: 'Cloud Foundations Bootcamp',
    description:
      'Ten-week evening bootcamp at Summit Code Institute covering Linux administration, containers, infrastructure as code and cloud networking. The final project deployed a three-tier sample application with Terraform and Docker.',
    source_type: 'education',
    status: 'approved',
    start: { monthsAgo: 11 },
    end: { monthsAgo: 9 },
    education: {
      education_type: 'certificate',
      orgKey: 'summit-code',
      certificate_subtype: 'completion',
      credential_id: 'SCI-CF-1182',
      url: 'https://summitcode.example.org/certificates/SCI-CF-1182',
      field: 'Cloud Infrastructure',
    },
    skills: ['linux', 'docker', 'terraform', 'networking'],
    daysAgo: 280,
  },
  {
    key: 'k8s-course',
    title: 'Kubernetes Essentials (online course)',
    description:
      'Self-paced Learnwell Academy course on Kubernetes fundamentals: pods, deployments, services, config maps and basic troubleshooting, with hands-on labs on a local cluster.',
    source_type: 'education',
    status: 'draft',
    start: { monthsAgo: 3 },
    end: { monthsAgo: 2 },
    education: {
      education_type: 'course',
      orgKey: 'learnwell',
      url: 'https://learnwell.example.com/courses/kubernetes-essentials',
      field: 'Container Orchestration',
    },
    skills: ['kubernetes', 'docker'],
    daysAgo: 70,
  },
  {
    key: 'self-taught-systems',
    title: 'Self-directed study: systems design',
    description:
      'Working through a systems design reading list and building small prototypes of caches, queues and rate limiters to understand their trade-offs.',
    source_type: 'education',
    status: 'rejected',
    start: { monthsAgo: 8 },
    education: { education_type: 'self_taught', field: 'Systems Design', is_in_progress: true },
    skills: ['redis', 'python'],
    daysAgo: 200,
  },
  {
    key: 'brightline-intern',
    title: 'Software Engineering Intern, Brightline Logistics',
    description:
      "Summer internship on the operations tooling team. Built internal services and dashboards in Python and PostgreSQL for shipment tracking, containerized tools with Docker, and joined the team's code review rotation.",
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 28 },
    end: { monthsAgo: 25, day: 22 },
    role: { orgKey: 'brightline', work_arrangement: 'hybrid', total_comp_notes: 'Paid internship, hourly.' },
    skills: ['python', 'flask', 'postgresql', 'docker', 'grafana', 'sql'],
    daysAgo: 398,
  },
  {
    key: 'ashgrove-ta',
    title: 'Teaching Assistant, Data Structures',
    description:
      'Teaching assistant for the sophomore Data Structures course at Ashgrove State University for four semesters. Led weekly labs, wrote and graded programming assignments, and held office hours.',
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 40 },
    end: { monthsAgo: 16, day: 5 },
    role: { orgKey: 'ashgrove', work_arrangement: 'on-site' },
    skills: ['java', 'data-structures', 'junit', 'mentoring'],
    daysAgo: 396,
  },
  {
    key: 'library-helpdesk',
    title: 'IT Help Desk Technician (part-time), Cedar Hollow Public Library',
    description:
      'Part-time help desk role supporting staff and public computers across two library branches: account and printer issues, Wi-Fi troubleshooting, PC imaging and basic network maintenance.',
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 52 },
    end: { monthsAgo: 17 },
    role: { orgKey: 'cedar-hollow-library', work_arrangement: 'on-site' },
    skills: ['customer-support', 'windows-server', 'bash', 'networking', 'linux'],
    daysAgo: 394,
  },
  {
    key: 'capstone',
    title: 'Capstone: Campus Shuttle Tracker',
    description:
      'Senior capstone project with a four-person team: a web app that shows live campus shuttle locations and predicted arrival times. Built with TypeScript, React, Express and PostgreSQL, deployed in Docker containers, and piloted for one semester.',
    source_type: 'project',
    status: 'approved',
    start: { monthsAgo: 24 },
    end: { monthsAgo: 16 },
    project: { orgKey: 'ashgrove', url: 'https://code.example.com/avery-lindqvist/shuttle-tracker' },
    skills: ['typescript', 'react', 'express', 'postgresql', 'docker', 'agile'],
    daysAgo: 390,
  },
  {
    key: 'hackathon',
    title: 'Midwest Civic Hack: Pantry Finder',
    description:
      'Weekend hackathon project with one teammate: a mobile-friendly site that helps residents find nearby food pantries and their opening hours, built on Flask and SQLite with an open map tile service. Released under an open-source license.',
    source_type: 'project',
    status: 'approved',
    start: { monthsAgo: 30, day: 12 },
    end: { monthsAgo: 30, day: 14 },
    project: { orgKey: 'midwest-civic-hack', is_personal: true, open_source: true, url: 'https://code.example.com/avery-lindqvist/pantry-finder' },
    skills: ['python', 'flask', 'sqlite', 'pandas'],
    daysAgo: 385,
  },
  {
    key: 'lightning-talk',
    title: 'Lightning talk: Five Dockerfile mistakes I made',
    description:
      'Five-minute lightning talk at the Columbus Developers Meetup on common Dockerfile mistakes (huge images, running as root, cache busting) and how to catch them in review.',
    source_type: 'presentation',
    status: 'in_review',
    start: { monthsAgo: 6, day: 18 },
    end: { monthsAgo: 6, day: 18 },
    presentation: {
      venue: 'Columbus Developers Meetup',
      presentation_type: 'lightning_talk',
      url: 'https://meetup.example.org/columbus-dev/lightning-night',
    },
    skills: ['docker', 'public-speaking'],
    daysAgo: 170,
  },
  {
    key: 'research-poster',
    title: 'Poster: Predicting shuttle arrival times',
    description:
      'Poster at the Ashgrove State Undergraduate Research Symposium comparing three simple models for predicting campus shuttle arrival times from GPS history.',
    source_type: 'presentation',
    status: 'approved',
    start: { monthsAgo: 17, day: 21 },
    end: { monthsAgo: 17, day: 21 },
    presentation: {
      venue: 'Ashgrove State Undergraduate Research Symposium',
      presentation_type: 'poster',
      coauthors: 'Dana Whitfield; Elena Marsh (advisor)',
    },
    skills: ['python', 'scikit-learn', 'pandas', 'public-speaking'],
    daysAgo: 388,
  },
  {
    key: 'oss-docs',
    title: 'Open-source contributions: static site generator',
    description:
      'Occasional contributions to an open-source static site generator: two bug fixes in the Markdown front-matter parser and a rewrite of the installation guide.',
    source_type: 'general',
    status: 'archived',
    start: { monthsAgo: 20 },
    end: { monthsAgo: 14 },
    skills: ['git', 'technical-writing', 'python', 'pytest'],
    daysAgo: 330,
  },
  {
    key: 'homelab',
    title: 'Home lab',
    description:
      'A three-node home lab of small single-board computers running Linux, Docker and Grafana, used to practice monitoring, backups and upgrades.',
    source_type: 'general',
    status: 'draft',
    start: { monthsAgo: 7 },
    skills: ['linux', 'docker', 'grafana', 'ssh-hardening', 'dns'],
    daysAgo: 45,
  },
]

export const bullets: BulletSpec[] = [
  // Brightline internship
  {
    key: 'bl-metrics-service',
    sourceKey: 'brightline-intern',
    content: 'Built a Flask service that exposed shipment-delay metrics to the operations dashboard, replacing a nightly spreadsheet export.',
    technologies: ['python', 'flask', 'postgresql'],
    metrics: 'Replaced a nightly manual export',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 397,
    reviewedDaysAgo: 395,
  },
  {
    key: 'bl-query-tuning',
    sourceKey: 'brightline-intern',
    content: 'Rewrote the slowest dashboard queries and added two PostgreSQL indexes, cutting report load time from about 40 seconds to under 4.',
    technologies: ['postgresql', 'sql'],
    metrics: 'Report load time from ~40s to under 4s',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 397,
    reviewedDaysAgo: 395,
  },
  {
    key: 'bl-docker-onboarding',
    sourceKey: 'brightline-intern',
    content: 'Containerized two internal tools with Docker and wrote the local setup guide, shortening new-intern onboarding from two days to half a day.',
    technologies: ['docker', 'linux', 'technical-writing'],
    metrics: 'Onboarding from 2 days to half a day',
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 397,
    reviewedDaysAgo: 395,
  },
  {
    key: 'bl-grafana-alerts',
    sourceKey: 'brightline-intern',
    content: 'Added Grafana panels and alert thresholds for queue backlog so on-call engineers saw stalled shipments before customers reported them.',
    technologies: ['grafana', 'postgresql'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 397,
    reviewedDaysAgo: 394,
  },
  {
    key: 'bl-code-review',
    sourceKey: 'brightline-intern',
    content: "Took part in code reviews for the routing team's Python services.",
    technologies: ['python', 'code-review'],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Too vague: say what changed because of the reviews.',
    daysAgo: 397,
    reviewedDaysAgo: 394,
  },
  {
    key: 'bl-learned',
    sourceKey: 'brightline-intern',
    content: 'Learned a lot about how logistics companies work.',
    technologies: [],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Not an accomplishment: no action or outcome.',
    daysAgo: 397,
    reviewedDaysAgo: 394,
  },
  {
    key: 'bl-demo',
    sourceKey: 'brightline-intern',
    content: 'Demoed the delay-metrics service to about 30 operations staff at the end of the internship and collected feature requests for the next intern.',
    technologies: ['public-speaking'],
    metrics: 'Audience of ~30',
    via: 'draft',
    status: 'draft',
    daysAgo: 150,
  },
  // Teaching assistant
  {
    key: 'ta-labs',
    sourceKey: 'ashgrove-ta',
    content: 'Led weekly lab sections for about 35 students, covering linked lists through graph traversal in Java.',
    technologies: ['java', 'data-structures', 'mentoring'],
    metrics: '~35 students per section',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 395,
    reviewedDaysAgo: 393,
  },
  {
    key: 'ta-autograder',
    sourceKey: 'ashgrove-ta',
    content: 'Wrote 12 autograded Java assignments with JUnit test suites, which cut grading time per assignment by roughly half.',
    technologies: ['java', 'junit', 'tdd'],
    metrics: '12 assignments; grading time down ~50%',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 395,
    reviewedDaysAgo: 393,
  },
  {
    key: 'ta-office-hours',
    sourceKey: 'ashgrove-ta',
    content: 'Held office hours and answered course forum questions, keeping the median response time under six hours during exam weeks.',
    technologies: ['mentoring', 'technical-writing'],
    metrics: 'Median forum response under 6 hours',
    via: 'derive',
    status: 'in_review',
    daysAgo: 395,
  },
  {
    key: 'ta-lab-container',
    sourceKey: 'ashgrove-ta',
    content: 'Packaged the course toolchain in a Docker image so students could run labs on any laptop, ending first-week setup problems.',
    technologies: ['docker', 'linux'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 395,
    reviewedDaysAgo: 392,
  },
  // Library help desk
  {
    key: 'hd-tickets',
    sourceKey: 'library-helpdesk',
    content: 'Resolved about 25 staff and patron tickets a week covering printers, Wi-Fi, account lockouts and PC issues across two branches.',
    technologies: ['customer-support', 'windows-server', 'networking'],
    metrics: '~25 tickets per week',
    via: 'derive',
    status: 'approved',
    daysAgo: 393,
    reviewedDaysAgo: 391,
  },
  {
    key: 'hd-reimage-script',
    sourceKey: 'library-helpdesk',
    content: 'Scripted nightly resets of public computers with Bash and a scheduled job, cutting manual reimaging time by roughly 70%.',
    technologies: ['bash', 'linux'],
    metrics: '~70% less manual reimaging',
    domain: 'systems_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 393,
    reviewedDaysAgo: 391,
  },
  {
    key: 'hd-runbook',
    sourceKey: 'library-helpdesk',
    content: 'Wrote a troubleshooting runbook for the five most common ticket types.',
    technologies: ['technical-writing'],
    metrics: null,
    via: 'derive',
    status: 'in_review',
    reopenedAfter: 'Add the outcome: did tickets get resolved faster?',
    daysAgo: 393,
  },
  {
    key: 'hd-intake-form',
    sourceKey: 'library-helpdesk',
    content: 'Proposed a simple web intake form so staff could report issues with screenshots instead of phone calls.',
    technologies: ['customer-support'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 140,
  },
  // Capstone
  {
    key: 'cap-web-app',
    sourceKey: 'capstone',
    content: 'Designed and built a shuttle-tracking web app in TypeScript and React that about 400 students used during the pilot semester.',
    technologies: ['typescript', 'react'],
    metrics: '~400 pilot users',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 389,
    reviewedDaysAgo: 387,
  },
  {
    key: 'cap-api',
    sourceKey: 'capstone',
    content: 'Modeled stops, routes and GPS pings in PostgreSQL and served them through a REST API built with Express.',
    technologies: ['postgresql', 'express', 'rest-apis'],
    metrics: null,
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 389,
    reviewedDaysAgo: 387,
  },
  {
    key: 'cap-ci',
    sourceKey: 'capstone',
    content: 'Set up a CI pipeline that ran the test suite and built Docker images on every pull request.',
    technologies: ['docker', 'git', 'tdd'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 389,
    reviewedDaysAgo: 387,
  },
  {
    key: 'cap-team',
    sourceKey: 'capstone',
    content: 'Coordinated a four-person team with two-week sprints, a shared task board and weekly demos to our advisor.',
    technologies: ['agile', 'mentoring'],
    metrics: '4-person team',
    domain: 'leadership',
    via: 'derive',
    status: 'archived',
    daysAgo: 389,
    reviewedDaysAgo: 387,
  },
  {
    key: 'cap-prediction',
    sourceKey: 'capstone',
    content: 'Fit a regression model on historical GPS pings that predicted arrival times within two minutes for 80% of trips.',
    technologies: ['python', 'scikit-learn', 'pandas'],
    metrics: 'Within 2 minutes for 80% of trips',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 389,
    reviewedDaysAgo: 386,
  },
  // Hackathon
  {
    key: 'hack-pantry-app',
    sourceKey: 'hackathon',
    content: 'Built a food-pantry finder in 36 hours with one teammate using Flask, SQLite and an open map tile service.',
    technologies: ['flask', 'sqlite', 'python'],
    metrics: 'Built in 36 hours',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 384,
    reviewedDaysAgo: 383,
  },
  {
    key: 'hack-importer',
    sourceKey: 'hackathon',
    content: 'Wrote the data importer that cleaned and geocoded 300 pantry listings from a county spreadsheet.',
    technologies: ['python', 'pandas'],
    metrics: '300 listings',
    via: 'derive',
    status: 'approved',
    daysAgo: 384,
    reviewedDaysAgo: 383,
  },
  {
    key: 'hack-award',
    sourceKey: 'hackathon',
    content: 'Won the Best Civic Impact award out of 22 teams.',
    technologies: [],
    metrics: '1st of 22 teams in category',
    via: 'derive',
    status: 'approved',
    daysAgo: 384,
    reviewedDaysAgo: 383,
  },
  // Bachelor's degree
  {
    key: 'bs-coursework',
    sourceKey: 'bs-cs',
    content: 'Completed coursework in algorithms, operating systems, databases and computer networks.',
    technologies: ['data-structures', 'sql', 'networking'],
    metrics: null,
    via: 'derive',
    status: 'approved',
    daysAgo: 399,
    reviewedDaysAgo: 399,
  },
  {
    key: 'bs-gpa',
    sourceKey: 'bs-cs',
    content: 'Graduated with a 3.62 GPA while working part-time throughout the degree.',
    technologies: [],
    metrics: '3.62 GPA',
    via: 'derive',
    status: 'approved',
    daysAgo: 399,
    reviewedDaysAgo: 399,
  },
  // Bootcamp
  {
    key: 'bc-final-project',
    sourceKey: 'bootcamp',
    content: "Deployed a three-tier sample application with Terraform and Docker as the bootcamp's final project.",
    technologies: ['terraform', 'docker', 'linux'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 279,
    reviewedDaysAgo: 276,
  },
  {
    key: 'bc-hardening',
    sourceKey: 'bootcamp',
    content: 'Practiced least-privilege access, SSH hardening and secrets handling in guided security labs.',
    technologies: ['ssh-hardening', 'owasp', 'linux'],
    metrics: null,
    domain: 'security',
    via: 'derive',
    status: 'in_review',
    daysAgo: 279,
  },
  // Master's (in progress)
  {
    key: 'ms-rate-limiter',
    sourceKey: 'ms-se',
    content: 'Building a course project that load-tests a Redis-backed rate limiter under simulated traffic spikes.',
    technologies: ['redis', 'python'],
    metrics: null,
    via: 'derive',
    status: 'in_review',
    daysAgo: 60,
  },
  // Lightning talk
  {
    key: 'talk-dockerfile',
    sourceKey: 'lightning-talk',
    content: 'Gave a five-minute talk to about 60 meetup attendees on common Dockerfile mistakes and how to catch them in code review.',
    technologies: ['docker', 'public-speaking'],
    metrics: '~60 attendees',
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 168,
    reviewedDaysAgo: 165,
  },
  // Research poster
  {
    key: 'poster-presented',
    sourceKey: 'research-poster',
    content: 'Presented a research poster on shuttle arrival prediction at the undergraduate research symposium.',
    technologies: ['public-speaking'],
    metrics: null,
    via: 'derive',
    status: 'approved',
    daysAgo: 387,
    reviewedDaysAgo: 386,
  },
  {
    key: 'poster-models',
    sourceKey: 'research-poster',
    content: 'Compared three baseline models and reported prediction error by route and time of day.',
    technologies: ['python', 'scikit-learn'],
    metrics: null,
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 387,
    reviewedDaysAgo: 386,
  },
  // Open-source contributions (the source is archived later)
  {
    key: 'oss-fixes',
    sourceKey: 'oss-docs',
    content: "Fixed two bugs in an open-source static site generator's front-matter parser and rewrote its installation guide.",
    technologies: ['python', 'pytest', 'git', 'technical-writing'],
    metrics: '2 merged fixes',
    via: 'derive',
    status: 'archived',
    daysAgo: 329,
    reviewedDaysAgo: 328,
  },
  // Drafts on draft sources
  {
    key: 'k8s-labs',
    sourceKey: 'k8s-course',
    content: 'Completed hands-on labs deploying, scaling and debugging a sample service on a local Kubernetes cluster.',
    technologies: ['kubernetes', 'docker'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 66,
  },
  {
    key: 'homelab-monitoring',
    sourceKey: 'homelab',
    content: 'Run a three-node home lab with Linux, Docker and Grafana to practice monitoring, backups and upgrades.',
    technologies: ['linux', 'docker', 'grafana'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 44,
  },
]

export const perspectives: PerspectiveSpec[] = [
  // bl-metrics-service
  {
    key: 'p-bl-metrics-infra',
    bulletKey: 'bl-metrics-service',
    content: 'Replaced a nightly spreadsheet export with a Flask metrics service feeding the operations dashboard, giving the team same-day visibility into shipment delays.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 300,
  },
  {
    key: 'p-bl-metrics-sa',
    bulletKey: 'bl-metrics-service',
    content: "Turned an operations team's manual delay report into a small Flask service, working with the analysts who used it to decide which metrics mattered.",
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 300,
  },
  // bl-query-tuning
  {
    key: 'p-bl-query-infra',
    bulletKey: 'bl-query-tuning',
    content: 'Cut dashboard report load time from about 40 seconds to under 4 by rewriting queries and adding targeted PostgreSQL indexes.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 299,
  },
  {
    key: 'p-bl-query-hft',
    bulletKey: 'bl-query-tuning',
    content: 'Shaved report latency by an order of magnitude through query plan analysis and index design.',
    archetype: 'hft', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'rejected',
    rejection_reason: 'HFT framing overstates a reporting-query fix.', daysAgo: 299,
  },
  // bl-docker-onboarding
  {
    key: 'p-bl-docker-infra',
    bulletKey: 'bl-docker-onboarding',
    content: 'Containerized two internal tools and documented local setup, cutting new-intern onboarding from two days to half a day.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 298,
  },
  {
    key: 'p-bl-docker-sa',
    bulletKey: 'bl-docker-onboarding',
    content: 'Owned the developer setup experience for two internal tools, from the Dockerfiles to the written guide.',
    archetype: 'solutions-architect', domain: 'devops', framing: 'responsibility', via: 'draft', status: 'draft', daysAgo: 120,
  },
  // bl-grafana-alerts
  {
    key: 'p-bl-grafana-infra',
    bulletKey: 'bl-grafana-alerts',
    content: 'Built Grafana panels and backlog alerts that let on-call engineers catch stalled shipment queues before customers noticed.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 298,
  },
  {
    key: 'p-bl-grafana-sec',
    bulletKey: 'bl-grafana-alerts',
    content: "Added monitoring and alert thresholds on a shipment queue as part of the team's operational readiness work.",
    archetype: 'security-engineer', domain: 'devops', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 82,
  },
  // ta-labs
  {
    key: 'p-ta-labs-lead',
    bulletKey: 'ta-labs',
    content: 'Led weekly Java lab sections for about 35 students, explaining data structures from linked lists to graph traversal.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 290,
  },
  {
    key: 'p-ta-labs-ai',
    bulletKey: 'ta-labs',
    content: 'Taught core data structures to sophomores, the same graph and search foundations that planning algorithms build on.',
    archetype: 'agentic-ai', domain: 'leadership', framing: 'context', via: 'draft', status: 'draft', daysAgo: 18,
  },
  // ta-autograder
  {
    key: 'p-ta-autograder-se',
    bulletKey: 'ta-autograder',
    content: 'Wrote 12 autograded Java assignments with JUnit suites, halving grading time per assignment for the course staff.',
    archetype: 'infrastructure', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 290,
  },
  {
    key: 'p-ta-autograder-sa',
    bulletKey: 'ta-autograder',
    content: 'Designed automated test suites for 12 programming assignments so students got instant feedback and graders saved about half their time.',
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 289,
  },
  // ta-lab-container
  {
    key: 'p-ta-container-infra',
    bulletKey: 'ta-lab-container',
    content: 'Packaged a course toolchain as a Docker image so students in every lab section could run the labs on any laptop.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 288,
  },
  {
    key: 'p-ta-container-sa',
    bulletKey: 'ta-lab-container',
    content: 'Removed a recurring support burden for course staff by giving every student the same containerized lab environment.',
    archetype: 'solutions-architect', domain: 'devops', framing: 'context', via: 'derive', status: 'approved', daysAgo: 95,
  },
  // hd-tickets
  {
    key: 'p-hd-tickets-sa',
    bulletKey: 'hd-tickets',
    content: 'Supported library staff and patrons on about 25 tickets a week, turning vague problem reports into concrete fixes.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 287,
  },
  {
    key: 'p-hd-tickets-pub',
    bulletKey: 'hd-tickets',
    content: 'Kept public computers and Wi-Fi working for two branches of a public library, handling about 25 tickets a week.',
    archetype: 'public-sector', domain: 'systems_engineering', framing: 'context', via: 'derive', status: 'approved', daysAgo: 286,
  },
  {
    key: 'p-hd-tickets-old',
    bulletKey: 'hd-tickets',
    content: 'Worked the help desk at a public library.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'context', via: 'derive', status: 'archived', daysAgo: 380,
  },
  // hd-reimage-script
  {
    key: 'p-hd-script-infra',
    bulletKey: 'hd-reimage-script',
    content: 'Automated nightly resets of public computers with Bash and a scheduled job, removing roughly 70% of manual reimaging work.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 286,
  },
  {
    key: 'p-hd-script-sec',
    bulletKey: 'hd-reimage-script',
    content: "Automated nightly wipes of shared public computers so no patron's session data carried over to the next day.",
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 84,
  },
  // cap-web-app
  {
    key: 'p-cap-app-sa',
    bulletKey: 'cap-web-app',
    content: 'Built a shuttle-tracking web app in TypeScript and React that about 400 students relied on during its pilot semester.',
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 285,
  },
  {
    key: 'p-cap-app-ai',
    bulletKey: 'cap-web-app',
    content: 'Delivered the user-facing half of a prediction product: a TypeScript and React app showing live shuttle positions and predicted arrivals.',
    archetype: 'agentic-ai', domain: 'software_engineering', framing: 'context', via: 'derive', status: 'approved', daysAgo: 17,
  },
  {
    key: 'p-cap-app-infra',
    bulletKey: 'cap-web-app',
    content: 'Owned the front end of a four-person capstone, from component design to the production build.',
    archetype: 'infrastructure', domain: 'software_engineering', framing: 'responsibility', via: 'derive', status: 'in_review', daysAgo: 58,
  },
  // cap-api
  {
    key: 'p-cap-api-sa',
    bulletKey: 'cap-api',
    content: 'Designed the data model for stops, routes and GPS pings in PostgreSQL and exposed it through a REST API in Express.',
    archetype: 'solutions-architect', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 284,
  },
  {
    key: 'p-cap-api-infra',
    bulletKey: 'cap-api',
    content: 'Built and maintained the Express REST API and PostgreSQL schema behind a campus shuttle tracker.',
    archetype: 'infrastructure', domain: 'software_engineering', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 284,
  },
  {
    key: 'p-cap-api-ai',
    bulletKey: 'cap-api',
    content: 'Built the data layer that fed a prediction model, from GPS ingest to a queryable API.',
    archetype: 'agentic-ai', domain: 'systems_engineering', framing: 'context', via: 'draft', status: 'draft', daysAgo: 16,
  },
  // cap-ci
  {
    key: 'p-cap-ci-infra',
    bulletKey: 'cap-ci',
    content: 'Set up CI that ran tests and built Docker images on every pull request for a four-person team.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 283,
  },
  {
    key: 'p-cap-ci-sec',
    bulletKey: 'cap-ci',
    content: 'Introduced automated checks on every pull request to keep untested code out of the main branch.',
    archetype: 'security-engineer', domain: 'devops', framing: 'context', via: 'derive', status: 'rejected',
    rejection_reason: 'Nothing security-specific here; pick another archetype.', daysAgo: 83,
  },
  // cap-team (the bullet is archived later)
  {
    key: 'p-cap-team-lead',
    bulletKey: 'cap-team',
    content: 'Coordinated a four-person capstone team with two-week sprints, a shared board and weekly advisor demos.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'archived', daysAgo: 283,
  },
  // cap-prediction
  {
    key: 'p-cap-pred-ai',
    bulletKey: 'cap-prediction',
    content: 'Trained a regression model on historical GPS pings that predicted shuttle arrivals within two minutes for 80% of trips.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 282,
  },
  {
    key: 'p-cap-pred-sa',
    bulletKey: 'cap-prediction',
    content: 'Added arrival predictions to a campus app with a simple, explainable regression model rather than a heavier approach.',
    archetype: 'solutions-architect', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'approved', daysAgo: 282,
  },
  {
    key: 'p-cap-pred-hft',
    bulletKey: 'cap-prediction',
    content: 'Built a lightweight predictor on noisy GPS time series, reaching two-minute accuracy for 80% of trips.',
    archetype: 'hft', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'in_review', daysAgo: 21,
  },
  // hack-pantry-app
  {
    key: 'p-hack-app-sa',
    bulletKey: 'hack-pantry-app',
    content: 'Shipped a working food-pantry finder in 36 hours with one teammate, using Flask, SQLite and open map tiles.',
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 281,
  },
  {
    key: 'p-hack-app-pub',
    bulletKey: 'hack-pantry-app',
    content: 'Built a civic tool that helps residents find food pantries and their opening hours during a 36-hour public-interest hackathon.',
    archetype: 'public-sector', domain: 'software_engineering', framing: 'context', via: 'derive', status: 'approved', daysAgo: 281,
  },
  // hack-importer
  {
    key: 'p-hack-import-ai',
    bulletKey: 'hack-importer',
    content: 'Cleaned and geocoded 300 messy pantry listings from a county spreadsheet into a dataset the app could query.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 280,
  },
  {
    key: 'p-hack-import-infra',
    bulletKey: 'hack-importer',
    content: 'Wrote a repeatable import script for 300 pantry listings so the data could be refreshed after the hackathon.',
    archetype: 'infrastructure', domain: 'software_engineering', framing: 'accomplishment', via: 'draft', status: 'draft', daysAgo: 110,
  },
  // hack-award
  {
    key: 'p-hack-award-sa',
    bulletKey: 'hack-award',
    content: 'Won Best Civic Impact out of 22 teams at a regional civic hackathon.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 280,
  },
  {
    key: 'p-hack-award-pub',
    bulletKey: 'hack-award',
    content: 'Recognized with a Best Civic Impact award for a tool serving residents facing food insecurity.',
    archetype: 'public-sector', domain: 'leadership', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 72,
  },
  // bs-coursework / bs-gpa
  {
    key: 'p-bs-course-infra',
    bulletKey: 'bs-coursework',
    content: 'Studied operating systems, databases and computer networks as the core of a computer science degree.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'context', via: 'derive', status: 'approved', daysAgo: 279,
  },
  {
    key: 'p-bs-gpa-sa',
    bulletKey: 'bs-gpa',
    content: 'Earned a 3.62 GPA in computer science while working part-time throughout.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'context', via: 'derive', status: 'approved', daysAgo: 279,
  },
  // bc-final-project
  {
    key: 'p-bc-final-infra',
    bulletKey: 'bc-final-project',
    content: 'Deployed a three-tier application with Terraform and Docker as the capstone of a cloud foundations bootcamp.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 270,
  },
  {
    key: 'p-bc-final-sa',
    bulletKey: 'bc-final-project',
    content: 'Learned to describe infrastructure as code by building and deploying a three-tier reference application.',
    archetype: 'solutions-architect', domain: 'devops', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 64,
  },
  // talk-dockerfile
  {
    key: 'p-talk-infra',
    bulletKey: 'talk-dockerfile',
    content: 'Spoke to about 60 developers on five common Dockerfile mistakes and how to catch them in review.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 160,
  },
  {
    key: 'p-talk-sa',
    bulletKey: 'talk-dockerfile',
    content: 'Shared container best practices with a local developer community in a five-minute lightning talk.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'context', via: 'derive', status: 'approved', daysAgo: 160,
  },
  // poster
  {
    key: 'p-poster-ai',
    bulletKey: 'poster-presented',
    content: 'Presented research on predicting shuttle arrival times at an undergraduate research symposium.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'approved', daysAgo: 278,
  },
  {
    key: 'p-poster-models-ai',
    bulletKey: 'poster-models',
    content: 'Compared three baseline models for arrival prediction and reported error by route and time of day.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 278,
  },
  {
    key: 'p-poster-models-hft',
    bulletKey: 'poster-models',
    content: 'Evaluated competing predictive models on latency-sensitive time-series data.',
    archetype: 'hft', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'rejected',
    rejection_reason: 'Too far from the trading domain to be credible.', daysAgo: 22,
  },
  // oss-fixes (the bullet is archived later)
  {
    key: 'p-oss-se',
    bulletKey: 'oss-fixes',
    content: 'Landed two bug fixes and a rewritten install guide in an open-source static site generator.',
    archetype: 'infrastructure', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'archived', daysAgo: 320,
  },
]
