/**
 * early-career-developer: profile, answer bank, industries, role types, skill catalog,
 * organizations, credentials and certifications. Every name, address line, email, phone
 * number and URL is fictional; cities and states are real.
 */

import type {
  AnswerSpec,
  CertificationSpec,
  CredentialSpec,
  NamedSpec,
  OrgSpec,
  ProfileSpec,
  SkillSpec,
} from '../../corpus/types'

export const profile: ProfileSpec = {
  name: 'Avery Lindqvist',
  email: 'avery.lindqvist@example.com',
  phone: '(614) 555-0142',
  address: { name: 'Columbus, OH', street_1: '200 Example Avenue', street_2: 'Apt 3B', city: 'Columbus', state: 'OH', zip: '43215' },
  urls: [
    { key: 'linkedin', url: 'https://social.example.com/in/avery-lindqvist' },
    { key: 'github', url: 'https://code.example.com/avery-lindqvist' },
    { key: 'portfolio', url: 'https://avery-lindqvist.example.net' },
  ],
  salary_minimum: 68000,
  salary_target: 78000,
  salary_stretch: 90000,
}

export const answers: AnswerSpec[] = [
  { field_kind: 'work_auth.us', value: 'Yes' },
  { field_kind: 'work_auth.sponsorship', value: 'No' },
  { field_kind: 'eeo.gender', value: 'Decline to self-identify' },
  { field_kind: 'eeo.race', value: 'Decline to self-identify' },
  { field_kind: 'eeo.veteran', value: 'Prefer not to say' },
  { field_kind: 'eeo.disability', value: 'Prefer not to say' },
]

export const industries: NamedSpec[] = [
  { key: 'software', name: 'Software', description: 'Software products and developer tools' },
  { key: 'data-analytics', name: 'Data Analytics' },
  { key: 'healthcare', name: 'Healthcare' },
  { key: 'logistics', name: 'Logistics' },
  { key: 'insurance', name: 'Insurance' },
  { key: 'higher-ed', name: 'Higher Education' },
  { key: 'robotics', name: 'Robotics' },
]

export const roleTypes: NamedSpec[] = [
  { key: 'software-engineer', name: 'Software Engineer' },
  { key: 'platform-engineer', name: 'Platform Engineer', description: 'Internal platforms, CI/CD and infrastructure' },
  { key: 'solutions-engineer', name: 'Solutions Engineer' },
  { key: 'ml-engineer', name: 'Machine Learning Engineer' },
  { key: 'it-support', name: 'IT Support' },
]

export const skills: SkillSpec[] = [
  { key: 'python', name: 'Python', category: 'language', domains: ['software_engineering', 'ai_ml'] },
  { key: 'typescript', name: 'TypeScript', category: 'language' },
  { key: 'javascript', name: 'JavaScript', category: 'language' },
  { key: 'sql', name: 'SQL', category: 'language' },
  { key: 'java', name: 'Java', category: 'language' },
  { key: 'bash', name: 'Bash', category: 'language' },
  { key: 'react', name: 'React', category: 'framework' },
  { key: 'flask', name: 'Flask', category: 'framework' },
  { key: 'express', name: 'Express', category: 'framework' },
  { key: 'pandas', name: 'Pandas', category: 'library' },
  { key: 'scikit-learn', name: 'Scikit-learn', category: 'library', domains: ['ai_ml'] },
  { key: 'junit', name: 'JUnit', category: 'library' },
  { key: 'pytest', name: 'Pytest', category: 'library' },
  { key: 'postgresql', name: 'PostgreSQL', category: 'data_systems', domains: ['software_engineering'] },
  { key: 'sqlite', name: 'SQLite', category: 'data_systems' },
  { key: 'redis', name: 'Redis', category: 'data_systems' },
  { key: 'docker', name: 'Docker', category: 'infrastructure', domains: ['devops'] },
  { key: 'kubernetes', name: 'Kubernetes', category: 'infrastructure', domains: ['devops', 'systems_engineering'] },
  { key: 'terraform', name: 'Terraform', category: 'infrastructure', domains: ['devops'] },
  { key: 'linux', name: 'Linux', category: 'platform', domains: ['systems_engineering'] },
  { key: 'windows-server', name: 'Windows Server', category: 'platform' },
  { key: 'git', name: 'Git', category: 'tool' },
  { key: 'grafana', name: 'Grafana', category: 'tool', domains: ['devops'] },
  { key: 'agile', name: 'Agile', category: 'methodology' },
  { key: 'tdd', name: 'Test-Driven Development', category: 'methodology', domains: ['software_engineering'] },
  { key: 'code-review', name: 'Code Review', category: 'methodology' },
  { key: 'rest-apis', name: 'REST APIs', category: 'concept' },
  { key: 'data-structures', name: 'Data Structures', category: 'concept' },
  { key: 'networking', name: 'Networking Fundamentals', category: 'concept', domains: ['systems_engineering'] },
  { key: 'http', name: 'HTTP', category: 'protocol' },
  { key: 'dns', name: 'DNS', category: 'protocol' },
  { key: 'owasp', name: 'OWASP Top 10', category: 'security', domains: ['security'] },
  { key: 'ssh-hardening', name: 'SSH Hardening', category: 'security', domains: ['security'] },
  { key: 'technical-writing', name: 'Technical Writing', category: 'soft_skill' },
  { key: 'mentoring', name: 'Mentoring', category: 'soft_skill', domains: ['leadership'] },
  { key: 'customer-support', name: 'Customer Support', category: 'soft_skill' },
  { key: 'public-speaking', name: 'Public Speaking', category: 'soft_skill' },
  { key: 'llm-apis', name: 'LLM APIs', category: 'ai_ml', domains: ['ai_ml'] },
]

export const orgs: OrgSpec[] = [
  {
    key: 'ashgrove',
    name: 'Ashgrove State University',
    org_type: 'education',
    tags: ['university'],
    industry: 'Higher Education',
    size: '18,000 students',
    worked: true,
    employment_type: 'civilian',
    website: 'https://ashgrove.example.org',
    status: null,
    aliases: ['Ashgrove State', 'ASHU'],
    locations: [
      {
        key: 'main',
        name: 'Main Campus',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Dayton, OH', street_1: '100 Example Way', city: 'Dayton', state: 'OH', zip: '45409' },
      },
      { key: 'online', name: 'Online Graduate Programs', modality: 'remote' },
    ],
    daysAgo: 410,
  },
  {
    key: 'brightline',
    name: 'Brightline Logistics',
    org_type: 'company',
    tags: ['company'],
    industry: 'Logistics',
    size: '500-1,000',
    worked: true,
    employment_type: 'intern',
    website: 'https://brightline-logistics.example.com',
    glassdoor_url: 'https://reviews.example.com/brightline-logistics',
    glassdoor_rating: 3.9,
    status: 'interested',
    aliases: ['Brightline'],
    locations: [
      {
        key: 'hq',
        name: 'Columbus Headquarters',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Columbus, OH', street_1: '250 Example Boulevard', city: 'Columbus', state: 'OH', zip: '43215' },
      },
    ],
    daysAgo: 405,
  },
  {
    key: 'cedar-hollow-library',
    name: 'Cedar Hollow Public Library',
    org_type: 'nonprofit',
    tags: ['nonprofit'],
    industry: 'Public Libraries',
    worked: true,
    employment_type: 'civilian',
    website: 'https://cedarhollowlibrary.example.org',
    status: null,
    locations: [
      {
        key: 'main',
        name: 'Main Branch',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Dayton, OH', street_1: '42 Example Street', city: 'Dayton', state: 'OH', zip: '45402' },
      },
    ],
    daysAgo: 404,
  },
  {
    key: 'learnwell',
    name: 'Learnwell Academy',
    org_type: 'education',
    tags: ['platform'],
    industry: 'Online Learning',
    worked: false,
    website: 'https://learnwell.example.com',
    status: null,
    daysAgo: 395,
  },
  {
    key: 'midwest-civic-hack',
    name: 'Midwest Civic Hack',
    org_type: 'nonprofit',
    tags: ['conference', 'volunteer'],
    worked: false,
    website: 'https://civichack.example.org',
    status: null,
    daysAgo: 388,
  },
  {
    key: 'summit-code',
    name: 'Summit Code Institute',
    org_type: 'education',
    tags: ['school'],
    industry: 'Technical Training',
    worked: false,
    website: 'https://summitcode.example.org',
    status: null,
    daysAgo: 300,
  },
  {
    key: 'ocsc',
    name: 'Open Cloud Skills Council',
    org_type: 'nonprofit',
    tags: ['nonprofit'],
    industry: 'Professional Certification',
    worked: false,
    website: 'https://ocsc.example.org',
    status: null,
    daysAgo: 300,
  },
  {
    key: 'tallgrass',
    name: 'Tallgrass Software',
    org_type: 'company',
    tags: ['company'],
    industry: 'Software',
    size: '50-200',
    worked: false,
    website: 'https://tallgrass.example.com',
    status: 'researching',
    locations: [
      {
        key: 'hq',
        name: 'Indianapolis Office',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Indianapolis, IN', street_1: '75 Example Lane', city: 'Indianapolis', state: 'IN', zip: '46204' },
      },
      { key: 'remote', name: 'Remote (US)', modality: 'remote' },
    ],
    daysAgo: 140,
  },
  {
    key: 'kestrel',
    name: 'Kestrel Analytics',
    org_type: 'company',
    tags: ['company'],
    industry: 'Data Analytics',
    size: '200-500',
    worked: false,
    website: 'https://kestrel-analytics.example.com',
    linkedin_url: 'https://social.example.com/company/kestrel-analytics',
    glassdoor_url: 'https://reviews.example.com/kestrel-analytics',
    glassdoor_rating: 4.2,
    status: 'exciting',
    aliases: ['Kestrel'],
    locations: [
      {
        key: 'hq',
        name: 'Cincinnati Office',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Cincinnati, OH', street_1: '300 Example Plaza', street_2: 'Floor 6', city: 'Cincinnati', state: 'OH', zip: '45202' },
      },
    ],
    daysAgo: 118,
  },
  {
    key: 'harborview',
    name: 'Harborview Health Partners',
    org_type: 'company',
    tags: ['company'],
    industry: 'Healthcare',
    size: '5,000+',
    worked: false,
    website: 'https://harborview-health.example.org',
    status: 'interested',
    locations: [
      {
        key: 'cleveland',
        name: 'Cleveland Campus',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Cleveland, OH', street_1: '1200 Example Avenue', city: 'Cleveland', state: 'OH', zip: '44114' },
      },
    ],
    daysAgo: 100,
  },
  {
    key: 'ironleaf',
    name: 'Ironleaf Insurance Group',
    org_type: 'company',
    tags: ['company'],
    industry: 'Insurance',
    size: '1,000-5,000',
    worked: false,
    website: 'https://ironleaf.example.com',
    status: 'acceptable',
    locations: [
      {
        key: 'hq',
        name: 'Columbus Office',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Columbus, OH', street_1: '500 Example Road', city: 'Columbus', state: 'OH', zip: '43215' },
      },
    ],
    daysAgo: 90,
  },
  {
    key: 'pinecrest',
    name: 'Pinecrest Media',
    org_type: 'company',
    tags: ['company'],
    industry: 'Media',
    size: '50-200',
    worked: false,
    website: 'https://pinecrest-media.example.com',
    status: 'excluded',
    daysAgo: 80,
  },
  {
    key: 'blue-heron',
    name: 'Blue Heron Robotics',
    org_type: 'company',
    tags: ['company'],
    industry: 'Robotics',
    size: '200-500',
    worked: false,
    website: 'https://blueheron-robotics.example.com',
    status: null,
    locations: [
      {
        key: 'hq',
        name: 'Pittsburgh Lab',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Pittsburgh, PA', street_1: '80 Example Drive', city: 'Pittsburgh', state: 'PA', zip: '15222' },
      },
    ],
    daysAgo: 60,
  },
  {
    key: 'osg',
    name: 'Open Systems Guild',
    org_type: 'nonprofit',
    tags: ['nonprofit'],
    industry: 'Professional Certification',
    worked: false,
    website: 'https://opensystemsguild.example.org',
    status: null,
    daysAgo: 60,
  },
  {
    key: 'quarry',
    name: 'Quarry Labs',
    org_type: 'company',
    tags: ['company', 'vendor'],
    industry: 'Developer Tools',
    size: '11-50',
    worked: false,
    website: 'https://quarrylabs.example.com',
    status: 'backlog',
    daysAgo: 30,
  },
]

export const credentials: CredentialSpec[] = [
  {
    key: 'ohio-license',
    credential_type: 'drivers_license',
    label: 'Ohio Class D Driver License',
    status: 'active',
    details: { class: 'D', state: 'OH', endorsements: [] },
    issued: { monthsAgo: 30, day: 14 },
    expires: { monthsAgo: -18, day: 14 },
    daysAgo: 392,
  },
]

export const certifications: CertificationSpec[] = [
  {
    key: 'learnwell-web',
    short_name: 'Learnwell Responsive Web',
    long_name: 'Learnwell Academy Responsive Web Development Certificate',
    issuerKey: 'learnwell',
    earned: { monthsAgo: 30, day: 20 },
    credential_id: 'LWA-RW-58812',
    credential_url: 'https://learnwell.example.com/verify/LWA-RW-58812',
    in_progress: false,
    skills: ['javascript', 'react'],
    daysAgo: 390,
  },
  {
    key: 'ocsc-acp',
    short_name: 'OCSC Cloud Practitioner',
    long_name: 'Open Cloud Skills Council Associate Cloud Practitioner',
    cert_id: 'OCSC-ACP',
    issuerKey: 'ocsc',
    earned: { monthsAgo: 9, day: 3 },
    expires: { monthsAgo: -27, day: 3 },
    credential_id: 'OCSC-2291-4407',
    credential_url: 'https://verify.example.org/ocsc/2291-4407',
    credly_url: 'https://badges.example.com/ocsc-acp/2291-4407',
    in_progress: false,
    skills: ['docker', 'terraform', 'linux'],
    daysAgo: 270,
  },
  {
    key: 'osg-linux',
    short_name: 'OSG Linux Administrator',
    long_name: 'Open Systems Guild Certified Linux Administrator (Associate)',
    cert_id: 'OSG-LA1',
    issuerKey: 'osg',
    in_progress: true,
    skills: ['linux', 'bash', 'ssh-hardening'],
    daysAgo: 55,
  },
]
