/**
 * ai-ml-engineer: summaries, job descriptions, contacts, resumes and notes.
 *
 * Resumes: two fully built (the approved Standard Tech Resume for an agent platform role and
 * the in-review Academic CV with its presentations, publications and awards sections) and
 * three lighter ones, one per remaining status.
 */

import type { ContactSpec, JdSpec, NoteSpec, ResumeSpec, SummarySpec } from '../../corpus/types'

export const summaries: SummarySpec[] = [
  {
    key: 's-agent-platform',
    title: 'Agent platform staff engineer',
    role: 'Staff Engineer, Agent Platform',
    description:
      'Staff engineer who builds the runtime that agents run on: tool routing, sandboxing, budgets, evaluation and defenses against prompt injection. Ph.D. in robot learning; eight years taking models from research into production.',
    industryKey: 'ai',
    roleTypeKey: 'ai-platform',
    skills: ['agent-orchestration', 'llms', 'model-evaluation', 'rust', 'python', 'prompt-injection'],
    daysAgo: 60,
  },
  {
    key: 's-solutions',
    title: 'Applied AI solutions architect',
    role: 'Principal Solutions Architect',
    description:
      'Engineer who turns customer workflows into production AI systems, from retrieval-augmented assistants to agent platforms, and explains the trade-offs in plain language.',
    industryKey: 'cloud',
    roleTypeKey: 'solutions-architect',
    skills: ['rag', 'llms', 'kubernetes', 'distributed-systems', 'technical-writing'],
    daysAgo: 82,
  },
  {
    key: 's-research-template',
    title: 'Research-forward template',
    role: 'Research Scientist',
    description: 'Lead with publications, talks and the dissertation, then the systems work that put the research into production.',
    is_template: true,
    industryKey: 'quant-finance',
    roleTypeKey: 'research-scientist',
    notes: 'Pair with the Academic CV for research roles.',
    skills: ['reinforcement-learning', 'experiment-design', 'pytorch', 'jax'],
    daysAgo: 25,
  },
]

export const jds: JdSpec[] = [
  {
    key: 'jd-sablepoint-agent',
    title: 'Staff Engineer, Agent Platform',
    orgKey: 'sablepoint',
    url: 'https://jobs.example.com/sablepoint-ai/staff-engineer-agent-platform',
    file: 'sablepoint-staff-agent-platform.md',
    status: 'interviewing',
    salary_min: 245000,
    salary_max: 300000,
    salary_range: '$245,000 - $300,000',
    location: 'San Francisco, CA (hybrid)',
    skills: ['agent-orchestration', 'python', 'rust', 'kubernetes', 'model-evaluation', 'prompt-injection'],
    daysAgo: 45,
    updatedDaysAgo: 6,
  },
  {
    key: 'jd-sablepoint-eval',
    title: 'Senior Engineer, Model Evaluation',
    orgKey: 'sablepoint',
    url: 'https://jobs.example.com/sablepoint-ai/senior-engineer-model-evaluation',
    file: 'sablepoint-senior-model-evaluation.md',
    status: 'discovered',
    salary_min: 205000,
    salary_max: 250000,
    salary_range: '$205,000 - $250,000',
    location: 'San Francisco, CA (hybrid)',
    skills: ['model-evaluation', 'experiment-design', 'python', 'llms'],
    daysAgo: 11,
  },
  {
    key: 'jd-harborlight-sa',
    title: 'Principal Solutions Architect, Generative AI',
    orgKey: 'harborlight',
    url: 'https://jobs.example.com/harborlight-cloud/principal-solutions-architect-genai',
    file: 'harborlight-principal-sa-genai.md',
    status: 'offered',
    salary_min: 230000,
    salary_max: 275000,
    salary_range: '$230,000 - $275,000',
    location: 'Bellevue, WA (hybrid)',
    skills: ['rag', 'llms', 'kubernetes', 'distributed-systems', 'technical-writing', 'public-speaking'],
    daysAgo: 80,
    updatedDaysAgo: 3,
  },
  {
    key: 'jd-harborlight-partner',
    title: 'Solutions Architect, AI Partners',
    orgKey: 'harborlight',
    url: 'https://jobs.example.com/harborlight-cloud/solutions-architect-ai-partners',
    file: 'harborlight-sa-ai-partners.md',
    status: 'discovered',
    salary_min: 190000,
    salary_max: 230000,
    salary_range: '$190,000 - $230,000',
    location: 'Remote (US)',
    skills: ['llms', 'mcp', 'technical-writing'],
    daysAgo: 4,
  },
  {
    key: 'jd-quantcrest-ml',
    title: 'Senior ML Engineer, Low-Latency Signals',
    orgKey: 'quantcrest',
    url: 'https://jobs.example.com/quantcrest-capital/senior-ml-engineer-low-latency',
    file: 'quantcrest-senior-ml-low-latency.md',
    status: 'applied',
    salary_min: 250000,
    salary_max: 325000,
    salary_range: '$250,000 - $325,000 plus bonus',
    location: 'New York, NY',
    skills: ['cpp', 'python', 'low-latency', 'pytorch', 'kafka', 'linux'],
    daysAgo: 38,
    updatedDaysAgo: 30,
  },
  {
    key: 'jd-copperline-research',
    title: 'Machine Learning Researcher, Execution',
    orgKey: 'copperline',
    url: 'https://jobs.example.com/copperline-markets/ml-researcher-execution',
    file: 'copperline-ml-researcher-execution.md',
    status: 'analyzing',
    salary_min: 220000,
    salary_max: 300000,
    salary_range: '$220,000 - $300,000 plus bonus',
    location: 'New York, NY (hybrid)',
    skills: ['reinforcement-learning', 'experiment-design', 'jax', 'pytorch', 'numpy'],
    daysAgo: 24,
    updatedDaysAgo: 21,
  },
  {
    key: 'jd-northbeam-platform',
    title: 'Staff ML Platform Engineer',
    orgKey: 'northbeam',
    url: 'https://jobs.example.com/northbeam-logistics/staff-ml-platform-engineer',
    file: 'northbeam-staff-ml-platform.md',
    status: 'applying',
    salary_min: 210000,
    salary_max: 250000,
    salary_range: '$210,000 - $250,000',
    location: 'Remote (US)',
    skills: ['kubernetes', 'ray', 'mlflow', 'mlops', 'python', 'docker'],
    daysAgo: 18,
    updatedDaysAgo: 13,
  },
  {
    key: 'jd-tidewater-ai',
    title: 'Lead AI Engineer, Clinical Agents',
    orgKey: 'tidewater',
    url: 'https://jobs.example.com/tidewater-health/lead-ai-engineer-clinical-agents',
    file: 'tidewater-lead-ai-clinical-agents.md',
    status: 'withdrawn',
    salary_min: 200000,
    salary_max: 240000,
    salary_range: '$200,000 - $240,000',
    location: 'Sacramento, CA (on-site)',
    skills: ['llms', 'rag', 'agent-orchestration', 'prompt-injection'],
    daysAgo: 110,
    updatedDaysAgo: 92,
  },
  {
    key: 'jd-ironwood-robot-learning',
    title: 'Principal Robot Learning Engineer',
    orgKey: 'ironwood',
    url: 'https://jobs.example.com/ironwood-robotics/principal-robot-learning-engineer',
    file: 'ironwood-principal-robot-learning.md',
    status: 'rejected',
    salary_min: 235000,
    salary_max: 280000,
    salary_range: '$235,000 - $280,000',
    location: 'San Jose, CA',
    skills: ['reinforcement-learning', 'computer-vision', 'ros2', 'cpp', 'pytorch'],
    daysAgo: 100,
    updatedDaysAgo: 66,
  },
  {
    key: 'jd-meridian-staff',
    title: 'Staff Applied Scientist, Agents',
    orgKey: 'meridian',
    url: 'https://jobs.example.com/meridian-applied-ai/staff-applied-scientist-agents',
    file: 'meridian-staff-applied-scientist-agents.md',
    status: 'closed',
    salary_min: 220000,
    salary_max: 265000,
    salary_range: '$220,000 - $265,000',
    location: 'Remote (US)',
    skills: ['llms', 'model-evaluation', 'experiment-design', 'agent-orchestration'],
    daysAgo: 130,
    updatedDaysAgo: 105,
  },
]

export const contacts: ContactSpec[] = [
  {
    key: 'c-jonah-whitlock',
    name: 'Jonah Whitlock',
    title: 'Technical Recruiter',
    email: 'jonah.whitlock@example.com',
    phone: '(415) 555-0128',
    linkedin: 'https://social.example.com/in/jonah-whitlock',
    team: 'Talent',
    notes: 'Schedules the whole loop; prefers a call to email for anything about compensation.',
    orgKey: 'sablepoint',
    orgLinks: [{ orgKey: 'sablepoint', relationship: 'recruiter' }],
    jdLinks: [
      { jdKey: 'jd-sablepoint-agent', relationship: 'recruiter' },
      { jdKey: 'jd-sablepoint-eval', relationship: 'recruiter' },
    ],
    resumeLinks: [],
    daysAgo: 44,
  },
  {
    key: 'c-lucia-ferreira-hale',
    name: 'Dr. Lucia Ferreira-Hale',
    title: 'Professor of Robotics',
    email: 'lucia.ferreira-hale@example.com',
    phone: '(253) 555-0151',
    dept: 'Robotics',
    notes: 'Ph.D. advisor. Writes reference letters with two weeks of notice; send the posting and the current CV.',
    orgKey: 'cascadia',
    orgLinks: [{ orgKey: 'cascadia', relationship: 'other' }],
    jdLinks: [],
    resumeLinks: [
      { resumeKey: 'r-academic-cv', relationship: 'reference' },
      { resumeKey: 'r-sablepoint-agent', relationship: 'reference' },
    ],
    daysAgo: 500,
  },
  {
    key: 'c-marcus-ibsen',
    name: 'Marcus Ibsen',
    title: 'Director of Applied Science',
    email: 'marcus.ibsen@example.com',
    linkedin: 'https://social.example.com/in/marcus-ibsen',
    team: 'Client Solutions',
    notes: 'Former manager at Meridian. Flagged the staff agents opening before it was posted.',
    orgKey: 'meridian',
    orgLinks: [{ orgKey: 'meridian', relationship: 'manager' }],
    jdLinks: [{ jdKey: 'jd-meridian-staff', relationship: 'referral' }],
    resumeLinks: [{ resumeKey: 'r-sablepoint-agent', relationship: 'recommender' }],
    daysAgo: 480,
  },
  {
    key: 'c-noemi-castellan',
    name: 'Noemi Castellan',
    title: 'Director, Solutions Architecture',
    email: 'noemi.castellan@example.com',
    phone: '(425) 555-0186',
    orgKey: 'harborlight',
    orgLinks: [{ orgKey: 'harborlight', relationship: 'other' }],
    jdLinks: [{ jdKey: 'jd-harborlight-sa', relationship: 'hiring_manager' }],
    resumeLinks: [],
    daysAgo: 78,
  },
  {
    key: 'c-elliot-navarro',
    name: 'Elliot Navarro',
    title: 'HR Business Partner',
    email: 'elliot.navarro@example.com',
    dept: 'People Operations',
    orgKey: 'tidewater',
    orgLinks: [{ orgKey: 'tidewater', relationship: 'hr' }],
    jdLinks: [{ jdKey: 'jd-tidewater-ai', relationship: 'interviewer' }],
    resumeLinks: [],
    daysAgo: 104,
  },
  {
    key: 'c-sofia-kaminski',
    name: 'Sofia Kaminski',
    title: 'Senior Software Engineer',
    email: 'sofia.kaminski@example.com',
    linkedin: 'https://social.example.com/in/sofia-kaminski',
    notes: 'Co-ran the agent evaluation workshop. Sent over the Northbeam posting; happy to review drafts.',
    orgKey: 'lanternfish',
    orgLinks: [{ orgKey: 'lanternfish', relationship: 'peer' }],
    jdLinks: [{ jdKey: 'jd-northbeam-platform', relationship: 'other' }],
    resumeLinks: [{ resumeKey: 'r-northbeam-platform', relationship: 'other' }],
    daysAgo: 30,
  },
  {
    key: 'c-desmond-achterberg',
    name: 'Desmond Achterberg',
    title: 'Quantitative Developer',
    email: 'desmond.achterberg@example.com',
    phone: '(212) 555-0164',
    notes: 'Former Ironwood perception teammate, now at Quantcrest. Submitted the internal referral.',
    orgKey: 'quantcrest',
    orgLinks: [
      { orgKey: 'quantcrest', relationship: 'referral' },
      { orgKey: 'ironwood', relationship: 'peer' },
    ],
    jdLinks: [{ jdKey: 'jd-quantcrest-ml', relationship: 'referral' }],
    resumeLinks: [],
    daysAgo: 40,
  },
]

// Standard Tech Resume sections
const SUMMARY = 'Summary'
const EXPERIENCE = 'Experience'
const SKILLS = 'Technical Skills'
const EDUCATION = 'Education & Certifications'
const PROJECTS = 'Selected Projects'
// Academic CV sections
const CV_EDUCATION = 'Education'
const CV_RESEARCH = 'Research Experience'
const CV_PUBLICATIONS = 'Publications'
const CV_PRESENTATIONS = 'Presentations'
const CV_AWARDS = 'Awards'
// Added on top of either template
const CERTIFICATIONS = 'Certifications'

export const resumes: ResumeSpec[] = [
  {
    key: 'r-sablepoint-agent',
    name: 'Sablepoint AI - Staff Engineer, Agent Platform',
    target_role: 'Staff Engineer, Agent Platform',
    target_employer: 'Sablepoint AI',
    archetype: 'agentic-ai',
    template: 'Standard Tech Resume',
    summaryKey: 's-agent-platform',
    status: 'approved',
    extraSections: [{ title: CERTIFICATIONS, entry_type: 'certifications' }],
    entries: [
      { key: 'sp-exp-platform', section: EXPERIENCE, perspectiveKey: 'p-lf-platform-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-latency-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-budget-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-mcp-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-injection-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-team-lead' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-rag-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-eval-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-pipeline-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-mentoring-lead' },
      { section: EXPERIENCE, perspectiveKey: 'p-iw-grasp-ai' },
      { section: EXPERIENCE, perspectiveKey: 'p-iw-latency-ai' },
      { section: EDUCATION, sourceKey: 'phd-robotics' },
      { section: EDUCATION, sourceKey: 'bs-mech' },
      { section: PROJECTS, perspectiveKey: 'p-bramble-release-ai' },
      { section: PROJECTS, perspectiveKey: 'p-bramble-ci-ai' },
      { section: PROJECTS, perspectiveKey: 'p-pocket-sim-ai' },
      { section: PROJECTS, perspectiveKey: 'p-talk-contracts-ai' },
      { section: PROJECTS, perspectiveKey: 'p-internal-router-ai' },
    ],
    skills: {
      [SKILLS]: [
        'python', 'rust', 'agent-orchestration', 'llms', 'rag', 'model-evaluation', 'mcp', 'prompt-injection',
        'pytorch', 'fastapi', 'kubernetes', 'ray', 'redis', 'postgresql',
      ],
    },
    certifications: { [CERTIFICATIONS]: ['ampg-mlsp', 'oaf-asp'] },
    jdKeys: ['jd-sablepoint-agent', 'jd-sablepoint-eval'],
    daysAgo: 40,
    updatedDaysAgo: 8,
  },
  {
    key: 'r-academic-cv',
    name: 'Academic CV - ML Researcher',
    target_role: 'Machine Learning Researcher, Execution',
    target_employer: 'Copperline Markets',
    archetype: 'hft',
    template: 'Academic CV',
    status: 'in_review',
    extraSections: [{ title: CERTIFICATIONS, entry_type: 'certifications' }],
    entries: [
      { section: CV_EDUCATION, sourceKey: 'phd-robotics' },
      { section: CV_EDUCATION, sourceKey: 'bs-mech' },
      { key: 'cv-research-latency', section: CV_RESEARCH, perspectiveKey: 'p-lf-latency-hft' },
      { section: CV_RESEARCH, perspectiveKey: 'p-lf-injection-ai' },
      { section: CV_RESEARCH, perspectiveKey: 'p-mer-forecast-hft' },
      { section: CV_RESEARCH, perspectiveKey: 'p-mer-eval-ai' },
      { section: CV_RESEARCH, perspectiveKey: 'p-iw-latency-hft' },
      { section: CV_RESEARCH, perspectiveKey: 'p-iw-sim-hft' },
      { section: CV_PUBLICATIONS, perspectiveKey: 'p-phd-thesis-ai' },
      { section: CV_PUBLICATIONS, perspectiveKey: 'p-phd-dataset-ai' },
      { section: CV_PUBLICATIONS, perspectiveKey: 'p-bramble-release-ai' },
      { section: CV_PUBLICATIONS, perspectiveKey: 'p-pocket-jax-hft' },
      { section: CV_PRESENTATIONS, perspectiveKey: 'p-talk-contracts-ai' },
      { section: CV_PRESENTATIONS, perspectiveKey: 'p-workshop-evals-sa' },
      { section: CV_PRESENTATIONS, perspectiveKey: 'p-internal-router-ai' },
      { section: CV_PRESENTATIONS, perspectiveKey: 'p-webinar-mlops-infra' },
      { section: CV_PRESENTATIONS, perspectiveKey: 'p-poster-sparse-ai' },
      { section: CV_AWARDS, perspectiveKey: 'p-phd-award-ai' },
      {
        key: 'cv-award-paper',
        section: CV_AWARDS,
        content: 'Best Workshop Paper, Pacific Symposium on Robot Learning, for sparse-demonstration bin picking.',
      },
      { section: CV_AWARDS, perspectiveKey: 'p-bs-capstone-award' },
    ],
    skills: {
      [SKILLS]: [
        'python', 'cpp', 'rust', 'pytorch', 'jax', 'cuda', 'numpy', 'reinforcement-learning', 'computer-vision',
        'experiment-design', 'low-latency', 'distributed-systems',
      ],
    },
    certifications: { [CERTIFICATIONS]: ['ampg-mlsp'] },
    jdKeys: ['jd-copperline-research', 'jd-meridian-staff'],
    daysAgo: 20,
    updatedDaysAgo: 9,
  },
  {
    key: 'r-harborlight-sa',
    name: 'Harborlight Cloud - Principal Solutions Architect',
    target_role: 'Principal Solutions Architect, Generative AI',
    target_employer: 'Harborlight Cloud',
    archetype: 'solutions-architect',
    template: 'Standard Tech Resume',
    summaryKey: 's-solutions',
    status: 'archived',
    extraSections: [{ title: CERTIFICATIONS, entry_type: 'certifications' }],
    entries: [
      { section: EXPERIENCE, perspectiveKey: 'p-lf-platform-sa' },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-mcp-sa' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-rag-sa' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-forecast-sa' },
      { section: EDUCATION, sourceKey: 'phd-robotics' },
      { section: PROJECTS, perspectiveKey: 'p-bramble-release-sa' },
      { section: PROJECTS, perspectiveKey: 'p-workshop-evals-sa' },
    ],
    skills: { [SKILLS]: ['python', 'llms', 'rag', 'kubernetes', 'distributed-systems', 'technical-writing', 'public-speaking'] },
    certifications: { [CERTIFICATIONS]: ['harborlight-sap'] },
    jdKeys: ['jd-harborlight-sa', 'jd-harborlight-partner'],
    daysAgo: 75,
    updatedDaysAgo: 3,
  },
  {
    key: 'r-quantcrest-hft',
    name: 'Quantcrest Capital - Senior ML Engineer, Low-Latency',
    target_role: 'Senior ML Engineer, Low-Latency Signals',
    target_employer: 'Quantcrest Capital',
    archetype: 'hft',
    template: 'Standard Tech Resume',
    status: 'rejected',
    extraSections: [],
    entries: [
      {
        key: 'qc-summary',
        section: SUMMARY,
        content: 'Systems-minded ML engineer who has cut latency on robots and agent platforms by an order of magnitude, with a research background in sample-efficient learning.',
      },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-latency-hft' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-forecast-hft' },
      { section: EXPERIENCE, perspectiveKey: 'p-iw-latency-hft' },
      { section: EDUCATION, sourceKey: 'phd-robotics' },
      { section: PROJECTS, perspectiveKey: 'p-pocket-jax-hft' },
    ],
    skills: { [SKILLS]: ['cpp', 'rust', 'python', 'low-latency', 'cuda', 'kafka', 'linux'] },
    certifications: {},
    jdKeys: ['jd-quantcrest-ml'],
    daysAgo: 36,
    updatedDaysAgo: 31,
  },
  {
    key: 'r-northbeam-platform',
    name: 'Northbeam Logistics - Staff ML Platform Engineer',
    target_role: 'Staff ML Platform Engineer',
    target_employer: 'Northbeam Logistics',
    archetype: 'infrastructure',
    template: 'Standard Tech Resume',
    status: 'draft',
    extraSections: [],
    entries: [
      {
        key: 'nb-summary',
        section: SUMMARY,
        content: 'ML platform engineer who has run training pipelines, evaluation gates and agent runtimes in production.',
      },
      { section: EXPERIENCE, perspectiveKey: 'p-lf-platform-infra' },
      { section: EXPERIENCE, perspectiveKey: 'p-mer-pipeline-infra' },
      { section: EDUCATION, sourceKey: 'bs-mech' },
      { section: PROJECTS, perspectiveKey: 'p-bramble-ci-infra' },
      { section: PROJECTS, perspectiveKey: 'p-webinar-mlops-infra' },
    ],
    skills: { [SKILLS]: ['kubernetes', 'ray', 'docker', 'mlflow', 'mlops', 'python'] },
    certifications: {},
    jdKeys: ['jd-northbeam-platform'],
    daysAgo: 14,
  },
]

export const notes: NoteSpec[] = [
  {
    key: 'n-sablepoint-loop',
    title: 'Sablepoint onsite loop',
    content:
      'Four rounds next Thursday: system design (agent runtime), coding in Python, a values interview and a session with the founders. Jonah says the system design round goes deep on sandboxing and budgets; bring the tool router diagram.',
    refs: [
      { type: 'job_description', key: 'jd-sablepoint-agent' },
      { type: 'organization', key: 'sablepoint' },
      { type: 'contact', key: 'c-jonah-whitlock' },
      { type: 'resume', key: 'r-sablepoint-agent' },
      { type: 'resume_entry', key: 'sp-exp-platform' },
    ],
    daysAgo: 6,
  },
  {
    key: 'n-academic-cv',
    title: 'Academic CV for research roles',
    content:
      'Copperline wants publications and talks up front. Keep the poster and the workshop paper award; move the dissertation entry to the top of Publications. Ask whether they count open-source software as a publication.',
    refs: [
      { type: 'resume', key: 'r-academic-cv' },
      { type: 'resume_entry', key: 'cv-award-paper' },
      { type: 'resume_entry', key: 'cv-research-latency' },
      { type: 'source', key: 'talk-poster' },
      { type: 'perspective', key: 'p-phd-thesis-ai' },
    ],
    daysAgo: 9,
  },
  {
    key: 'n-summit-followups',
    title: 'Open Agents Summit follow-ups',
    content:
      'Three teams asked for the typed-contracts examples after the talk. Publish the slides and the sample schemas, and turn the Q&A on versioning into a blog post.',
    refs: [
      { type: 'source', key: 'talk-conference' },
      { type: 'bullet', key: 'b-talk-contracts' },
      { type: 'skill', key: 'agent-orchestration' },
    ],
    daysAgo: 150,
  },
  {
    key: 'n-cert-plan',
    title: 'Certification plan',
    content:
      'Finish the agent security practitioner exam before the ML systems certification lapses. The Harborlight professional cert is current until 2029; no action needed there.',
    refs: [
      { type: 'certification', key: 'oaf-asp' },
      { type: 'certification', key: 'ampg-mlsp' },
      { type: 'certification', key: 'harborlight-sap' },
      { type: 'skill', key: 'prompt-injection' },
    ],
    daysAgo: 50,
  },
  {
    key: 'n-commute',
    title: 'Sacramento commute math',
    content:
      'Tidewater wants five days on site in Sacramento. That means relocating or a long weekly drive; not worth it for this role. Withdrew after the HR screen.',
    refs: [
      { type: 'credential', key: 'wa-license' },
      { type: 'organization', key: 'tidewater' },
      { type: 'job_description', key: 'jd-tidewater-ai' },
    ],
    daysAgo: 92,
  },
  {
    key: 'n-offer-compare',
    title: 'Harborlight offer vs. Sablepoint loop',
    content:
      'Harborlight offered at the top of the posted band with a sign-on bonus; Noemi gave until the end of next week. Sablepoint equity is the open question. Ask both about on-call expectations before deciding.',
    refs: [
      { type: 'job_description', key: 'jd-harborlight-sa' },
      { type: 'organization', key: 'harborlight' },
      { type: 'contact', key: 'c-noemi-castellan' },
    ],
    daysAgo: 3,
  },
  {
    key: 'n-ferreira-letter',
    content:
      'Dr. Ferreira-Hale agreed to write a letter for the research roles. Send her the Academic CV draft and the two postings by Friday.',
    refs: [
      { type: 'contact', key: 'c-lucia-ferreira-hale' },
      { type: 'source', key: 'phd-robotics' },
    ],
    daysAgo: 18,
  },
]
