/**
 * ai-ml-engineer: sources, bullets and perspectives.
 *
 * The arc runs robotics (a Ph.D. and a robotics software role) → applied ML (forecasting
 * and a retrieval-augmented assistant) → an agent platform (the current staff role), with an
 * open-source evaluation harness, a personal simulator and one talk of every presentation
 * type along the way.
 *
 * Source statuses other than `draft`, and the `archived` bullets and perspectives, are set
 * by the post-pass overlay (no API route reaches them).
 */

import type { BulletSpec, PerspectiveSpec, SourceSpec } from '../../corpus/types'

export const sources: SourceSpec[] = [
  // ── Education ──
  {
    key: 'phd-robotics',
    title: 'Ph.D. in Robotics',
    description:
      'Doctorate in robotics at Cascadia Institute of Technology. Dissertation: learning manipulation policies from sparse demonstrations, published as four peer-reviewed papers. Released an open grasping dataset and co-taught the graduate robot learning course.',
    source_type: 'education',
    status: 'approved',
    start: { monthsAgo: 118 },
    end: { monthsAgo: 72, day: 15 },
    education: {
      education_type: 'degree',
      orgKey: 'cascadia',
      campusKey: 'cascadia/main',
      field: 'Robotics',
      degree_level: 'doctoral',
      degree_type: 'PhD',
      edu_description: 'Dissertation: Learning Manipulation Policies from Sparse Demonstrations. Advisor: Dr. Lucia Ferreira-Hale.',
    },
    skills: ['reinforcement-learning', 'computer-vision', 'pytorch', 'ros2', 'python', 'numpy'],
    daysAgo: 528,
  },
  {
    key: 'bs-mech',
    title: 'B.S. in Mechanical Engineering',
    description:
      'Bachelor of Science in Mechanical Engineering with a robotics minor from Lakehaven Polytechnic University. Controls, dynamics and embedded systems coursework; led the senior design team that built an autonomous greenhouse inspection rover.',
    source_type: 'education',
    status: 'approved',
    start: { monthsAgo: 166 },
    end: { monthsAgo: 120, day: 20 },
    education: {
      education_type: 'degree',
      orgKey: 'lakehaven',
      campusKey: 'lakehaven/main',
      field: 'Mechanical Engineering (Robotics minor)',
      degree_level: 'bachelors',
      degree_type: 'BS',
      gpa: '3.81',
    },
    skills: ['cpp', 'ros2', 'technical-leadership'],
    daysAgo: 527,
  },
  // ── Roles ──
  {
    key: 'ironwood-role',
    title: 'Robotics Software Engineer, Ironwood Robotics',
    description:
      'Built perception and grasp-planning software for warehouse picking robots: a C++ and ROS 2 grasp planner, GPU point-cloud filtering, a simulation regression suite and field calibration tools used at customer sites.',
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 72 },
    end: { monthsAgo: 50, day: 28 },
    role: { orgKey: 'ironwood', work_arrangement: 'on-site' },
    skills: ['cpp', 'ros2', 'cuda', 'opencv', 'computer-vision', 'python', 'docker', 'linux'],
    daysAgo: 525,
  },
  {
    key: 'meridian-role',
    title: 'Senior Applied ML Scientist, Meridian Applied AI',
    description:
      "Applied ML scientist on Meridian's client solutions group. Rebuilt a demand-forecasting model, moved training onto a scheduled Ray-on-Kubernetes pipeline, and shipped the company's first retrieval-augmented support assistant with its evaluation set.",
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 50 },
    end: { monthsAgo: 22, day: 14 },
    role: { orgKey: 'meridian', work_arrangement: 'hybrid' },
    skills: ['pytorch', 'python', 'ray', 'kubernetes', 'mlflow', 'rag', 'llms', 'kafka', 'postgresql', 'mentoring'],
    daysAgo: 524,
  },
  {
    key: 'lanternfish-role',
    title: 'Staff Engineer, Agent Platform, Lanternfish Systems',
    description:
      "Staff engineer and technical lead for Lanternfish's agent platform: the tool router, sandboxed executors, policy layer and the customer-facing tool registry. Leads an eleven-person team and the platform's design reviews.",
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 22 },
    role: { orgKey: 'lanternfish', is_current: true, work_arrangement: 'hybrid', total_comp_notes: 'Base plus equity; annual refresh grant.' },
    skills: ['agent-orchestration', 'rust', 'python', 'kubernetes', 'mcp', 'prompt-injection', 'redis', 'technical-leadership'],
    daysAgo: 522,
  },
  // ── Projects ──
  {
    key: 'oss-harness',
    title: 'Bramble: open-source agent evaluation harness',
    description:
      "Bramble records an agent's tool calls and replays them deterministically, so evaluation suites can run in CI without live tools. Started at Lanternfish and released under the Apache-2.0 license; now maintained with outside contributors.",
    source_type: 'project',
    status: 'approved',
    start: { monthsAgo: 18 },
    project: { orgKey: 'lanternfish', open_source: true, url: 'https://code.example.com/lanternfish/bramble' },
    skills: ['python', 'model-evaluation', 'pydantic', 'docker', 'git'],
    daysAgo: 500,
  },
  {
    key: 'personal-sim',
    title: 'Pocket Arm: a laptop-scale robot arm simulator',
    description:
      'A personal open-source simulator for six-axis hobby robot arms, written in Rust with Python bindings, for running reinforcement-learning experiments on an ordinary laptop CPU.',
    source_type: 'project',
    status: 'in_review',
    start: { monthsAgo: 14 },
    project: { is_personal: true, open_source: true, url: 'https://code.example.com/talia-bo/pocket-arm' },
    skills: ['rust', 'python', 'reinforcement-learning', 'jax', 'pytorch'],
    daysAgo: 180,
  },
  // ── General ──
  {
    key: 'mentor-general',
    title: 'Volunteer mentor, Pacific Robot League',
    description:
      'Volunteer mentor for a high-school robotics team in the Pacific Robot League for three seasons: weekly build sessions, programming lessons and competition-day pit support.',
    source_type: 'general',
    status: 'archived',
    start: { monthsAgo: 96 },
    end: { monthsAgo: 60 },
    skills: ['mentoring', 'cpp', 'public-speaking'],
    daysAgo: 515,
  },
  // ── Presentations: one of every type ──
  {
    key: 'talk-poster',
    title: 'Poster: Sparse-demonstration policy learning for bin picking',
    description:
      'Poster at the Pacific Symposium on Robot Learning with early results on learning bin-picking policies from fewer than ten demonstrations; later expanded into a journal paper.',
    source_type: 'presentation',
    status: 'approved',
    start: { monthsAgo: 80, day: 24 },
    end: { monthsAgo: 80, day: 24 },
    presentation: {
      venue: 'Pacific Symposium on Robot Learning',
      presentation_type: 'poster',
      url: 'https://psrl.example.org/2020/posters/sparse-demos',
      coauthors: 'Ben Ashdown; Dr. Lucia Ferreira-Hale (advisor)',
    },
    skills: ['reinforcement-learning', 'computer-vision'],
    daysAgo: 520,
  },
  {
    key: 'talk-webinar',
    title: 'Webinar: From notebook to nightly retrain',
    description:
      'Hour-long webinar for the Applied ML Practitioners Guild on moving a forecasting model from a notebook to a scheduled, tracked production pipeline, with a live walkthrough and Q&A.',
    source_type: 'presentation',
    status: 'in_review',
    start: { monthsAgo: 30, day: 7 },
    end: { monthsAgo: 30, day: 7 },
    presentation: {
      venue: 'Applied ML Practitioners Guild webinar series',
      presentation_type: 'webinar',
      url: 'https://ampg.example.org/webinars/notebook-to-nightly',
    },
    skills: ['mlops', 'mlflow', 'public-speaking'],
    daysAgo: 510,
  },
  {
    key: 'talk-panel',
    title: 'Panel: Who is accountable when an agent acts?',
    description:
      'Panelist at Open Agents Summit 2025 on accountability, audit trails and human approval for autonomous agents, alongside a product counsel and a platform security lead.',
    source_type: 'presentation',
    status: 'rejected',
    start: { monthsAgo: 13, day: 20 },
    end: { monthsAgo: 13, day: 20 },
    presentation: {
      venue: 'Open Agents Summit 2025',
      presentation_type: 'panel',
      url: 'https://openagents.example.org/summit/2025/panels/accountability',
      coauthors: 'Moderated by Hollis Grant',
    },
    skills: ['public-speaking', 'prompt-injection'],
    daysAgo: 400,
  },
  {
    key: 'talk-workshop',
    title: 'Workshop: Building evaluation suites for LLM agents',
    description:
      'Three-hour hands-on workshop at the Northwest Robotics and AI Conference: participants recorded traces from their own agents and turned them into replayable evaluation suites with Bramble.',
    source_type: 'presentation',
    status: 'approved',
    start: { monthsAgo: 11, day: 9 },
    end: { monthsAgo: 11, day: 9 },
    presentation: {
      venue: 'Northwest Robotics and AI Conference',
      presentation_type: 'workshop',
      url: 'https://nw-robotics.example.org/conference/2025/workshops/agent-evals',
      coauthors: 'Sofia Kaminski',
    },
    skills: ['model-evaluation', 'python', 'public-speaking'],
    daysAgo: 350,
  },
  {
    key: 'talk-internal',
    title: 'Internal tech talk: Inside the tool router',
    description:
      "Engineering all-hands deep dive on the design of Lanternfish's tool router: request flow, sandbox scheduling, budgets and the failure modes we designed for.",
    source_type: 'presentation',
    status: 'approved',
    start: { monthsAgo: 8, day: 15 },
    end: { monthsAgo: 8, day: 15 },
    presentation: { venue: 'Lanternfish Engineering All-Hands', presentation_type: 'internal' },
    skills: ['distributed-systems', 'rust', 'technical-writing'],
    daysAgo: 250,
  },
  {
    key: 'talk-conference',
    title: 'Talk: Typed contracts for tool-calling agents',
    description:
      'Thirty-minute conference talk at Open Agents Summit 2026 arguing that agent tools need typed, versioned contracts, with case studies from a platform serving over a million runs a week.',
    source_type: 'presentation',
    status: 'approved',
    start: { monthsAgo: 5, day: 22 },
    end: { monthsAgo: 5, day: 22 },
    presentation: {
      venue: 'Open Agents Summit 2026',
      presentation_type: 'conference_talk',
      url: 'https://openagents.example.org/summit/2026/talks/typed-contracts',
    },
    skills: ['agent-orchestration', 'pydantic', 'mcp', 'public-speaking'],
    daysAgo: 155,
  },
  {
    key: 'talk-lightning',
    title: 'Lightning talk: Your agent needs a budget',
    description:
      'Five-minute lightning talk at the Seattle Applied ML Meetup on per-run token and tool budgets for agents, and the runaway-cost incidents that motivated them.',
    source_type: 'presentation',
    status: 'draft',
    start: { monthsAgo: 2, day: 16 },
    end: { monthsAgo: 2, day: 16 },
    presentation: {
      venue: 'Seattle Applied ML Meetup',
      presentation_type: 'lightning_talk',
      url: 'https://meetup.example.org/seattle-applied-ml/lightning-summer',
    },
    skills: ['agent-orchestration', 'public-speaking'],
    daysAgo: 72,
  },
]

export const bullets: BulletSpec[] = [
  // Ironwood Robotics
  {
    key: 'b-iw-grasp',
    sourceKey: 'ironwood-role',
    content: 'Shipped a grasp-planning service in C++ and ROS 2 that raised first-attempt pick success on mixed-SKU bins from 71% to 89%.',
    technologies: ['cpp', 'ros2', 'computer-vision'],
    metrics: 'First-attempt pick success 71% to 89%',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 524,
    reviewedDaysAgo: 522,
  },
  {
    key: 'b-iw-sim',
    sourceKey: 'ironwood-role',
    content: 'Built a simulation regression suite that replayed 2,000 recorded bin scenes on every merge, catching grasp regressions before field rollout.',
    technologies: ['python', 'docker', 'experiment-design'],
    metrics: '2,000 scenes replayed per merge',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 524,
    reviewedDaysAgo: 522,
  },
  {
    key: 'b-iw-latency',
    sourceKey: 'ironwood-role',
    content: 'Cut perception-to-motion latency from 140 ms to 38 ms by moving point-cloud filtering onto the GPU with CUDA.',
    technologies: ['cuda', 'cpp', 'low-latency', 'opencv'],
    metrics: 'Latency 140 ms to 38 ms',
    domain: 'systems_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 524,
    reviewedDaysAgo: 521,
  },
  {
    key: 'b-iw-oncall',
    sourceKey: 'ironwood-role',
    content: 'Was part of the on-call rotation for warehouse robots.',
    technologies: ['linux'],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Responsibility, not an outcome: what did the on-call work change?',
    daysAgo: 524,
    reviewedDaysAgo: 521,
  },
  {
    key: 'b-iw-calibration',
    sourceKey: 'ironwood-role',
    content: 'Wrote a camera-calibration tool that cut robot-cell setup from a full day to under two hours across 14 customer sites.',
    technologies: ['python', 'opencv', 'computer-vision'],
    metrics: 'Setup from 1 day to under 2 hours; 14 sites',
    domain: 'software_engineering',
    via: 'derive',
    status: 'archived',
    daysAgo: 524,
    reviewedDaysAgo: 521,
  },
  // Meridian Applied AI
  {
    key: 'b-mer-forecast',
    sourceKey: 'meridian-role',
    content: 'Led a demand-forecasting model rebuild in PyTorch that cut weighted forecast error 18% for 40 regional distribution centers.',
    technologies: ['pytorch', 'python', 'model-evaluation'],
    metrics: 'Weighted error down 18%; 40 distribution centers',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 523,
    reviewedDaysAgo: 520,
  },
  {
    key: 'b-mer-pipeline',
    sourceKey: 'meridian-role',
    content: 'Moved model training from notebooks to a Ray-on-Kubernetes pipeline with MLflow tracking, taking retrains from weekly manual runs to nightly automated ones.',
    technologies: ['ray', 'kubernetes', 'mlflow', 'mlops'],
    metrics: 'Weekly manual retrains to nightly automated',
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 523,
    reviewedDaysAgo: 520,
  },
  {
    key: 'b-mer-rag',
    sourceKey: 'meridian-role',
    content: "Built the company's first retrieval-augmented support assistant, which answered 42% of tier-one tickets without escalation in its first quarter.",
    technologies: ['rag', 'llms', 'python', 'postgresql'],
    metrics: '42% of tier-one tickets resolved without escalation',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 523,
    reviewedDaysAgo: 520,
  },
  {
    key: 'b-mer-eval',
    sourceKey: 'meridian-role',
    content: 'Designed an offline evaluation set of 1,200 labeled support conversations that became the release gate for every assistant change.',
    technologies: ['model-evaluation', 'experiment-design'],
    metrics: '1,200 labeled conversations',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 523,
    reviewedDaysAgo: 519,
  },
  {
    key: 'b-mer-mentoring',
    sourceKey: 'meridian-role',
    content: 'Mentored three junior scientists through their first production launches; two were promoted within 18 months.',
    technologies: ['mentoring', 'technical-leadership'],
    metrics: '3 mentees; 2 promotions',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 523,
    reviewedDaysAgo: 519,
  },
  {
    key: 'b-mer-feature-store',
    sourceKey: 'meridian-role',
    content: 'Worked on the feature store.',
    technologies: ['sql'],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Too vague: what did you build, and for whom?',
    daysAgo: 523,
    reviewedDaysAgo: 519,
  },
  {
    key: 'b-mer-kafka',
    sourceKey: 'meridian-role',
    content: 'Streamed point-of-sale events through Kafka into hourly feature tables so forecasts reacted to promotions within the same day.',
    technologies: ['kafka', 'python', 'sql'],
    metrics: null,
    domain: 'systems_engineering',
    via: 'derive',
    status: 'in_review',
    reopenedAfter: 'Add the business outcome: what did same-day reaction to promotions save?',
    daysAgo: 523,
  },
  {
    key: 'b-mer-spot',
    sourceKey: 'meridian-role',
    content: 'Proposed spot-instance scheduling for nightly retrains to cut training spend.',
    technologies: ['ray', 'kubernetes'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 210,
  },
  // Lanternfish Systems
  {
    key: 'b-lf-platform',
    sourceKey: 'lanternfish-role',
    content: "Architected Lanternfish's agent platform (a tool router, sandboxed executors and a policy layer) serving 1.2 million agent runs a week.",
    technologies: ['agent-orchestration', 'python', 'rust', 'kubernetes'],
    metrics: '1.2 million agent runs per week',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 521,
    reviewedDaysAgo: 518,
  },
  {
    key: 'b-lf-latency',
    sourceKey: 'lanternfish-role',
    content: 'Rewrote the tool-dispatch hot path in Rust, cutting p99 dispatch latency from 210 ms to 24 ms.',
    technologies: ['rust', 'low-latency', 'distributed-systems'],
    metrics: 'p99 latency 210 ms to 24 ms',
    domain: 'systems_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 521,
    reviewedDaysAgo: 518,
  },
  {
    key: 'b-lf-mcp',
    sourceKey: 'lanternfish-role',
    content: 'Added Model Context Protocol support so customers could register their own tools, growing third-party tool integrations from 0 to 310 in two quarters.',
    technologies: ['mcp', 'fastapi', 'pydantic'],
    metrics: '0 to 310 integrations in two quarters',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 521,
    reviewedDaysAgo: 518,
  },
  {
    key: 'b-lf-injection',
    sourceKey: 'lanternfish-role',
    content: 'Built a prompt-injection defense layer that scores tool outputs before they re-enter the context window, blocking 96% of red-team attacks in the regression suite.',
    technologies: ['prompt-injection', 'llms', 'model-evaluation'],
    metrics: '96% of red-team attacks blocked',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 521,
    reviewedDaysAgo: 517,
  },
  {
    key: 'b-lf-budget',
    sourceKey: 'lanternfish-role',
    content: 'Introduced per-run token and tool budgets that cut runaway agent spend by 63% without lowering task success.',
    technologies: ['agent-orchestration', 'redis'],
    metrics: 'Runaway spend down 63%',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 521,
    reviewedDaysAgo: 517,
  },
  {
    key: 'b-lf-team',
    sourceKey: 'lanternfish-role',
    content: 'Grew the agent platform team from 3 to 11 engineers and set up its design review process.',
    technologies: ['technical-leadership', 'mentoring'],
    metrics: 'Team from 3 to 11 engineers',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 521,
    reviewedDaysAgo: 517,
  },
  {
    key: 'b-lf-customers',
    sourceKey: 'lanternfish-role',
    content: 'Ran architecture reviews with 20 enterprise customers to map their workflows onto agent templates.',
    technologies: ['technical-writing', 'distributed-systems'],
    metrics: '20 enterprise customers',
    domain: 'leadership',
    via: 'derive',
    status: 'in_review',
    daysAgo: 521,
  },
  {
    key: 'b-lf-uptime',
    sourceKey: 'lanternfish-role',
    content: "Responsible for the platform's uptime.",
    technologies: ['kubernetes'],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Responsibility without an outcome; give the availability number.',
    daysAgo: 521,
    reviewedDaysAgo: 516,
  },
  {
    key: 'b-lf-websockets',
    sourceKey: 'lanternfish-role',
    content: 'Prototyping a WebSockets channel so long-running agent runs can stream progress to clients.',
    technologies: ['websockets', 'rust'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 35,
  },
  // Bramble (open source)
  {
    key: 'b-bramble-release',
    sourceKey: 'oss-harness',
    content: 'Created and open-sourced Bramble, an agent evaluation harness that replays recorded tool traces deterministically; it has 2,400 stars and 60 outside contributors.',
    technologies: ['python', 'model-evaluation', 'pydantic'],
    metrics: '2,400 stars; 60 outside contributors',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 499,
    reviewedDaysAgo: 497,
  },
  {
    key: 'b-bramble-ci',
    sourceKey: 'oss-harness',
    content: "Made Bramble's trace replay the release gate for Lanternfish's own agents, running 9,000 scenarios on every pull request.",
    technologies: ['model-evaluation', 'docker', 'git'],
    metrics: '9,000 scenarios per pull request',
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 499,
    reviewedDaysAgo: 497,
  },
  {
    key: 'b-bramble-docs',
    sourceKey: 'oss-harness',
    content: "Wrote Bramble's contributor guide and triage rota, keeping the median first response on new issues under two days.",
    technologies: ['technical-writing', 'git'],
    metrics: 'Median first response under 2 days',
    via: 'derive',
    status: 'in_review',
    daysAgo: 499,
  },
  // Pocket Arm (personal, open source)
  {
    key: 'b-pocket-sim',
    sourceKey: 'personal-sim',
    content: 'Built Pocket Arm, a robot arm simulator in Rust with Python bindings that runs reinforcement-learning experiments on a laptop CPU.',
    technologies: ['rust', 'python', 'reinforcement-learning'],
    metrics: null,
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 179,
    reviewedDaysAgo: 176,
  },
  {
    key: 'b-pocket-jax',
    sourceKey: 'personal-sim',
    content: 'Ported the policy-training loop to JAX, training a reach-and-grasp policy 5x faster than the PyTorch baseline on the same hardware.',
    technologies: ['jax', 'pytorch', 'reinforcement-learning'],
    metrics: '5x faster training',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 179,
    reviewedDaysAgo: 176,
  },
  {
    key: 'b-pocket-tutorials',
    sourceKey: 'personal-sim',
    content: 'Writing a tutorial series on sim-to-real gaps for hobbyist robot arms.',
    technologies: ['technical-writing', 'reinforcement-learning'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 28,
  },
  // Ph.D.
  {
    key: 'b-phd-thesis',
    sourceKey: 'phd-robotics',
    content: 'Wrote a dissertation on learning manipulation policies from fewer than ten demonstrations, published as four peer-reviewed papers.',
    technologies: ['reinforcement-learning', 'computer-vision', 'pytorch'],
    metrics: '4 peer-reviewed papers',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 527,
    reviewedDaysAgo: 526,
  },
  {
    key: 'b-phd-dataset',
    sourceKey: 'phd-robotics',
    content: 'Released an open dataset of 30,000 annotated grasp attempts that research groups at other universities adopted.',
    technologies: ['computer-vision', 'python', 'numpy'],
    metrics: '30,000 annotated grasp attempts',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 527,
    reviewedDaysAgo: 526,
  },
  {
    key: 'b-phd-teaching',
    sourceKey: 'phd-robotics',
    content: 'Co-taught the graduate robot learning course for two terms and redesigned its labs around a shared simulation stack.',
    technologies: ['mentoring', 'public-speaking', 'ros2'],
    metrics: 'Two terms',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 527,
    reviewedDaysAgo: 526,
  },
  {
    key: 'b-phd-award',
    sourceKey: 'phd-robotics',
    content: "Received the robotics department's outstanding dissertation award.",
    technologies: [],
    metrics: 'Department dissertation award',
    via: 'derive',
    status: 'approved',
    daysAgo: 527,
    reviewedDaysAgo: 526,
  },
  // B.S.
  {
    key: 'b-bs-capstone',
    sourceKey: 'bs-mech',
    content: 'Led a five-person senior design team that built an autonomous greenhouse inspection rover and won first place at the engineering showcase.',
    technologies: ['ros2', 'cpp', 'technical-leadership'],
    metrics: '1st place; 5-person team',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 526,
    reviewedDaysAgo: 525,
  },
  {
    key: 'b-bs-honors',
    sourceKey: 'bs-mech',
    content: 'Graduated summa cum laude with a 3.81 GPA.',
    technologies: [],
    metrics: '3.81 GPA',
    via: 'derive',
    status: 'approved',
    daysAgo: 526,
    reviewedDaysAgo: 525,
  },
  // Volunteer mentoring (the source is archived later)
  {
    key: 'b-mentor',
    sourceKey: 'mentor-general',
    content: 'Mentored a high-school robotics team for three seasons; two students went on to study engineering.',
    technologies: ['mentoring', 'cpp'],
    metrics: '3 seasons',
    domain: 'leadership',
    via: 'derive',
    status: 'archived',
    daysAgo: 514,
    reviewedDaysAgo: 513,
  },
  // Presentations
  {
    key: 'b-talk-contracts',
    sourceKey: 'talk-conference',
    content: 'Presented typed tool contracts for agents to about 400 Open Agents Summit attendees; the recording has passed 9,000 views.',
    technologies: ['agent-orchestration', 'pydantic', 'public-speaking'],
    metrics: '~400 attendees; 9,000+ recording views',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 154,
    reviewedDaysAgo: 152,
  },
  {
    key: 'b-workshop-evals',
    sourceKey: 'talk-workshop',
    content: 'Ran a three-hour hands-on workshop in which 45 engineers built evaluation suites for their own agents.',
    technologies: ['model-evaluation', 'public-speaking'],
    metrics: '45 participants',
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 349,
    reviewedDaysAgo: 347,
  },
  {
    key: 'b-poster-sparse',
    sourceKey: 'talk-poster',
    content: 'Presented a poster on sparse-demonstration policy learning for bin picking, later expanded into a journal paper.',
    technologies: ['reinforcement-learning', 'computer-vision'],
    metrics: null,
    domain: 'ai_ml',
    via: 'derive',
    status: 'approved',
    daysAgo: 519,
    reviewedDaysAgo: 518,
  },
  {
    key: 'b-webinar-mlops',
    sourceKey: 'talk-webinar',
    content: 'Hosted a webinar for 600 registrants on moving forecasting models from notebooks to scheduled production pipelines.',
    technologies: ['mlops', 'mlflow', 'public-speaking'],
    metrics: '600 registrants',
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 509,
    reviewedDaysAgo: 507,
  },
  {
    key: 'b-internal-router',
    sourceKey: 'talk-internal',
    content: "Gave an internal deep dive on the tool router's design to 120 engineers; it became required onboarding for the platform team.",
    technologies: ['distributed-systems', 'rust', 'technical-writing'],
    metrics: '120 engineers',
    domain: 'software_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 249,
    reviewedDaysAgo: 247,
  },
  {
    key: 'b-panel',
    sourceKey: 'talk-panel',
    content: 'Sat on a panel about agent accountability.',
    technologies: ['public-speaking'],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Being on a panel is not an accomplishment; say what you argued or what changed.',
    daysAgo: 399,
    reviewedDaysAgo: 398,
  },
  {
    key: 'b-lightning-budgets',
    sourceKey: 'talk-lightning',
    content: 'Gave a five-minute lightning talk arguing that every agent run needs explicit token and tool budgets.',
    technologies: ['agent-orchestration', 'public-speaking'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 70,
  },
]

export const perspectives: PerspectiveSpec[] = [
  // b-iw-grasp
  {
    key: 'p-iw-grasp-ai',
    bulletKey: 'b-iw-grasp',
    content: 'Raised first-attempt pick success on mixed-SKU bins from 71% to 89% with a grasp planner that ranked learned candidate grasps in real time.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 410,
  },
  {
    key: 'p-iw-grasp-sa',
    bulletKey: 'b-iw-grasp',
    content: 'Worked from warehouse customers\' pick-failure reports to a grasp-planning service that lifted first-attempt success to 89%.',
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 64,
  },
  // b-iw-sim
  {
    key: 'p-iw-sim-hft',
    bulletKey: 'b-iw-sim',
    content: 'Replayed 2,000 recorded scenes against every merge in a deterministic simulation suite, catching regressions before any robot ran the code.',
    archetype: 'hft', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 380,
  },
  {
    key: 'p-iw-sim-infra',
    bulletKey: 'b-iw-sim',
    content: 'Owned the simulation regression suite that gated every merge to the robot software stack.',
    archetype: 'infrastructure', domain: 'devops', framing: 'responsibility', via: 'draft', status: 'draft', daysAgo: 90,
  },
  // b-iw-latency
  {
    key: 'p-iw-latency-hft',
    bulletKey: 'b-iw-latency',
    content: 'Cut perception-to-motion latency from 140 ms to 38 ms by moving point-cloud filtering into CUDA kernels.',
    archetype: 'hft', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 380,
  },
  {
    key: 'p-iw-latency-ai',
    bulletKey: 'b-iw-latency',
    content: "Made a robot's perception loop fast enough for closed-loop grasp correction by cutting its latency from 140 ms to 38 ms.",
    archetype: 'agentic-ai', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 409,
  },
  // b-iw-calibration (the bullet is archived later)
  {
    key: 'p-iw-calibration-sa',
    bulletKey: 'b-iw-calibration',
    content: 'Cut robot-cell setup at 14 customer sites from a full day to under two hours with a camera-calibration tool.',
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'archived', daysAgo: 500,
  },
  // b-mer-forecast
  {
    key: 'p-mer-forecast-hft',
    bulletKey: 'b-mer-forecast',
    content: 'Rebuilt a demand-forecasting model in PyTorch that cut weighted error 18% across 40 distribution centers, backtesting every candidate before release.',
    archetype: 'hft', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 378,
  },
  {
    key: 'p-mer-forecast-sa',
    bulletKey: 'b-mer-forecast',
    content: 'Partnered with supply-chain planners to rebuild the forecasting model they relied on, cutting its weighted error 18%.',
    archetype: 'solutions-architect', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'approved', daysAgo: 300,
  },
  {
    key: 'p-mer-forecast-sec',
    bulletKey: 'b-mer-forecast',
    content: 'Protected forecast integrity for 40 distribution centers by rebuilding the model behind them.',
    archetype: 'security-engineer', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'rejected',
    rejection_reason: 'No security angle in a forecasting rebuild; pick another archetype.', daysAgo: 298,
  },
  // b-mer-pipeline
  {
    key: 'p-mer-pipeline-infra',
    bulletKey: 'b-mer-pipeline',
    content: 'Moved model training from notebooks onto a Ray-on-Kubernetes pipeline with MLflow tracking, turning weekly manual retrains into nightly automated ones.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 60,
  },
  {
    key: 'p-mer-pipeline-ai',
    bulletKey: 'b-mer-pipeline',
    content: 'Built the training pipeline that let a small science team retrain and ship models nightly instead of weekly.',
    archetype: 'agentic-ai', domain: 'devops', framing: 'context', via: 'derive', status: 'approved', daysAgo: 405,
  },
  // b-mer-rag
  {
    key: 'p-mer-rag-ai',
    bulletKey: 'b-mer-rag',
    content: 'Shipped a retrieval-augmented support assistant that resolved 42% of tier-one tickets without escalation in its first quarter.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 404,
  },
  {
    key: 'p-mer-rag-sa',
    bulletKey: 'b-mer-rag',
    content: "Designed a retrieval-augmented assistant around the support team's existing knowledge base, resolving 42% of tier-one tickets on its own.",
    archetype: 'solutions-architect', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 299,
  },
  {
    key: 'p-mer-rag-hft',
    bulletKey: 'b-mer-rag',
    content: 'Applied retrieval and ranking techniques to a high-volume stream of support tickets.',
    archetype: 'hft', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'rejected',
    rejection_reason: 'Stretches a support assistant into a trading story; drop it.', daysAgo: 377,
  },
  // b-mer-eval
  {
    key: 'p-mer-eval-ai',
    bulletKey: 'b-mer-eval',
    content: 'Built a 1,200-conversation offline evaluation set that became the release gate for every change to the support assistant.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 404,
  },
  {
    key: 'p-mer-eval-sa',
    bulletKey: 'b-mer-eval',
    content: 'Owned the evaluation set and release criteria for a customer-facing assistant.',
    archetype: 'solutions-architect', domain: 'ai_ml', framing: 'responsibility', via: 'derive', status: 'in_review', daysAgo: 66,
  },
  // b-mer-mentoring
  {
    key: 'p-mer-mentoring-lead',
    bulletKey: 'b-mer-mentoring',
    content: 'Mentored three junior applied scientists through their first production launches; two were promoted within 18 months.',
    archetype: 'agentic-ai', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 403,
  },
  // b-lf-platform
  {
    key: 'p-lf-platform-ai',
    bulletKey: 'b-lf-platform',
    content: 'Architected an agent platform (tool router, sandboxed executors and a policy layer) that serves 1.2 million agent runs a week.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 402,
  },
  {
    key: 'p-lf-platform-sa',
    bulletKey: 'b-lf-platform',
    content: 'Designed the reference architecture customers use to run agents in production (routing, sandboxing and policy) at 1.2 million runs a week.',
    archetype: 'solutions-architect', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 298,
  },
  {
    key: 'p-lf-platform-infra',
    bulletKey: 'b-lf-platform',
    content: 'Own the Kubernetes-based execution layer behind 1.2 million sandboxed agent runs a week.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 59,
  },
  {
    key: 'p-lf-platform-old',
    bulletKey: 'b-lf-platform',
    content: 'Built the first version of an internal agent platform.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'archived', daysAgo: 510,
  },
  // b-lf-latency
  {
    key: 'p-lf-latency-hft',
    bulletKey: 'b-lf-latency',
    content: 'Rewrote a dispatch hot path in Rust, cutting p99 latency from 210 ms to 24 ms under production load.',
    archetype: 'hft', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 376,
  },
  {
    key: 'p-lf-latency-ai',
    bulletKey: 'b-lf-latency',
    content: "Cut p99 tool-dispatch latency from 210 ms to 24 ms by rewriting the agent platform's hot path in Rust.",
    archetype: 'agentic-ai', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 402,
  },
  {
    key: 'p-lf-latency-infra',
    bulletKey: 'b-lf-latency',
    content: "Profiled and rewrote the slowest service on the agent platform's request path.",
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'context', via: 'draft', status: 'draft', daysAgo: 20,
  },
  // b-lf-mcp
  {
    key: 'p-lf-mcp-ai',
    bulletKey: 'b-lf-mcp',
    content: 'Added Model Context Protocol support so customers could bring their own tools, growing third-party integrations from zero to 310 in two quarters.',
    archetype: 'agentic-ai', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 401,
  },
  {
    key: 'p-lf-mcp-sa',
    bulletKey: 'b-lf-mcp',
    content: 'Opened the platform to customer-built tools through a standard protocol, reaching 310 third-party integrations in two quarters.',
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 297,
  },
  // b-lf-injection
  {
    key: 'p-lf-injection-ai',
    bulletKey: 'b-lf-injection',
    content: "Built a defense layer that scores tool outputs before they re-enter an agent's context, blocking 96% of red-team prompt-injection attacks.",
    archetype: 'agentic-ai', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 401,
  },
  {
    key: 'p-lf-injection-sec',
    bulletKey: 'b-lf-injection',
    content: 'Hardened an agent platform against prompt injection with an output-scoring layer that blocks 96% of red-team attacks in regression.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 48,
  },
  // b-lf-budget
  {
    key: 'p-lf-budget-ai',
    bulletKey: 'b-lf-budget',
    content: 'Cut runaway agent spend 63% with per-run token and tool budgets, with no drop in task success.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 400,
  },
  {
    key: 'p-lf-budget-hft',
    bulletKey: 'b-lf-budget',
    content: 'Put hard per-run limits on token and tool spend, treating agent cost the way a desk treats a risk budget.',
    archetype: 'hft', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 33,
  },
  // b-lf-team
  {
    key: 'p-lf-team-lead',
    bulletKey: 'b-lf-team',
    content: 'Grew the agent platform team from 3 to 11 engineers and set up the design review process it still uses.',
    archetype: 'agentic-ai', domain: 'leadership', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 400,
  },
  {
    key: 'p-lf-team-sa',
    bulletKey: 'b-lf-team',
    content: 'Lead an eleven-person platform team and run its design reviews.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'responsibility', via: 'draft', status: 'draft', daysAgo: 77,
  },
  // b-bramble-release
  {
    key: 'p-bramble-release-ai',
    bulletKey: 'b-bramble-release',
    content: 'Created and open-sourced Bramble, an agent evaluation harness that replays tool traces deterministically; 2,400 stars and 60 outside contributors.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 399,
  },
  {
    key: 'p-bramble-release-sa',
    bulletKey: 'b-bramble-release',
    content: 'Released an open-source evaluation harness that customers now use to test their own agents before rollout.',
    archetype: 'solutions-architect', domain: 'software_engineering', framing: 'context', via: 'derive', status: 'approved', daysAgo: 296,
  },
  // b-bramble-ci
  {
    key: 'p-bramble-ci-infra',
    bulletKey: 'b-bramble-ci',
    content: 'Wired a 9,000-scenario agent regression suite into CI so every pull request is gated on replayed tool traces.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 58,
  },
  {
    key: 'p-bramble-ci-ai',
    bulletKey: 'b-bramble-ci',
    content: 'Made deterministic trace replay the release gate for our own agents, running 9,000 scenarios on every pull request.',
    archetype: 'agentic-ai', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 399,
  },
  // b-pocket-sim / b-pocket-jax
  {
    key: 'p-pocket-sim-ai',
    bulletKey: 'b-pocket-sim',
    content: 'Built Pocket Arm, an open-source robot arm simulator in Rust and Python that runs reinforcement-learning experiments on a laptop CPU.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 170,
  },
  {
    key: 'p-pocket-jax-hft',
    bulletKey: 'b-pocket-jax',
    content: 'Ported a policy-training loop to JAX and trained 5x faster than the PyTorch baseline on identical hardware.',
    archetype: 'hft', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 169,
  },
  // b-phd-*
  {
    key: 'p-phd-thesis-ai',
    bulletKey: 'b-phd-thesis',
    content: 'Showed in a four-paper dissertation that manipulation policies can be learned from fewer than ten demonstrations.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 398,
  },
  {
    key: 'p-phd-thesis-hft',
    bulletKey: 'b-phd-thesis',
    content: 'Researched sample-efficient learning, a skill that transfers to noisy financial signals.',
    archetype: 'hft', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'rejected',
    rejection_reason: 'Too speculative; let the publications speak for themselves.', daysAgo: 375,
  },
  {
    key: 'p-phd-dataset-ai',
    bulletKey: 'b-phd-dataset',
    content: 'Released an open dataset of 30,000 annotated grasp attempts, adopted by research groups at other universities.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 398,
  },
  {
    key: 'p-phd-teaching-lead',
    bulletKey: 'b-phd-teaching',
    content: 'Co-taught a graduate robot learning course for two terms and rebuilt its labs around a shared simulation stack.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 295,
  },
  {
    key: 'p-phd-award-ai',
    bulletKey: 'b-phd-award',
    content: 'Outstanding Dissertation Award, Department of Robotics, Cascadia Institute of Technology.',
    archetype: 'agentic-ai', domain: 'leadership', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 397,
  },
  // b-bs-capstone
  {
    key: 'p-bs-capstone-award',
    bulletKey: 'b-bs-capstone',
    content: 'First place, senior engineering showcase, for an autonomous greenhouse inspection rover built by a five-person team I led.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 294,
  },
  // b-mentor (the bullet is archived later)
  {
    key: 'p-mentor-lead',
    bulletKey: 'b-mentor',
    content: 'Coached a high-school robotics team for three seasons.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'archived', daysAgo: 505,
  },
  // Presentations
  {
    key: 'p-talk-contracts-ai',
    bulletKey: 'b-talk-contracts',
    content: 'Presented typed tool contracts for agents to about 400 Open Agents Summit attendees; the recording has passed 9,000 views.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 150,
  },
  {
    key: 'p-workshop-evals-sa',
    bulletKey: 'b-workshop-evals',
    content: 'Taught 45 engineers to build evaluation suites for their own agents in a three-hour hands-on workshop.',
    archetype: 'solutions-architect', domain: 'ai_ml', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 293,
  },
  {
    key: 'p-poster-sparse-ai',
    bulletKey: 'b-poster-sparse',
    content: 'Presented early results on sparse-demonstration bin picking, later expanded into a journal paper.',
    archetype: 'agentic-ai', domain: 'ai_ml', framing: 'context', via: 'derive', status: 'approved', daysAgo: 397,
  },
  {
    key: 'p-webinar-mlops-infra',
    bulletKey: 'b-webinar-mlops',
    content: 'Walked 600 webinar registrants through moving a forecasting model from a notebook to a scheduled production pipeline.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 57,
  },
  {
    key: 'p-internal-router-ai',
    bulletKey: 'b-internal-router',
    content: 'Gave a design deep dive on the tool router to 120 engineers; it is now required onboarding for the platform team.',
    archetype: 'agentic-ai', domain: 'software_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 240,
  },
]
