/**
 * ai-ml-engineer: profile, answer bank, industries, role types, skill catalog,
 * organizations, credentials and certifications. Every name, address line, email, phone
 * number and URL is fictional; cities and states are real.
 */

import type {
  AnswerSpec,
  CertificationSpec,
  CredentialSpec,
  NamedSpec,
  OrgSpec,
  ProfileSpec,
  SkillSpec,
} from '../../corpus/types'

export const profile: ProfileSpec = {
  name: 'Talia Brennan-Osei',
  email: 'talia.brennan-osei@example.com',
  phone: '(206) 555-0173',
  address: { name: 'Seattle, WA', street_1: '1400 Example Street', street_2: 'Unit 5', city: 'Seattle', state: 'WA', zip: '98122' },
  urls: [
    { key: 'linkedin', url: 'https://social.example.com/in/talia-brennan-osei' },
    { key: 'github', url: 'https://code.example.com/talia-bo' },
    { key: 'blog', url: 'https://notes.talia-bo.example.net' },
    { key: 'portfolio', url: 'https://talia-bo.example.net' },
  ],
  salary_minimum: 215000,
  salary_target: 250000,
  salary_stretch: 295000,
}

export const answers: AnswerSpec[] = [
  { field_kind: 'work_auth.us', value: 'Yes' },
  { field_kind: 'work_auth.sponsorship', value: 'No' },
  { field_kind: 'eeo.gender', value: 'Prefer not to say' },
  { field_kind: 'eeo.race', value: 'Decline to self-identify' },
  { field_kind: 'eeo.veteran', value: 'Prefer not to say' },
  { field_kind: 'eeo.disability', value: 'Prefer not to say' },
]

export const industries: NamedSpec[] = [
  { key: 'ai', name: 'Artificial Intelligence', description: 'Model, agent and applied AI companies' },
  { key: 'robotics', name: 'Robotics' },
  { key: 'cloud', name: 'Cloud Computing' },
  { key: 'quant-finance', name: 'Quantitative Finance', description: 'Trading firms and market makers' },
  { key: 'healthcare', name: 'Healthcare' },
  { key: 'logistics', name: 'Logistics' },
  { key: 'devtools', name: 'Developer Tools' },
]

export const roleTypes: NamedSpec[] = [
  { key: 'ai-platform', name: 'AI Platform Engineer', description: 'Agent runtimes, tool routing and model serving' },
  { key: 'ml-engineer', name: 'Machine Learning Engineer' },
  { key: 'solutions-architect', name: 'Solutions Architect' },
  { key: 'research-scientist', name: 'Research Scientist' },
  { key: 'quant-developer', name: 'Quantitative Developer' },
  { key: 'eng-manager', name: 'Engineering Manager' },
]

export const skills: SkillSpec[] = [
  { key: 'python', name: 'Python', category: 'language', domains: ['software_engineering', 'ai_ml'] },
  { key: 'cpp', name: 'C++', category: 'language', domains: ['systems_engineering'] },
  { key: 'rust', name: 'Rust', category: 'language', domains: ['systems_engineering', 'software_engineering'] },
  { key: 'sql', name: 'SQL', category: 'language' },
  { key: 'reinforcement-learning', name: 'Reinforcement Learning', category: 'ai_ml', domains: ['ai_ml'] },
  { key: 'llms', name: 'Large Language Models', category: 'ai_ml', domains: ['ai_ml'] },
  { key: 'rag', name: 'Retrieval-Augmented Generation', category: 'ai_ml', domains: ['ai_ml'] },
  { key: 'model-evaluation', name: 'Model Evaluation', category: 'ai_ml', domains: ['ai_ml'] },
  { key: 'computer-vision', name: 'Computer Vision', category: 'ai_ml', domains: ['ai_ml'] },
  { key: 'agent-orchestration', name: 'Agent Orchestration', category: 'ai_ml', domains: ['ai_ml', 'software_engineering'] },
  { key: 'pytorch', name: 'PyTorch', category: 'framework', domains: ['ai_ml'] },
  { key: 'jax', name: 'JAX', category: 'framework', domains: ['ai_ml'] },
  { key: 'ros2', name: 'ROS 2', category: 'framework', domains: ['systems_engineering'] },
  { key: 'fastapi', name: 'FastAPI', category: 'framework' },
  { key: 'numpy', name: 'NumPy', category: 'library' },
  { key: 'opencv', name: 'OpenCV', category: 'library', domains: ['ai_ml'] },
  { key: 'pydantic', name: 'Pydantic', category: 'library' },
  { key: 'postgresql', name: 'PostgreSQL', category: 'data_systems' },
  { key: 'redis', name: 'Redis', category: 'data_systems' },
  { key: 'kafka', name: 'Kafka', category: 'data_systems', domains: ['systems_engineering'] },
  { key: 'kubernetes', name: 'Kubernetes', category: 'infrastructure', domains: ['devops'] },
  { key: 'docker', name: 'Docker', category: 'infrastructure', domains: ['devops'] },
  { key: 'ray', name: 'Ray', category: 'infrastructure', domains: ['ai_ml', 'devops'] },
  { key: 'linux', name: 'Linux', category: 'platform' },
  { key: 'cuda', name: 'CUDA', category: 'platform', domains: ['systems_engineering'] },
  { key: 'git', name: 'Git', category: 'tool' },
  { key: 'mlflow', name: 'MLflow', category: 'tool', domains: ['devops'] },
  { key: 'experiment-design', name: 'Experiment Design', category: 'methodology', domains: ['ai_ml'] },
  { key: 'mlops', name: 'MLOps', category: 'methodology', domains: ['devops', 'ai_ml'] },
  { key: 'distributed-systems', name: 'Distributed Systems', category: 'concept', domains: ['systems_engineering'] },
  { key: 'low-latency', name: 'Low-Latency Systems', category: 'concept', domains: ['systems_engineering'] },
  { key: 'websockets', name: 'WebSockets', category: 'protocol' },
  { key: 'mcp', name: 'Model Context Protocol', category: 'protocol', domains: ['ai_ml'] },
  { key: 'prompt-injection', name: 'Prompt Injection Defense', category: 'security', domains: ['security', 'ai_ml'] },
  { key: 'technical-leadership', name: 'Technical Leadership', category: 'soft_skill', domains: ['leadership'] },
  { key: 'mentoring', name: 'Mentoring', category: 'soft_skill', domains: ['leadership'] },
  { key: 'public-speaking', name: 'Public Speaking', category: 'soft_skill' },
  { key: 'technical-writing', name: 'Technical Writing', category: 'soft_skill' },
]

export const orgs: OrgSpec[] = [
  {
    key: 'cascadia',
    name: 'Cascadia Institute of Technology',
    org_type: 'education',
    tags: ['university'],
    industry: 'Higher Education',
    size: '9,000 students',
    worked: true,
    employment_type: 'civilian',
    website: 'https://cascadia-tech.example.org',
    status: null,
    aliases: ['Cascadia Tech', 'CIT'],
    locations: [
      {
        key: 'main',
        name: 'Tacoma Campus',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Tacoma, WA', street_1: '500 Example Way', city: 'Tacoma', state: 'WA', zip: '98402' },
      },
    ],
    daysAgo: 530,
  },
  {
    key: 'lakehaven',
    name: 'Lakehaven Polytechnic University',
    org_type: 'education',
    tags: ['university'],
    industry: 'Higher Education',
    size: '14,000 students',
    worked: false,
    website: 'https://lakehaven-poly.example.org',
    status: null,
    aliases: ['Lakehaven Poly'],
    locations: [
      {
        key: 'main',
        name: 'North Campus',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Rochester, NY', street_1: '1 Example Circle', city: 'Rochester', state: 'NY', zip: '14623' },
      },
    ],
    daysAgo: 529,
  },
  {
    key: 'ironwood',
    name: 'Ironwood Robotics',
    org_type: 'company',
    tags: ['company'],
    industry: 'Robotics',
    size: '200-500',
    worked: true,
    employment_type: 'civilian',
    website: 'https://ironwood-robotics.example.com',
    linkedin_url: 'https://social.example.com/company/ironwood-robotics',
    status: null,
    aliases: ['Ironwood'],
    locations: [
      {
        key: 'hq',
        name: 'San Jose Lab',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'San Jose, CA', street_1: '2200 Example Parkway', city: 'San Jose', state: 'CA', zip: '95134' },
      },
    ],
    daysAgo: 527,
  },
  {
    key: 'meridian',
    name: 'Meridian Applied AI',
    org_type: 'company',
    tags: ['company'],
    industry: 'Artificial Intelligence',
    size: '500-1,000',
    worked: true,
    employment_type: 'civilian',
    website: 'https://meridian-applied.example.com',
    glassdoor_url: 'https://reviews.example.com/meridian-applied-ai',
    glassdoor_rating: 4.1,
    status: null,
    aliases: ['Meridian AI'],
    locations: [
      {
        key: 'hq',
        name: 'Portland Office',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Portland, OR', street_1: '900 Example Avenue', city: 'Portland', state: 'OR', zip: '97209' },
      },
      { key: 'remote', name: 'Remote (US)', modality: 'remote' },
    ],
    daysAgo: 526,
  },
  {
    key: 'lanternfish',
    name: 'Lanternfish Systems',
    org_type: 'company',
    tags: ['company', 'platform'],
    industry: 'Developer Tools',
    size: '200-500',
    worked: true,
    employment_type: 'civilian',
    website: 'https://lanternfish.example.com',
    linkedin_url: 'https://social.example.com/company/lanternfish-systems',
    status: null,
    locations: [
      {
        key: 'hq',
        name: 'Seattle Headquarters',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Seattle, WA', street_1: '610 Example Place', street_2: 'Floor 9', city: 'Seattle', state: 'WA', zip: '98104' },
      },
      { key: 'remote', name: 'Remote (North America)', modality: 'remote' },
    ],
    daysAgo: 525,
  },
  {
    key: 'nwrc',
    name: 'Northwest Robotics Consortium',
    org_type: 'nonprofit',
    tags: ['conference', 'nonprofit'],
    industry: 'Professional Associations',
    worked: false,
    website: 'https://nw-robotics.example.org',
    status: null,
    daysAgo: 520,
  },
  {
    key: 'pacific-robot-league',
    name: 'Pacific Robot League',
    org_type: 'volunteer',
    tags: ['volunteer', 'nonprofit'],
    industry: 'STEM Education',
    worked: true,
    employment_type: 'volunteer',
    website: 'https://robotleague.example.org',
    status: null,
    daysAgo: 516,
  },
  {
    key: 'ampg',
    name: 'Applied ML Practitioners Guild',
    org_type: 'nonprofit',
    tags: ['nonprofit', 'conference'],
    industry: 'Professional Certification',
    worked: false,
    website: 'https://ampg.example.org',
    status: null,
    aliases: ['AMPG'],
    daysAgo: 512,
  },
  {
    key: 'open-agents',
    name: 'Open Agents Foundation',
    org_type: 'nonprofit',
    tags: ['nonprofit', 'conference'],
    industry: 'Open Source',
    worked: false,
    website: 'https://openagents.example.org',
    status: null,
    aliases: ['OAF'],
    daysAgo: 405,
  },
  {
    key: 'harborlight',
    name: 'Harborlight Cloud',
    org_type: 'company',
    tags: ['company', 'vendor', 'platform'],
    industry: 'Cloud Computing',
    size: '10,000+',
    worked: false,
    website: 'https://harborlight-cloud.example.com',
    linkedin_url: 'https://social.example.com/company/harborlight-cloud',
    glassdoor_url: 'https://reviews.example.com/harborlight-cloud',
    glassdoor_rating: 3.8,
    status: 'interested',
    aliases: ['Harborlight'],
    locations: [
      {
        key: 'hq',
        name: 'Bellevue Campus',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Bellevue, WA', street_1: '400 Example Boulevard', city: 'Bellevue', state: 'WA', zip: '98004' },
      },
      {
        key: 'seattle',
        name: 'Seattle Office',
        modality: 'hybrid',
        address: { name: 'Seattle, WA', street_1: '1201 Example Avenue', city: 'Seattle', state: 'WA', zip: '98101' },
      },
      { key: 'remote', name: 'Remote (US)', modality: 'remote' },
    ],
    daysAgo: 300,
  },
  {
    key: 'sablepoint',
    name: 'Sablepoint AI',
    org_type: 'company',
    tags: ['company'],
    industry: 'Artificial Intelligence',
    size: '50-200',
    worked: false,
    website: 'https://sablepoint.example.com',
    linkedin_url: 'https://social.example.com/company/sablepoint-ai',
    status: 'researching',
    locations: [
      {
        key: 'hq',
        name: 'San Francisco Office',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'San Francisco, CA', street_1: '88 Example Street', street_2: 'Suite 400', city: 'San Francisco', state: 'CA', zip: '94105' },
      },
    ],
    daysAgo: 120,
  },
  {
    key: 'quantcrest',
    name: 'Quantcrest Capital',
    org_type: 'company',
    tags: ['company'],
    industry: 'Quantitative Finance',
    size: '200-500',
    worked: false,
    website: 'https://quantcrest.example.com',
    glassdoor_url: 'https://reviews.example.com/quantcrest-capital',
    glassdoor_rating: 4.4,
    status: 'exciting',
    locations: [
      {
        key: 'hq',
        name: 'New York Office',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'New York, NY', street_1: '300 Example Plaza', street_2: 'Floor 31', city: 'New York', state: 'NY', zip: '10007' },
      },
    ],
    daysAgo: 95,
  },
  {
    key: 'copperline',
    name: 'Copperline Markets',
    org_type: 'company',
    tags: ['company'],
    industry: 'Quantitative Finance',
    size: '50-200',
    worked: false,
    website: 'https://copperline-markets.example.com',
    status: 'backlog',
    locations: [
      {
        key: 'hq',
        name: 'Manhattan Office',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'New York, NY', street_1: '45 Example Lane', city: 'New York', state: 'NY', zip: '10004' },
      },
    ],
    daysAgo: 40,
  },
  {
    key: 'northbeam',
    name: 'Northbeam Logistics',
    org_type: 'company',
    tags: ['company'],
    industry: 'Logistics',
    size: '1,000-5,000',
    worked: false,
    website: 'https://northbeam.example.com',
    status: 'acceptable',
    locations: [{ key: 'remote', name: 'Remote (US)', modality: 'remote', is_headquarters: true }],
    daysAgo: 70,
  },
  {
    key: 'tidewater',
    name: 'Tidewater Health Systems',
    org_type: 'company',
    tags: ['company'],
    industry: 'Healthcare',
    size: '5,000+',
    worked: false,
    website: 'https://tidewater-health.example.org',
    status: 'excluded',
    locations: [
      {
        key: 'hq',
        name: 'Sacramento Campus',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Sacramento, CA', street_1: '1600 Example Road', city: 'Sacramento', state: 'CA', zip: '95814' },
      },
    ],
    daysAgo: 115,
  },
]

export const credentials: CredentialSpec[] = [
  {
    key: 'wa-license',
    credential_type: 'drivers_license',
    label: 'Washington Driver License',
    status: 'active',
    details: { class: 'Standard', state: 'WA', endorsements: [] },
    issued: { monthsAgo: 26, day: 9 },
    expires: { monthsAgo: -46, day: 9 },
    daysAgo: 518,
  },
]

export const certifications: CertificationSpec[] = [
  {
    key: 'ampg-mlsp',
    short_name: 'AMPG ML Systems Professional',
    long_name: 'Applied ML Practitioners Guild Certified ML Systems Professional',
    cert_id: 'AMPG-MLSP',
    issuerKey: 'ampg',
    earned: { monthsAgo: 31, day: 12 },
    expires: { monthsAgo: -5, day: 12 },
    credential_id: 'MLSP-20417',
    credential_url: 'https://ampg.example.org/verify/MLSP-20417',
    in_progress: false,
    skills: ['mlops', 'model-evaluation', 'experiment-design'],
    daysAgo: 511,
  },
  {
    key: 'harborlight-sap',
    short_name: 'Harborlight Solutions Architect Professional',
    long_name: 'Harborlight Cloud Certified Solutions Architect - Professional',
    cert_id: 'HLC-SAP',
    issuerKey: 'harborlight',
    earned: { monthsAgo: 7, day: 2 },
    expires: { monthsAgo: -29, day: 2 },
    credential_id: 'HLC-SAP-88310',
    credential_url: 'https://certs.harborlight-cloud.example.com/verify/88310',
    credly_url: 'https://badges.example.com/harborlight-sap/88310',
    in_progress: false,
    skills: ['kubernetes', 'distributed-systems', 'llms'],
    daysAgo: 205,
  },
  {
    key: 'oaf-asp',
    short_name: 'OAF Agent Security Practitioner',
    long_name: 'Open Agents Foundation Agent Security Practitioner',
    cert_id: 'OAF-ASP',
    issuerKey: 'open-agents',
    in_progress: true,
    skills: ['prompt-injection', 'agent-orchestration'],
    daysAgo: 52,
  },
]
