/// <reference lib="webworker" />
/**
 * Typst compiler Worker. Loads the forge-typst wasm (about 25 MB, so it is only created when
 * a PDF is first asked for) and compiles Typst source to PDF bytes.
 *
 * Build the wasm first: `just typst-bundle` (writes ../typst-pkg).
 */

// @ts-ignore -- generated by `just typst-bundle`; absent until then
import init, { compilePdf } from '../typst-pkg/forge_typst.js'
import type { PdfReply, PdfRequest } from './protocol'

let loaded: Promise<unknown> | undefined

self.onmessage = async (event: MessageEvent<PdfRequest>) => {
  const { id, source } = event.data
  let reply: PdfReply
  try {
    loaded ??= init()
    await loaded
    reply = { id, ok: true, result: compilePdf(source) as Uint8Array }
  } catch (e) {
    // forge-typst throws a JSON string; anything else is a plain failure.
    reply = { id, ok: false, error: typeof e === 'string' ? e : e instanceof Error ? e.message : String(e) }
  }
  const transfer: Transferable[] = reply.ok ? [reply.result.buffer as ArrayBuffer] : []
  ;(self as unknown as Worker).postMessage(reply, transfer)
}
