/// <reference lib="webworker" />
/**
 * Database Worker: loads the Rust runtime (forge-wasm) and serves the page's requests.
 *
 * Must be a *dedicated* Worker: the OPFS storage needs `FileSystemSyncAccessHandle`,
 * which a SharedWorker does not have (verified; see ADR 0002), and only one Worker
 * may own the database at a time (the page arranges that with a Web Lock).
 *
 * Build the wasm first: `just wasm-bundle` (writes ../pkg).
 */

// @ts-ignore -- generated by `just wasm-bundle`; absent until then
import init, { start, request, exportDatabase, importDatabase } from '../pkg/forge_wasm.js'
import type { WorkerReply, WorkerRequest } from './protocol'

let loaded: Promise<unknown> | undefined

async function handle(msg: WorkerRequest): Promise<unknown> {
  loaded ??= init()
  await loaded

  switch (msg.op) {
    case 'start':
      return JSON.parse(await start())
    case 'request': {
      const res = await request(msg.method, msg.path, JSON.stringify(msg.headers), msg.body)
      return { status: res.status, headers: res.headers, body: res.body }
    }
    case 'export':
      return exportDatabase() as Uint8Array
    case 'import':
      return JSON.parse(importDatabase(msg.bytes))
  }
}

self.onmessage = async (event: MessageEvent<WorkerRequest>) => {
  const msg = event.data
  let reply: WorkerReply
  try {
    reply = { id: msg.id, ok: true, result: await handle(msg) }
  } catch (e) {
    reply = { id: msg.id, ok: false, error: e instanceof Error ? e.message : String(e) }
  }
  // Transfer binary results instead of copying them.
  const result = reply.ok ? reply.result : undefined
  const body = result && typeof result === 'object' && 'body' in result ? (result as { body: Uint8Array }).body : undefined
  const transfer: Transferable[] = result instanceof Uint8Array ? [result.buffer] : body ? [body.buffer] : []
  ;(self as unknown as Worker).postMessage(reply, transfer)
}
