/**
 * cleared-security-engineer: summaries, job descriptions, contacts, resumes and notes.
 */

import type { ContactSpec, JdSpec, NoteSpec, ResumeSpec, SummarySpec } from '../../corpus/types'

export const summaries: SummarySpec[] = [
  {
    key: 's-federal',
    title: 'Cleared senior security engineer (federal)',
    role: 'Senior Security Engineer',
    description:
      'Cleared senior security engineer (TS/SCI with CI polygraph) with eleven years across military network defense, defense security operations and federal modernization programs. Automates control evidence, host hardening and authorization work so mission systems stay compliant between assessments.',
    industryKey: 'federal-civilian',
    roleTypeKey: 'security-engineer',
    skills: ['rmf', 'security-control-assessment', 'ansible', 'python', 'incident-response', 'zero-trust'],
    daysAgo: 300,
  },
  {
    key: 's-zero-trust',
    title: 'Zero trust and platform security architect',
    role: 'Security Architect',
    description:
      'Security engineer who designs identity-aware access, segmentation and container platform controls, then measures whether they actually shrink the attack surface.',
    industryKey: 'defense',
    roleTypeKey: 'security-architect',
    skills: ['zero-trust', 'network-segmentation', 'kubernetes', 'pki', 'least-privilege'],
    daysAgo: 150,
  },
  {
    key: 's-isso-template',
    title: 'ISSO and authorization template',
    role: 'Information Systems Security Officer',
    description: 'Lead with authorization outcomes and assessor relationships, then the automation that keeps controls continuously in place.',
    is_template: true,
    industryKey: 'federal-civilian',
    roleTypeKey: 'isso',
    notes: 'Use for ISSO and assessment roles; keep the clearance line in the header.',
    skills: ['rmf', 'security-control-assessment', 'technical-writing'],
    daysAgo: 220,
  },
]

export const jds: JdSpec[] = [
  {
    key: 'jd-kettlerock-principal',
    title: 'Principal Security Engineer',
    orgKey: 'kettlerock',
    url: 'https://jobs.example.com/kettlerock-mission-systems/principal-security-engineer',
    file: 'kettlerock-principal-security-engineer.md',
    status: 'interviewing',
    salary_min: 190000,
    salary_max: 228000,
    salary_range: '$190,000 - $228,000',
    location: 'Annapolis Junction, MD',
    skills: ['zero-trust', 'kubernetes', 'pki', 'detection-engineering', 'python', 'threat-modeling'],
    daysAgo: 46,
    updatedDaysAgo: 6,
  },
  {
    key: 'jd-dsfn-lead',
    title: 'Lead Cybersecurity Engineer',
    orgKey: 'dsfn',
    url: 'https://jobs.example.com/dsfn/lead-cybersecurity-engineer',
    file: 'dsfn-lead-cybersecurity-engineer.md',
    status: 'applied',
    salary_min: 163000,
    salary_max: 191000,
    salary_range: '$163,000 - $191,000',
    location: 'Washington, DC',
    skills: ['rmf', 'security-control-assessment', 'zero-trust', 'vulnerability-management', 'technical-writing'],
    daysAgo: 72,
    updatedDaysAgo: 41,
  },
  {
    key: 'jd-halyard-zt',
    title: 'Zero Trust Architect',
    orgKey: 'halyard',
    url: 'https://jobs.example.com/halyard-analytics/zero-trust-architect',
    file: 'halyard-zero-trust-architect.md',
    status: 'offered',
    salary_min: 192000,
    salary_max: 220000,
    salary_range: '$192,000 - $220,000',
    location: 'Arlington, VA (hybrid)',
    skills: ['zero-trust', 'network-segmentation', 'saml', 'least-privilege', 'stakeholder-communication'],
    daysAgo: 82,
    updatedDaysAgo: 3,
  },
  {
    key: 'jd-tessellate-arch',
    title: 'Public Sector Cloud Security Architect',
    orgKey: 'tessellate',
    url: 'https://jobs.example.com/tessellate-cloud/public-sector-cloud-security-architect',
    file: 'tessellate-public-sector-cloud-security-architect.md',
    status: 'analyzing',
    salary_min: 205000,
    salary_max: 245000,
    salary_range: '$205,000 - $245,000 plus equity',
    location: 'Remote (US)',
    skills: ['kubernetes', 'terraform', 'zero-trust', 'pki', 'stakeholder-communication'],
    daysAgo: 13,
    updatedDaysAgo: 10,
  },
  {
    key: 'jd-spruce-detection',
    title: 'Detection Engineering Lead',
    orgKey: 'spruce-canyon',
    url: 'https://jobs.example.com/spruce-canyon/detection-engineering-lead',
    file: 'spruce-canyon-detection-engineering-lead.md',
    status: 'discovered',
    salary_min: 176000,
    salary_max: 204000,
    salary_range: '$176,000 - $204,000',
    location: 'Colorado Springs, CO',
    skills: ['detection-engineering', 'siem-engineering', 'zeek', 'suricata', 'technical-leadership'],
    daysAgo: 5,
  },
  {
    key: 'jd-anvil-ir',
    title: 'Senior Incident Response Engineer',
    orgKey: 'anvil-point',
    url: 'https://jobs.example.com/anvil-point-cyber/senior-incident-response-engineer',
    file: 'anvil-point-senior-incident-response-engineer.md',
    status: 'applying',
    salary_min: 170000,
    salary_max: 198000,
    salary_range: '$170,000 - $198,000',
    location: 'Aurora, CO (hybrid)',
    skills: ['incident-response', 'digital-forensics', 'osquery', 'powershell', 'python'],
    daysAgo: 19,
    updatedDaysAgo: 7,
  },
  {
    key: 'jd-larkspur-isso',
    title: 'Information Systems Security Officer',
    orgKey: 'larkspur',
    url: 'https://jobs.example.com/larkspur-integrated/information-systems-security-officer',
    file: 'larkspur-information-systems-security-officer.md',
    status: 'rejected',
    salary_min: 150000,
    salary_max: 172000,
    salary_range: '$150,000 - $172,000',
    location: 'Washington, DC',
    skills: ['rmf', 'security-control-assessment', 'vulnerability-management', 'technical-writing'],
    daysAgo: 122,
    updatedDaysAgo: 76,
  },
  {
    key: 'jd-capitol-manager',
    title: 'Security Engineering Manager',
    orgKey: 'capitol-beacon',
    url: 'https://jobs.example.com/capitol-beacon/security-engineering-manager',
    file: 'capitol-beacon-security-engineering-manager.md',
    status: 'withdrawn',
    salary_min: 196000,
    salary_max: 232000,
    salary_range: '$196,000 - $232,000',
    location: 'Washington, DC (hybrid)',
    skills: ['technical-leadership', 'mentoring', 'rmf', 'stakeholder-communication'],
    daysAgo: 96,
    updatedDaysAgo: 61,
  },
  {
    key: 'jd-ridgeback-staff',
    title: 'Staff Platform Security Engineer',
    orgKey: 'ridgeback',
    url: 'https://jobs.example.com/ridgeback-federal/staff-platform-security-engineer',
    file: 'ridgeback-staff-platform-security-engineer.md',
    status: 'closed',
    salary_min: 182000,
    salary_max: 206000,
    salary_range: '$182,000 - $206,000',
    location: 'Chantilly, VA',
    skills: ['kubernetes', 'ansible', 'terraform', 'linux', 'devsecops'],
    daysAgo: 302,
    updatedDaysAgo: 262,
  },
  {
    key: 'jd-halyard-devsecops',
    title: 'Senior DevSecOps Engineer',
    orgKey: 'halyard',
    url: 'https://jobs.example.com/halyard-analytics/senior-devsecops-engineer',
    file: 'halyard-senior-devsecops-engineer.md',
    status: 'discovered',
    salary_min: 166000,
    salary_max: 190000,
    salary_range: '$166,000 - $190,000',
    location: 'Remote (US)',
    skills: ['devsecops', 'kubernetes', 'terraform', 'docker', 'go'],
    daysAgo: 2,
  },
]

export const contacts: ContactSpec[] = [
  {
    key: 'c-renata-solis',
    name: 'Renata Solis',
    title: 'Cleared Technical Recruiter',
    email: 'renata.solis@example.com',
    phone: '(410) 555-0127',
    linkedin: 'https://social.example.com/in/renata-solis',
    team: 'Talent Acquisition',
    notes: 'Handles all cleared engineering roles; prefers a call before each interview round.',
    orgKey: 'kettlerock',
    orgLinks: [{ orgKey: 'kettlerock', relationship: 'recruiter' }],
    jdLinks: [{ jdKey: 'jd-kettlerock-principal', relationship: 'recruiter' }],
    resumeLinks: [],
    daysAgo: 44,
  },
  {
    key: 'c-dwight-amberly',
    name: 'Dwight Amberly',
    title: 'Program Manager, Network Modernization',
    email: 'dwight.amberly@example.com',
    phone: '(571) 555-0148',
    team: 'Network Modernization Program',
    notes: 'Current manager. Has offered to write a recommendation for federal applications.',
    orgKey: 'ridgeback',
    orgLinks: [{ orgKey: 'ridgeback', relationship: 'manager' }],
    jdLinks: [{ jdKey: 'jd-ridgeback-staff', relationship: 'other' }],
    resumeLinks: [{ resumeKey: 'r-dsfn-federal', relationship: 'recommender' }],
    daysAgo: 540,
  },
  {
    key: 'c-priya-halvorsen',
    name: 'Priya Halvorsen',
    title: 'Chief Engineer, Zero Trust Practice',
    email: 'priya.halvorsen@example.com',
    linkedin: 'https://social.example.com/in/priya-halvorsen',
    team: 'Zero Trust Practice',
    orgKey: 'halyard',
    orgLinks: [{ orgKey: 'halyard', relationship: 'other' }],
    jdLinks: [{ jdKey: 'jd-halyard-zt', relationship: 'hiring_manager' }],
    resumeLinks: [],
    daysAgo: 78,
  },
  {
    key: 'c-marcus-oyelaran',
    name: 'Marcus Oyelaran',
    title: 'Human Resources Specialist',
    email: 'marcus.oyelaran@example.com',
    phone: '(202) 555-0163',
    dept: 'Office of Human Capital',
    orgKey: 'dsfn',
    orgLinks: [{ orgKey: 'dsfn', relationship: 'hr' }],
    jdLinks: [{ jdKey: 'jd-dsfn-lead', relationship: 'interviewer' }],
    resumeLinks: [],
    daysAgo: 66,
  },
  {
    key: 'c-alana-whitmore',
    name: 'Alana Whitmore',
    title: 'Incident Response Manager',
    email: 'alana.whitmore@example.com',
    phone: '(720) 555-0152',
    linkedin: 'https://social.example.com/in/alana-whitmore',
    notes: 'Worked tier-3 together at Granite Point; now runs the response team at Anvil Point and offered a referral.',
    orgKey: 'anvil-point',
    orgLinks: [
      { orgKey: 'anvil-point', relationship: 'referral' },
      { orgKey: 'granite-point', relationship: 'peer' },
    ],
    jdLinks: [{ jdKey: 'jd-anvil-ir', relationship: 'referral' }],
    resumeLinks: [
      { resumeKey: 'r-dsfn-federal', relationship: 'reference' },
      { resumeKey: 'r-kettlerock-federal', relationship: 'reference' },
    ],
    daysAgo: 31,
  },
  {
    key: 'c-theo-brandvold',
    name: 'Theo Brandvold',
    title: 'Retired Battalion Operations Officer',
    email: 'theo.brandvold@example.com',
    phone: '(910) 555-0171',
    notes: 'Former operations officer from the signal battalion; reliable reference for the military years.',
    orgKey: 'battalion',
    orgLinks: [
      { orgKey: 'battalion', relationship: 'other' },
      { orgKey: 'vcmn', relationship: 'peer' },
    ],
    jdLinks: [],
    resumeLinks: [{ resumeKey: 'r-kettlerock-federal', relationship: 'reference' }],
    daysAgo: 522,
  },
  {
    key: 'c-jun-takeda',
    name: 'Jun Takeda',
    title: 'Public Sector Solutions Lead',
    email: 'jun.takeda@example.com',
    linkedin: 'https://social.example.com/in/jun-takeda',
    notes: 'Met at the summit after the talk. Suggested the architect role and offered to review the draft resume.',
    orgKey: 'tessellate',
    orgLinks: [{ orgKey: 'tessellate', relationship: 'peer' }],
    jdLinks: [{ jdKey: 'jd-tessellate-arch', relationship: 'other' }],
    resumeLinks: [{ resumeKey: 'r-tessellate-cloud', relationship: 'other' }],
    daysAgo: 12,
  },
]

// Federal Resume template sections (migration 008), plus the ones the generator adds.
const QUALIFICATIONS = 'Summary of Qualifications'
const FED_EXPERIENCE = 'Professional Experience'
const COMPETENCIES = 'Technical Competencies'
const EDUCATION = 'Education & Certifications'
const PROJECTS = 'Selected Projects'
const CERTIFICATIONS = 'Certifications'
const PRESENTATIONS = 'Presentations'
// Standard Tech Resume sections.
const SUMMARY = 'Summary'
const EXPERIENCE = 'Experience'
const SKILLS = 'Technical Skills'

export const resumes: ResumeSpec[] = [
  {
    key: 'r-dsfn-federal',
    name: 'DSFN - Lead Cybersecurity Engineer (Federal)',
    target_role: 'Lead Cybersecurity Engineer',
    target_employer: 'Directorate of Secure Federal Networks',
    archetype: 'public-sector',
    template: 'Federal Resume',
    summaryKey: 's-federal',
    status: 'approved',
    extraSections: [
      { title: CERTIFICATIONS, entry_type: 'certifications' },
      { title: PRESENTATIONS, entry_type: 'presentations' },
    ],
    entries: [
      {
        key: 'r1-qualifications',
        section: QUALIFICATIONS,
        content:
          'Eleven years securing military and federal networks; active TS/SCI with CI polygraph. Led three systems to authorization, automated evidence for 180 controls, and delivered a zero trust pilot the agency is extending. Protected veteran.',
      },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-cmon-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-ato-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-harden-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-mentor-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-siem-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-ir-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-bn-defense-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-bn-fw-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-bn-lead-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-bn-award-ps' },
      { section: EDUCATION, sourceKey: 'ms-cyber' },
      { section: EDUCATION, sourceKey: 'bs-iss' },
      { section: PROJECTS, perspectiveKey: 'p-zt-id-ps' },
      { key: 'r1-proj-zt-rollout', section: PROJECTS, perspectiveKey: 'p-zt-roll-ps' },
      { section: PROJECTS, perspectiveKey: 'p-ms-thesis-ps' },
      { section: PROJECTS, perspectiveKey: 'p-vc-mentor-ps' },
      { section: PRESENTATIONS, perspectiveKey: 'p-talk-ps' },
    ],
    skills: {
      [COMPETENCIES]: [
        'rmf', 'security-control-assessment', 'zero-trust', 'network-segmentation', 'pki', 'vulnerability-management',
        'incident-response', 'ansible', 'python', 'linux', 'windows-server', 'technical-writing',
      ],
    },
    certifications: { [CERTIFICATIONS]: ['csse', 'fapc-ap', 'ocih'] },
    jdKeys: ['jd-dsfn-lead', 'jd-capitol-manager'],
    daysAgo: 70,
    updatedDaysAgo: 40,
  },
  {
    key: 'r-kettlerock-federal',
    name: 'Kettlerock Mission Systems - Principal Security Engineer',
    target_role: 'Principal Security Engineer',
    target_employer: 'Kettlerock Mission Systems',
    archetype: 'security-engineer',
    template: 'Federal Resume',
    summaryKey: 's-zero-trust',
    status: 'in_review',
    extraSections: [{ title: CERTIFICATIONS, entry_type: 'certifications' }],
    entries: [
      {
        key: 'r2-qualifications',
        section: QUALIFICATIONS,
        content:
          'Security engineer with an active TS/SCI and CI polygraph who builds detection, hardening and zero trust controls for mission networks, and measures whether they work.',
      },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-cmon-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-harden-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-k8s-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-pki-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-siem-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-ids-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-ir-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-scan-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-osq-se' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-bn-defense-se' },
      { section: EDUCATION, sourceKey: 'ms-cyber' },
      { section: EDUCATION, sourceKey: 'bs-iss' },
      { section: PROJECTS, perspectiveKey: 'p-zt-id-se' },
      { key: 'r2-proj-zt-seg', section: PROJECTS, perspectiveKey: 'p-zt-seg-se' },
      { section: PROJECTS, perspectiveKey: 'p-bk-tool-se' },
      { section: PROJECTS, perspectiveKey: 'p-ms-thesis-se' },
    ],
    skills: {
      [COMPETENCIES]: [
        'zero-trust', 'kubernetes', 'docker', 'pki', 'tls', 'suricata', 'zeek', 'osquery', 'siem-engineering',
        'detection-engineering', 'python', 'go',
      ],
    },
    certifications: { [CERTIFICATIONS]: ['csse', 'ocih', 'tcss'] },
    jdKeys: ['jd-kettlerock-principal', 'jd-halyard-zt'],
    daysAgo: 42,
    updatedDaysAgo: 8,
  },
  {
    key: 'r-tessellate-cloud',
    name: 'Tessellate Cloud - Public Sector Cloud Security Architect',
    target_role: 'Public Sector Cloud Security Architect',
    target_employer: 'Tessellate Cloud',
    archetype: 'infrastructure',
    template: 'Standard Tech Resume',
    status: 'draft',
    extraSections: [],
    entries: [
      {
        key: 'r3-summary',
        section: SUMMARY,
        content: 'Platform security engineer who has run Kubernetes, PKI and hardening automation for cleared federal programs.',
      },
      { section: EXPERIENCE, perspectiveKey: 'p-rb-k8s-inf' },
      { section: EXPERIENCE, perspectiveKey: 'p-rb-pki-inf' },
      { section: EXPERIENCE, perspectiveKey: 'p-rb-harden-inf' },
      { section: EDUCATION, sourceKey: 'ms-cyber' },
      { section: PROJECTS, perspectiveKey: 'p-bk-tool-inf' },
      { section: PROJECTS, perspectiveKey: 'p-bk-ci-inf' },
      { section: PROJECTS, perspectiveKey: 'p-zt-seg-inf' },
    ],
    skills: { [SKILLS]: ['kubernetes', 'terraform', 'ansible', 'docker', 'go', 'python', 'zero-trust'] },
    certifications: {},
    jdKeys: ['jd-tessellate-arch', 'jd-halyard-devsecops'],
    daysAgo: 11,
  },
  {
    key: 'r-larkspur-isso',
    name: 'Larkspur Integrated Systems - ISSO',
    target_role: 'Information Systems Security Officer',
    target_employer: 'Larkspur Integrated Systems',
    archetype: 'public-sector',
    template: 'Federal Resume',
    summaryKey: 's-isso-template',
    status: 'rejected',
    extraSections: [],
    entries: [
      {
        key: 'r4-qualifications',
        section: QUALIFICATIONS,
        content: 'Authorization lead for three federal mission systems, with hands-on scanning and remediation experience.',
      },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-rb-ato-ps' },
      { section: FED_EXPERIENCE, perspectiveKey: 'p-gp-scan-se' },
      { section: EDUCATION, sourceKey: 'bs-iss' },
    ],
    skills: { [COMPETENCIES]: ['rmf', 'security-control-assessment', 'vulnerability-management'] },
    certifications: {},
    jdKeys: ['jd-larkspur-isso'],
    daysAgo: 120,
    updatedDaysAgo: 75,
  },
  {
    key: 'r-ridgeback-staff',
    name: 'Ridgeback Federal Solutions - Staff Platform Security Engineer (internal)',
    target_role: 'Staff Platform Security Engineer',
    target_employer: 'Ridgeback Federal Solutions',
    archetype: 'infrastructure',
    template: 'Standard Tech Resume',
    status: 'archived',
    extraSections: [],
    entries: [
      {
        key: 'r5-summary',
        section: SUMMARY,
        content: 'Internal transfer application for the platform security team.',
      },
      { section: EXPERIENCE, perspectiveKey: 'p-rb-harden-inf' },
      { section: EXPERIENCE, perspectiveKey: 'p-gp-ids-inf' },
      { section: PROJECTS, perspectiveKey: 'p-bk-ci-inf' },
    ],
    skills: { [SKILLS]: ['ansible', 'terraform', 'linux'] },
    certifications: {},
    jdKeys: ['jd-ridgeback-staff'],
    daysAgo: 292,
    updatedDaysAgo: 252,
  },
]

export const notes: NoteSpec[] = [
  {
    key: 'n-kettlerock-prep',
    title: 'Kettlerock panel prep',
    content:
      'Final panel next week: system design on segmentation, then a detection-rule walkthrough. Renata says they care about measuring control effectiveness, so lead with the 70% reachability number. Bring questions about on-site days and the polygraph reciprocity process.',
    refs: [
      { type: 'job_description', key: 'jd-kettlerock-principal' },
      { type: 'organization', key: 'kettlerock' },
      { type: 'contact', key: 'c-renata-solis' },
      { type: 'resume', key: 'r-kettlerock-federal' },
    ],
    daysAgo: 6,
  },
  {
    key: 'n-reinvestigation',
    title: 'Clearance reinvestigation',
    content:
      'Continuous vetting enrollment confirmed by the sponsoring agency. Keep the foreign travel log current and report the new address within five days of any move.',
    refs: [
      { type: 'credential', key: 'ts-sci' },
      { type: 'organization', key: 'dsfn' },
    ],
    daysAgo: 140,
  },
  {
    key: 'n-cert-renewals',
    title: 'Certification renewals',
    content:
      'CSSE renewal is due in four months: log the summit talk and the thesis for continuing education credits. Finish the Tessellate specialty exam before the architect interviews start.',
    refs: [
      { type: 'certification', key: 'csse' },
      { type: 'certification', key: 'tcss' },
      { type: 'skill', key: 'kubernetes' },
    ],
    daysAgo: 60,
  },
  {
    key: 'n-zt-story',
    title: 'Zero trust story for interviews',
    content:
      'Situation: flat VPN, red-team findings on lateral movement. Action: identity and posture checks, 40 policy zones. Result: 70% fewer reachable hosts and a plan adopted for two more systems. Use the segmentation entry, not the pilot overview.',
    refs: [
      { type: 'source', key: 'zt-pilot' },
      { type: 'bullet', key: 'zt-segmentation' },
      { type: 'perspective', key: 'p-zt-seg-se' },
      { type: 'resume_entry', key: 'r2-proj-zt-seg' },
    ],
    daysAgo: 35,
  },
  {
    key: 'n-federal-format',
    title: 'Federal resume formatting',
    content:
      'The DSFN posting asks for hours per week and supervisor contact for each role. Keep the qualifications summary to four lines and ask Dwight to confirm he can be listed as a supervisor contact.',
    refs: [
      { type: 'resume', key: 'r-dsfn-federal' },
      { type: 'resume_entry', key: 'r1-qualifications' },
      { type: 'contact', key: 'c-dwight-amberly' },
      { type: 'job_description', key: 'jd-dsfn-lead' },
    ],
    daysAgo: 42,
  },
  {
    key: 'n-larkspur-debrief',
    content:
      'Larkspur passed after the second interview: they wanted an ISSO who would stay on paperwork full-time. Fine. Moved them to excluded; not a fit for engineering work.',
    refs: [
      { type: 'job_description', key: 'jd-larkspur-isso' },
      { type: 'organization', key: 'larkspur' },
    ],
    daysAgo: 74,
  },
  {
    key: 'n-colorado-move',
    title: 'Colorado relocation math',
    content:
      'Aurora and Colorado Springs roles would mean moving. Check whether either would sponsor relocation, and remember the license and vehicle registration need to transfer within 90 days.',
    refs: [
      { type: 'credential', key: 'va-license' },
      { type: 'organization', key: 'spruce-canyon' },
      { type: 'organization', key: 'anvil-point' },
    ],
    daysAgo: 4,
  },
]
