/**
 * cleared-security-engineer: sources, bullets and perspectives.
 *
 * Source statuses other than `draft`, and the `archived` bullets and perspectives, are set
 * by the post-pass overlay (no API route reaches them).
 */

import type { BulletSpec, PerspectiveSpec, SourceSpec } from '../../corpus/types'

export const sources: SourceSpec[] = [
  {
    key: 'ridgeback-role',
    title: 'Senior Security Engineer, Ridgeback Federal Solutions',
    description:
      "Senior security engineer on Ridgeback's network modernization program for the Directorate of Secure Federal Networks. Owns continuous control monitoring, host hardening automation, container platform security and authorization packages for three mission systems; mentors the program's junior engineers.",
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 38, day: 10 },
    role: { orgKey: 'ridgeback', is_current: true, work_arrangement: 'hybrid', total_comp_notes: 'Salaried; clearance differential included in base.' },
    skills: ['python', 'go', 'ansible', 'kubernetes', 'rmf', 'security-control-assessment', 'pki', 'zero-trust', 'technical-leadership'],
    daysAgo: 544,
  },
  {
    key: 'granite-role',
    title: 'Security Engineer, Granite Point Systems',
    description:
      "Security engineer on a defense customer's security operations contract. Built detection content and network sensors, ran authenticated vulnerability scanning, and worked tier-3 incident investigations across 14 sites.",
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 83, day: 15 },
    end: { monthsAgo: 39, day: 30 },
    role: { orgKey: 'granite-point', work_arrangement: 'on-site' },
    skills: ['siem-engineering', 'detection-engineering', 'suricata', 'zeek', 'incident-response', 'vulnerability-management', 'osquery', 'elasticsearch'],
    daysAgo: 543,
  },
  {
    key: 'battalion-role',
    title: 'Network Defense Specialist, 418th Expeditionary Signal Battalion',
    description:
      'Active-duty network defense specialist for a deployable signal battalion. Monitored perimeter sensors, maintained firewall and VPN configurations for forward sites, and supervised a network operations shift.',
    source_type: 'role',
    status: 'approved',
    start: { monthsAgo: 131 },
    end: { monthsAgo: 84, day: 20 },
    role: { orgKey: 'battalion', work_arrangement: 'on-site' },
    skills: ['network-segmentation', 'ipsec', 'kerberos', 'windows-server', 'incident-response', 'technical-leadership'],
    daysAgo: 542,
  },
  {
    key: 'vcmn-role',
    title: 'Volunteer Mentor, Veterans Cyber Mentorship Network',
    description:
      'Volunteer mentor helping transitioning service members move into civilian security work: resume reviews, home-lab practice plans and mock technical interviews, a few hours a month.',
    source_type: 'role',
    status: 'in_review',
    start: { monthsAgo: 60 },
    role: { orgKey: 'vcmn', is_current: true, work_arrangement: 'remote' },
    skills: ['mentoring', 'stakeholder-communication'],
    daysAgo: 470,
  },
  {
    key: 'bs-iss',
    title: 'B.S. in Information Systems Security',
    description:
      'Bachelor of Science in Information Systems Security from Potomac Valley University, completed in the evening program after military service. Coursework in network security, cryptography, secure software design and digital forensics.',
    source_type: 'education',
    status: 'approved',
    start: { monthsAgo: 82 },
    end: { monthsAgo: 46, day: 15 },
    education: {
      education_type: 'degree',
      orgKey: 'potomac-valley',
      campusKey: 'potomac-valley/main',
      field: 'Information Systems Security',
      degree_level: 'bachelors',
      degree_type: 'BS',
      gpa: '3.48',
      location: 'Fairfax, VA',
    },
    skills: ['network-segmentation', 'pki', 'tls', 'digital-forensics'],
    daysAgo: 541,
  },
  {
    key: 'ms-cyber',
    title: 'M.S. in Cybersecurity Engineering',
    description:
      "Online master's program in cybersecurity engineering at Potomac Valley University, completed part-time while working. Capstone thesis on policy-as-code for continuous authorization of containerized systems.",
    source_type: 'education',
    status: 'approved',
    start: { monthsAgo: 30 },
    end: { monthsAgo: 6, day: 12 },
    education: {
      education_type: 'degree',
      orgKey: 'potomac-valley',
      campusKey: 'potomac-valley/online',
      field: 'Cybersecurity Engineering',
      degree_level: 'masters',
      degree_type: 'MS',
      gpa: '3.91',
      edu_description: 'Part-time, online. Thesis track.',
    },
    skills: ['devsecops', 'kubernetes', 'rmf', 'threat-modeling'],
    daysAgo: 540,
  },
  {
    key: 'container-course',
    title: 'Container Security Deep Dive (online course)',
    description:
      'Self-paced Open Cyber Credentialing Institute course on container security: image provenance, runtime detection, container escape techniques and admission control, with hands-on labs.',
    source_type: 'education',
    status: 'draft',
    start: { monthsAgo: 4 },
    end: { monthsAgo: 3 },
    education: {
      education_type: 'course',
      orgKey: 'occi',
      url: 'https://occi.example.org/courses/container-security-deep-dive',
      field: 'Container Security',
    },
    skills: ['kubernetes', 'docker', 'detection-engineering'],
    daysAgo: 100,
  },
  {
    key: 'zt-pilot',
    title: 'Zero Trust Access Pilot',
    description:
      'Program project replacing a flat remote-access VPN with identity- and device-aware, per-application access for 600 pilot users, and segmenting the pilot enclave into policy zones. Ended with a rollout plan the agency adopted for two more mission systems.',
    source_type: 'project',
    status: 'approved',
    start: { monthsAgo: 26 },
    end: { monthsAgo: 10, day: 28 },
    project: { orgKey: 'ridgeback' },
    skills: ['zero-trust', 'network-segmentation', 'saml', 'least-privilege', 'stakeholder-communication'],
    daysAgo: 539,
  },
  {
    key: 'baseline-kit',
    title: 'Baseline Kit: hardening benchmarks as code',
    description:
      'Personal open-source project that turns host hardening benchmarks into testable Ansible roles, with CI that boots each role in disposable containers and scores it against the benchmark.',
    source_type: 'project',
    status: 'approved',
    start: { monthsAgo: 20 },
    project: { is_personal: true, open_source: true, url: 'https://code.example.com/casey-thornbury/baseline-kit' },
    skills: ['ansible', 'python', 'openscap', 'docker', 'git', 'linux'],
    daysAgo: 538,
  },
  {
    key: 'summit-talk',
    title: 'Talk: Evidence on autopilot - continuous control monitoring',
    description:
      'Thirty-minute conference talk at the Mid-Atlantic Secure Systems Summit on collecting security control evidence continuously instead of once a year, with the pipeline design and the mistakes made along the way.',
    source_type: 'presentation',
    status: 'approved',
    start: { monthsAgo: 11, day: 14 },
    end: { monthsAgo: 11, day: 14 },
    presentation: {
      venue: 'Mid-Atlantic Secure Systems Summit',
      presentation_type: 'conference_talk',
      url: 'https://securesystems-summit.example.org/talks/evidence-on-autopilot',
    },
    skills: ['public-speaking', 'rmf', 'python'],
    daysAgo: 330,
  },
  {
    key: 'guild-briefing',
    title: 'Internal briefing: segmentation pilot lessons',
    description:
      "Internal briefing for Ridgeback's security engineering guild on what worked and what did not in the zero trust segmentation pilot, and how other programs could adopt the policy-zone model.",
    source_type: 'presentation',
    status: 'in_review',
    start: { monthsAgo: 8, day: 6 },
    end: { monthsAgo: 8, day: 6 },
    presentation: { venue: 'Ridgeback Security Engineering Guild', presentation_type: 'internal' },
    skills: ['public-speaking', 'network-segmentation'],
    daysAgo: 235,
  },
  {
    key: 'vets-panel',
    title: 'Panel: From network defender to security engineer',
    description:
      'Panel at the Veterans Cyber Mentorship Network annual meetup on moving from military network defense into civilian security engineering roles.',
    source_type: 'presentation',
    status: 'rejected',
    start: { monthsAgo: 15, day: 9 },
    end: { monthsAgo: 15, day: 9 },
    presentation: {
      venue: 'Veterans Cyber Mentorship Network Annual Meetup',
      presentation_type: 'panel',
      coauthors: 'Alana Whitmore; Theo Brandvold (moderator)',
    },
    skills: ['public-speaking', 'mentoring'],
    daysAgo: 452,
  },
  {
    key: 'ctf-captain',
    title: 'Capture-the-flag team captain',
    description:
      'Captained a six-person capture-the-flag team at regional competitions for two seasons, organizing practice nights on forensics and network challenges.',
    source_type: 'general',
    status: 'archived',
    start: { monthsAgo: 52 },
    end: { monthsAgo: 40 },
    skills: ['digital-forensics', 'incident-response', 'technical-leadership'],
    daysAgo: 520,
  },
  {
    key: 'detection-lab',
    title: 'Home detection lab',
    description:
      'A home lab that replays public attack datasets through Zeek and Suricata on a small Linux cluster, used to test new detection rules before proposing them at work.',
    source_type: 'general',
    status: 'draft',
    start: { monthsAgo: 5 },
    skills: ['zeek', 'suricata', 'linux', 'bash', 'detection-engineering'],
    daysAgo: 40,
  },
]

export const bullets: BulletSpec[] = [
  // Ridgeback Federal Solutions
  {
    key: 'rb-cmon',
    sourceKey: 'ridgeback-role',
    content: 'Built a Python pipeline that collects evidence for 180 security controls nightly, cutting the annual assessment evidence push from six weeks to one.',
    technologies: ['python', 'security-control-assessment', 'rmf', 'elasticsearch'],
    metrics: '180 controls; evidence prep from 6 weeks to 1',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 543,
    reviewedDaysAgo: 541,
  },
  {
    key: 'rb-ato',
    sourceKey: 'ridgeback-role',
    content: "Guided three mission systems through authorization, writing the system security plans and coordinating control assessments with the agency's assessors.",
    technologies: ['rmf', 'security-control-assessment', 'technical-writing'],
    metrics: '3 systems authorized',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 543,
    reviewedDaysAgo: 541,
  },
  {
    key: 'rb-harden',
    sourceKey: 'ridgeback-role',
    content: 'Automated host hardening for 1,200 Linux and Windows servers with Ansible, raising baseline compliance from 71% to 96%.',
    technologies: ['ansible', 'linux', 'windows-server', 'openscap', 'powershell'],
    metrics: '1,200 servers; compliance 71% to 96%',
    domain: 'systems_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 543,
    reviewedDaysAgo: 541,
  },
  {
    key: 'rb-k8s',
    sourceKey: 'ridgeback-role',
    content: "Introduced admission policies and image signing on the program's Kubernetes clusters, blocking unsigned and root-running containers before deployment.",
    technologies: ['kubernetes', 'docker', 'devsecops'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 543,
    reviewedDaysAgo: 540,
  },
  {
    key: 'rb-pki',
    sourceKey: 'ridgeback-role',
    content: 'Replaced hand-issued service certificates with an automated internal PKI workflow written in Go, ending certificate-expiry outages across 300 services.',
    technologies: ['pki', 'tls', 'go'],
    metrics: '300 services; zero expiry outages since',
    domain: 'systems_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 543,
    reviewedDaysAgo: 540,
  },
  {
    key: 'rb-mentor',
    sourceKey: 'ridgeback-role',
    content: 'Mentored four junior engineers through their first authorization packages and on-call rotations.',
    technologies: ['mentoring', 'technical-leadership'],
    metrics: '4 engineers',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 543,
    reviewedDaysAgo: 540,
  },
  {
    key: 'rb-meetings',
    sourceKey: 'ridgeback-role',
    content: 'Attended weekly security status meetings with the government customer.',
    technologies: ['stakeholder-communication'],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Attendance is not an accomplishment; say what was decided or changed.',
    daysAgo: 543,
    reviewedDaysAgo: 540,
  },
  {
    key: 'rb-vuln-sla',
    sourceKey: 'ridgeback-role',
    content: 'Reworked vulnerability triage so critical findings reach the owning team within one business day.',
    technologies: ['vulnerability-management'],
    metrics: null,
    domain: 'security',
    via: 'derive',
    status: 'in_review',
    reopenedAfter: 'Add the before-and-after numbers: how long did routing take before?',
    daysAgo: 543,
  },
  {
    key: 'rb-tabletop',
    sourceKey: 'ridgeback-role',
    content: "Ran quarterly incident response tabletop exercises with program leadership and the agency's security operations center.",
    technologies: ['incident-response', 'stakeholder-communication'],
    metrics: 'Quarterly',
    domain: 'security',
    via: 'derive',
    status: 'in_review',
    daysAgo: 543,
  },
  {
    key: 'rb-log-proposal',
    sourceKey: 'ridgeback-role',
    content: 'Drafting a proposal to consolidate three log pipelines into one, which would cut storage licensing costs for the program.',
    technologies: ['elasticsearch', 'siem-engineering'],
    metrics: null,
    domain: 'devops',
    via: 'draft',
    status: 'draft',
    daysAgo: 26,
  },
  // Granite Point Systems
  {
    key: 'gp-siem',
    sourceKey: 'granite-role',
    content: "Engineered detection content for a defense customer's SIEM, writing 120 correlation rules mapped to adversary techniques.",
    technologies: ['siem-engineering', 'detection-engineering', 'elasticsearch'],
    metrics: '120 correlation rules',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 542,
    reviewedDaysAgo: 540,
  },
  {
    key: 'gp-ids',
    sourceKey: 'granite-role',
    content: 'Deployed Suricata and Zeek sensors across 14 sites and tuned their signatures, cutting false-positive alerts by roughly 60%.',
    technologies: ['suricata', 'zeek', 'linux'],
    metrics: '14 sites; false positives down ~60%',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 542,
    reviewedDaysAgo: 540,
  },
  {
    key: 'gp-ir',
    sourceKey: 'granite-role',
    content: 'Handled more than 40 incident investigations as a tier-3 responder and wrote the after-action reports used to brief customer leadership.',
    technologies: ['incident-response', 'digital-forensics', 'technical-writing'],
    metrics: '40+ investigations',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 542,
    reviewedDaysAgo: 540,
  },
  {
    key: 'gp-scanning',
    sourceKey: 'granite-role',
    content: 'Stood up authenticated vulnerability scanning for 2,500 hosts and a monthly remediation report that program managers acted on.',
    technologies: ['vulnerability-management', 'nmap'],
    metrics: '2,500 hosts',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 542,
    reviewedDaysAgo: 539,
  },
  {
    key: 'gp-osquery',
    sourceKey: 'granite-role',
    content: 'Rolled out osquery to 900 endpoints so responders had live host telemetry during investigations.',
    technologies: ['osquery', 'incident-response'],
    metrics: '900 endpoints',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 542,
    reviewedDaysAgo: 539,
  },
  {
    key: 'gp-terraform',
    sourceKey: 'granite-role',
    content: 'Codified network security groups and logging configuration in Terraform for a new cloud enclave.',
    technologies: ['terraform', 'devsecops'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'archived',
    daysAgo: 542,
    reviewedDaysAgo: 539,
  },
  {
    key: 'gp-helped',
    sourceKey: 'granite-role',
    content: 'Helped with various security tasks across the program.',
    technologies: [],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Too vague: which tasks, and what changed because of them?',
    daysAgo: 542,
    reviewedDaysAgo: 539,
  },
  // 418th Expeditionary Signal Battalion
  {
    key: 'bn-defense',
    sourceKey: 'battalion-role',
    content: 'Defended a deployed tactical network serving 1,500 users, monitoring perimeter sensors and responding to intrusion alerts around the clock.',
    technologies: ['incident-response', 'network-segmentation'],
    metrics: '1,500 users; 24/7 coverage',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 541,
    reviewedDaysAgo: 539,
  },
  {
    key: 'bn-firewall',
    sourceKey: 'battalion-role',
    content: 'Rebuilt firewall and VPN configurations for six forward sites, closing 30 findings from a command cyber readiness inspection.',
    technologies: ['ipsec', 'network-segmentation'],
    metrics: '6 sites; 30 findings closed',
    domain: 'systems_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 541,
    reviewedDaysAgo: 539,
  },
  {
    key: 'bn-shift-lead',
    sourceKey: 'battalion-role',
    content: 'Supervised a five-person network operations shift and trained new soldiers on incident handling procedures.',
    technologies: ['technical-leadership', 'incident-response'],
    metrics: '5-person shift',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 541,
    reviewedDaysAgo: 538,
  },
  {
    key: 'bn-commendation',
    sourceKey: 'battalion-role',
    content: 'Received a unit commendation for restoring network service within four hours after a site power failure.',
    technologies: [],
    metrics: 'Service restored in 4 hours',
    via: 'derive',
    status: 'approved',
    daysAgo: 541,
    reviewedDaysAgo: 538,
  },
  {
    key: 'bn-kerberos',
    sourceKey: 'battalion-role',
    content: 'Migrated site authentication to Kerberos-backed directory services, retiring shared local administrator accounts.',
    technologies: ['kerberos', 'least-privilege', 'windows-server'],
    metrics: null,
    domain: 'systems_engineering',
    via: 'derive',
    status: 'in_review',
    daysAgo: 541,
  },
  // Volunteer mentoring
  {
    key: 'vc-mentor',
    sourceKey: 'vcmn-role',
    content: 'Mentor about 12 transitioning service members a year through resume reviews, home-lab practice and mock technical interviews.',
    technologies: ['mentoring', 'stakeholder-communication'],
    metrics: '~12 mentees per year',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 469,
    reviewedDaysAgo: 466,
  },
  {
    key: 'vc-curriculum',
    sourceKey: 'vcmn-role',
    content: 'Writing a six-week home-lab curriculum on network monitoring for new mentees.',
    technologies: ['zeek', 'technical-writing'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 33,
  },
  // Degrees
  {
    key: 'ms-thesis',
    sourceKey: 'ms-cyber',
    content: 'Wrote a capstone thesis evaluating policy-as-code approaches for continuous authorization of containerized systems.',
    technologies: ['devsecops', 'kubernetes', 'rmf'],
    metrics: null,
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 539,
    reviewedDaysAgo: 537,
  },
  {
    key: 'ms-gpa',
    sourceKey: 'ms-cyber',
    content: 'Completed the M.S. with a 3.91 GPA while working full-time as a senior engineer.',
    technologies: [],
    metrics: '3.91 GPA',
    via: 'derive',
    status: 'approved',
    daysAgo: 539,
    reviewedDaysAgo: 537,
  },
  {
    key: 'bs-coursework',
    sourceKey: 'bs-iss',
    content: 'Completed coursework in network security, cryptography, secure software design and digital forensics.',
    technologies: ['network-segmentation', 'pki', 'digital-forensics'],
    metrics: null,
    via: 'derive',
    status: 'approved',
    daysAgo: 540,
    reviewedDaysAgo: 538,
  },
  // Zero trust pilot
  {
    key: 'zt-identity',
    sourceKey: 'zt-pilot',
    content: 'Integrated device posture and identity signals into access decisions for 600 pilot users, replacing a flat VPN with per-application access.',
    technologies: ['zero-trust', 'saml', 'least-privilege'],
    metrics: '600 pilot users',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 538,
    reviewedDaysAgo: 536,
  },
  {
    key: 'zt-segmentation',
    sourceKey: 'zt-pilot',
    content: 'Segmented the pilot enclave into 40 policy zones and measured a 70% drop in hosts reachable from a compromised workstation.',
    technologies: ['network-segmentation', 'zero-trust'],
    metrics: '40 zones; reachable hosts down 70%',
    domain: 'systems_engineering',
    via: 'derive',
    status: 'approved',
    daysAgo: 538,
    reviewedDaysAgo: 536,
  },
  {
    key: 'zt-rollout',
    sourceKey: 'zt-pilot',
    content: 'Wrote the rollout plan the agency adopted to extend the pilot to two additional mission systems.',
    technologies: ['technical-writing', 'stakeholder-communication'],
    metrics: '2 more systems',
    domain: 'leadership',
    via: 'derive',
    status: 'approved',
    daysAgo: 538,
    reviewedDaysAgo: 536,
  },
  // Baseline Kit
  {
    key: 'bk-toolkit',
    sourceKey: 'baseline-kit',
    content: 'Published an open-source toolkit that turns hardening benchmarks into testable Ansible roles, now used by several contractor teams.',
    technologies: ['ansible', 'python', 'openscap'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 537,
    reviewedDaysAgo: 535,
  },
  {
    key: 'bk-ci',
    sourceKey: 'baseline-kit',
    content: 'Added CI that boots each role in a disposable container and scores it against the benchmark on every pull request.',
    technologies: ['docker', 'git', 'devsecops'],
    metrics: null,
    domain: 'devops',
    via: 'derive',
    status: 'approved',
    daysAgo: 537,
    reviewedDaysAgo: 535,
  },
  {
    key: 'bk-stars',
    sourceKey: 'baseline-kit',
    content: 'Got a lot of stars on the project repository.',
    technologies: ['git'],
    metrics: null,
    via: 'derive',
    status: 'rejected',
    rejection_reason: 'Vanity metric; describe adoption or impact instead.',
    daysAgo: 537,
    reviewedDaysAgo: 535,
  },
  // Summit talk
  {
    key: 'talk-cmon',
    sourceKey: 'summit-talk',
    content: 'Presented continuous control monitoring lessons to about 250 attendees at a regional secure-systems summit.',
    technologies: ['public-speaking', 'rmf'],
    metrics: '~250 attendees',
    domain: 'security',
    via: 'derive',
    status: 'approved',
    daysAgo: 328,
    reviewedDaysAgo: 325,
  },
  {
    key: 'talk-slides',
    sourceKey: 'summit-talk',
    content: "Published the talk's slides and sample evidence-collection scripts for attendees.",
    technologies: ['python', 'technical-writing'],
    metrics: null,
    via: 'derive',
    status: 'archived',
    daysAgo: 328,
    reviewedDaysAgo: 325,
  },
  // Internal briefing
  {
    key: 'guild-brief',
    sourceKey: 'guild-briefing',
    content: 'Briefed 40 engineers on segmentation pilot lessons, leading two other program teams to adopt the policy-zone model.',
    technologies: ['public-speaking', 'network-segmentation'],
    metrics: '40 engineers; 2 teams adopted',
    domain: 'leadership',
    via: 'derive',
    status: 'in_review',
    daysAgo: 233,
  },
  // Panel (the source is rejected later)
  {
    key: 'panel-talk',
    sourceKey: 'vets-panel',
    content: 'Spoke on a panel about moving from military network defense into civilian security engineering.',
    technologies: ['public-speaking', 'mentoring'],
    metrics: null,
    via: 'derive',
    status: 'archived',
    daysAgo: 450,
    reviewedDaysAgo: 448,
  },
  // Capture-the-flag (the source is archived later)
  {
    key: 'ctf-third',
    sourceKey: 'ctf-captain',
    content: 'Captained a six-person capture-the-flag team that placed third of 80 teams at a regional competition.',
    technologies: ['digital-forensics', 'technical-leadership'],
    metrics: '3rd of 80 teams',
    via: 'derive',
    status: 'archived',
    daysAgo: 519,
    reviewedDaysAgo: 517,
  },
  // Drafts on draft sources
  {
    key: 'course-labs',
    sourceKey: 'container-course',
    content: 'Completed labs on container escape techniques, runtime detection and admission control.',
    technologies: ['kubernetes', 'docker'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 88,
  },
  {
    key: 'lab-replay',
    sourceKey: 'detection-lab',
    content: 'Built a home detection lab that replays public attack datasets through Zeek and Suricata to test new detection rules.',
    technologies: ['zeek', 'suricata', 'detection-engineering'],
    metrics: null,
    via: 'draft',
    status: 'draft',
    daysAgo: 38,
  },
]

export const perspectives: PerspectiveSpec[] = [
  // rb-cmon
  {
    key: 'p-rb-cmon-ps',
    bulletKey: 'rb-cmon',
    content: "Cut a federal program's annual assessment evidence push from six weeks to one with nightly, automated evidence collection for 180 security controls.",
    archetype: 'public-sector', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 500,
  },
  {
    key: 'p-rb-cmon-se',
    bulletKey: 'rb-cmon',
    content: 'Built a Python pipeline that continuously verifies 180 security controls and flags configuration drift the morning after it happens.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 500,
  },
  {
    key: 'p-rb-cmon-inf',
    bulletKey: 'rb-cmon',
    content: 'Ran control evidence collection as a scheduled data pipeline, treating compliance checks like any other monitored service.',
    archetype: 'infrastructure', domain: 'devops', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 64,
  },
  // rb-ato
  {
    key: 'p-rb-ato-ps',
    bulletKey: 'rb-ato',
    content: 'Led three mission systems through the risk management framework to authorization, owning the system security plans and assessor coordination.',
    archetype: 'public-sector', domain: 'security', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 499,
  },
  {
    key: 'p-rb-ato-sa',
    bulletKey: 'rb-ato',
    content: 'Translated agency authorization requirements into engineering work that delivery teams could plan around.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'context', via: 'draft', status: 'draft', daysAgo: 30,
  },
  // rb-harden
  {
    key: 'p-rb-harden-inf',
    bulletKey: 'rb-harden',
    content: 'Automated hardening for 1,200 Linux and Windows servers with Ansible, lifting baseline compliance from 71% to 96%.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 498,
  },
  {
    key: 'p-rb-harden-se',
    bulletKey: 'rb-harden',
    content: 'Closed most host-configuration findings for a federal enclave by enforcing hardening baselines as code, taking compliance from 71% to 96%.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 498,
  },
  {
    key: 'p-rb-harden-ps',
    bulletKey: 'rb-harden',
    content: "Brought a mission program's 1,200 servers in line with agency hardening baselines ahead of its reauthorization.",
    archetype: 'public-sector', domain: 'security', framing: 'context', via: 'derive', status: 'approved', daysAgo: 497,
  },
  // rb-k8s
  {
    key: 'p-rb-k8s-se',
    bulletKey: 'rb-k8s',
    content: "Blocked unsigned and root-running containers at admission on a federal program's Kubernetes clusters, before they could reach production.",
    archetype: 'security-engineer', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 496,
  },
  {
    key: 'p-rb-k8s-inf',
    bulletKey: 'rb-k8s',
    content: 'Added image signing and admission policies to the deployment path for every Kubernetes workload on the program.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 496,
  },
  {
    key: 'p-rb-k8s-hft',
    bulletKey: 'rb-k8s',
    content: 'Kept deployment latency flat while adding signature checks to every container admission.',
    archetype: 'hft', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'rejected',
    rejection_reason: 'Latency framing does not fit an admission-control change.', daysAgo: 120,
  },
  // rb-pki
  {
    key: 'p-rb-pki-inf',
    bulletKey: 'rb-pki',
    content: 'Automated internal certificate issuance and renewal for 300 services, ending certificate-expiry outages.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 495,
  },
  {
    key: 'p-rb-pki-se',
    bulletKey: 'rb-pki',
    content: 'Replaced hand-issued service certificates with an automated PKI workflow, removing a recurring cause of outages across 300 services.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 495,
  },
  // rb-mentor
  {
    key: 'p-rb-mentor-ps',
    bulletKey: 'rb-mentor',
    content: 'Mentored four junior engineers through their first authorization packages and on-call rotations on a federal program.',
    archetype: 'public-sector', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 494,
  },
  {
    key: 'p-rb-mentor-se',
    bulletKey: 'rb-mentor',
    content: "Grew the program's security bench by coaching four junior engineers through real assessment and incident work.",
    archetype: 'security-engineer', domain: 'leadership', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 52,
  },
  // gp-siem
  {
    key: 'p-gp-siem-se',
    bulletKey: 'gp-siem',
    content: "Wrote 120 SIEM correlation rules mapped to adversary techniques for a defense customer's security operations center.",
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 493,
  },
  {
    key: 'p-gp-siem-ps',
    bulletKey: 'gp-siem',
    content: "Supported a defense customer's security operations center with detection content tuned to its mission networks.",
    archetype: 'public-sector', domain: 'security', framing: 'context', via: 'derive', status: 'approved', daysAgo: 493,
  },
  // gp-ids
  {
    key: 'p-gp-ids-se',
    bulletKey: 'gp-ids',
    content: 'Deployed and tuned Suricata and Zeek sensors at 14 sites, cutting false-positive alerts by about 60%.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 492,
  },
  {
    key: 'p-gp-ids-inf',
    bulletKey: 'gp-ids',
    content: 'Rolled out network sensors across 14 sites from repeatable builds, so every location ran the same tuned configuration.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 492,
  },
  // gp-ir
  {
    key: 'p-gp-ir-se',
    bulletKey: 'gp-ir',
    content: 'Investigated more than 40 incidents as a tier-3 responder and wrote the after-action reports briefed to customer leadership.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 491,
  },
  {
    key: 'p-gp-ir-ps',
    bulletKey: 'gp-ir',
    content: 'Kept defense customer leadership informed during incidents through clear, timely after-action reports.',
    archetype: 'public-sector', domain: 'leadership', framing: 'context', via: 'derive', status: 'approved', daysAgo: 491,
  },
  {
    key: 'p-gp-ir-ai',
    bulletKey: 'gp-ir',
    content: 'Wrote investigation playbooks structured so an automated triage assistant could follow them.',
    archetype: 'agentic-ai', domain: 'security', framing: 'context', via: 'derive', status: 'rejected',
    rejection_reason: 'No AI work behind this; keep it under security-engineer.', daysAgo: 118,
  },
  // gp-scanning
  {
    key: 'p-gp-scan-se',
    bulletKey: 'gp-scanning',
    content: 'Stood up authenticated vulnerability scanning for 2,500 hosts with a monthly remediation report that program managers acted on.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 490,
  },
  {
    key: 'p-gp-scan-inf',
    bulletKey: 'gp-scanning',
    content: 'Owned the scanning infrastructure and reporting for 2,500 hosts on a defense program.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'responsibility', via: 'draft', status: 'draft', daysAgo: 29,
  },
  // gp-osquery
  {
    key: 'p-gp-osq-se',
    bulletKey: 'gp-osquery',
    content: 'Gave incident responders live host telemetry by rolling out osquery to 900 endpoints.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 489,
  },
  {
    key: 'p-gp-osq-inf',
    bulletKey: 'gp-osquery',
    content: 'Deployed an endpoint telemetry agent to 900 hosts with configuration management and staged rollouts.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'in_review', daysAgo: 47,
  },
  // gp-terraform (the bullet is archived later)
  {
    key: 'p-gp-tf-inf',
    bulletKey: 'gp-terraform',
    content: 'Codified security groups and logging for a new cloud enclave in Terraform.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'archived', daysAgo: 488,
  },
  // bn-defense
  {
    key: 'p-bn-defense-ps',
    bulletKey: 'bn-defense',
    content: 'Defended a deployed tactical network serving 1,500 users, monitoring perimeter sensors and answering intrusion alerts around the clock.',
    archetype: 'public-sector', domain: 'security', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 487,
  },
  {
    key: 'p-bn-defense-se',
    bulletKey: 'bn-defense',
    content: 'Learned network defense under operational pressure, running 24/7 intrusion monitoring for a deployed unit.',
    archetype: 'security-engineer', domain: 'security', framing: 'context', via: 'derive', status: 'approved', daysAgo: 487,
  },
  // bn-firewall
  {
    key: 'p-bn-fw-inf',
    bulletKey: 'bn-firewall',
    content: 'Rebuilt firewall and VPN configurations for six forward sites, closing 30 cyber readiness inspection findings.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 486,
  },
  {
    key: 'p-bn-fw-ps',
    bulletKey: 'bn-firewall',
    content: 'Closed 30 findings from a command cyber readiness inspection by rebuilding perimeter and VPN configurations at six sites.',
    archetype: 'public-sector', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 486,
  },
  // bn-shift-lead
  {
    key: 'p-bn-lead-ps',
    bulletKey: 'bn-shift-lead',
    content: 'Supervised a five-person network operations shift and trained new soldiers on incident handling.',
    archetype: 'public-sector', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 485,
  },
  {
    key: 'p-bn-lead-old',
    bulletKey: 'bn-shift-lead',
    content: 'Led a small network operations team.',
    archetype: 'security-engineer', domain: 'leadership', framing: 'context', via: 'derive', status: 'archived', daysAgo: 530,
  },
  // bn-commendation
  {
    key: 'p-bn-award-ps',
    bulletKey: 'bn-commendation',
    content: 'Earned a unit commendation for restoring network service within four hours of a site power failure.',
    archetype: 'public-sector', domain: 'leadership', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 484,
  },
  // vc-mentor
  {
    key: 'p-vc-mentor-ps',
    bulletKey: 'vc-mentor',
    content: 'Mentor about 12 transitioning service members a year through resume reviews, lab practice and mock technical interviews.',
    archetype: 'public-sector', domain: 'leadership', framing: 'responsibility', via: 'derive', status: 'approved', daysAgo: 460,
  },
  {
    key: 'p-vc-mentor-sa',
    bulletKey: 'vc-mentor',
    content: 'Help career changers map military experience onto civilian security engineering roles.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'context', via: 'draft', status: 'draft', daysAgo: 28,
  },
  // ms-thesis
  {
    key: 'p-ms-thesis-se',
    bulletKey: 'ms-thesis',
    content: 'Evaluated policy-as-code approaches for continuous authorization of containerized systems in an M.S. capstone thesis.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 483,
  },
  {
    key: 'p-ms-thesis-ps',
    bulletKey: 'ms-thesis',
    content: 'Researched how agencies could authorize containerized systems continuously instead of once every few years.',
    archetype: 'public-sector', domain: 'security', framing: 'context', via: 'derive', status: 'approved', daysAgo: 483,
  },
  // ms-gpa / bs-coursework
  {
    key: 'p-ms-gpa-se',
    bulletKey: 'ms-gpa',
    content: 'Earned an M.S. in Cybersecurity Engineering with a 3.91 GPA while working full-time.',
    archetype: 'security-engineer', domain: 'leadership', framing: 'context', via: 'derive', status: 'approved', daysAgo: 482,
  },
  {
    key: 'p-bs-course-se',
    bulletKey: 'bs-coursework',
    content: 'Studied network security, cryptography, secure software design and digital forensics for a B.S. in Information Systems Security.',
    archetype: 'security-engineer', domain: 'security', framing: 'context', via: 'derive', status: 'approved', daysAgo: 482,
  },
  // zt-identity
  {
    key: 'p-zt-id-se',
    bulletKey: 'zt-identity',
    content: 'Replaced a flat VPN with per-application access for 600 pilot users, deciding each request on identity and device posture.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 481,
  },
  {
    key: 'p-zt-id-ps',
    bulletKey: 'zt-identity',
    content: 'Delivered a zero trust access pilot for 600 agency users that shaped the enterprise remote-access roadmap.',
    archetype: 'public-sector', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 481,
  },
  {
    key: 'p-zt-id-sa',
    bulletKey: 'zt-identity',
    content: "Designed identity-aware access for a federal pilot, balancing mission users' workflows against tighter controls.",
    archetype: 'solutions-architect', domain: 'security', framing: 'context', via: 'derive', status: 'in_review', daysAgo: 44,
  },
  // zt-segmentation
  {
    key: 'p-zt-seg-inf',
    bulletKey: 'zt-segmentation',
    content: 'Split a pilot enclave into 40 policy zones, cutting the hosts reachable from a compromised workstation by 70%.',
    archetype: 'infrastructure', domain: 'systems_engineering', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 480,
  },
  {
    key: 'p-zt-seg-se',
    bulletKey: 'zt-segmentation',
    content: 'Measured a 70% drop in lateral-movement reach after segmenting a federal enclave into 40 policy zones.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 480,
  },
  // zt-rollout
  {
    key: 'p-zt-roll-ps',
    bulletKey: 'zt-rollout',
    content: 'Wrote the rollout plan the agency adopted to extend a zero trust pilot to two more mission systems.',
    archetype: 'public-sector', domain: 'leadership', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 479,
  },
  {
    key: 'p-zt-roll-sa',
    bulletKey: 'zt-rollout',
    content: 'Owned the plan for taking a zero trust pilot to production across additional mission systems.',
    archetype: 'solutions-architect', domain: 'leadership', framing: 'responsibility', via: 'draft', status: 'draft', daysAgo: 27,
  },
  // bk-toolkit
  {
    key: 'p-bk-tool-inf',
    bulletKey: 'bk-toolkit',
    content: 'Published an open-source toolkit that turns hardening benchmarks into testable Ansible roles used by several contractor teams.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 478,
  },
  {
    key: 'p-bk-tool-se',
    bulletKey: 'bk-toolkit',
    content: 'Made hardening baselines testable by publishing them as open-source Ansible roles with automated benchmark scoring.',
    archetype: 'security-engineer', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 478,
  },
  // bk-ci
  {
    key: 'p-bk-ci-inf',
    bulletKey: 'bk-ci',
    content: 'Built CI that boots every hardening role in a disposable container and scores it against the benchmark on each pull request.',
    archetype: 'infrastructure', domain: 'devops', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 477,
  },
  {
    key: 'p-bk-ci-hft',
    bulletKey: 'bk-ci',
    content: 'Kept CI fast enough to score every hardening change within minutes.',
    archetype: 'hft', domain: 'devops', framing: 'context', via: 'derive', status: 'rejected',
    rejection_reason: 'Not relevant to trading systems.', daysAgo: 116,
  },
  // talk-cmon
  {
    key: 'p-talk-ps',
    bulletKey: 'talk-cmon',
    content: 'Shared continuous control monitoring lessons with about 250 attendees at a regional secure-systems summit.',
    archetype: 'public-sector', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'approved', daysAgo: 320,
  },
  {
    key: 'p-talk-se',
    bulletKey: 'talk-cmon',
    content: 'Taught practical compliance automation patterns to peers in the federal security community.',
    archetype: 'security-engineer', domain: 'leadership', framing: 'context', via: 'draft', status: 'draft', daysAgo: 25,
  },
  // talk-slides (the bullet is archived later)
  {
    key: 'p-talk-slides-ps',
    bulletKey: 'talk-slides',
    content: 'Published talk slides and sample evidence-collection scripts for summit attendees.',
    archetype: 'public-sector', domain: 'security', framing: 'accomplishment', via: 'derive', status: 'archived', daysAgo: 319,
  },
]
