/**
 * cleared-security-engineer: profile, answer bank, industries, role types, skill catalog,
 * organizations, credentials and certifications. Every name, address line, email, phone
 * number and URL is fictional, including the contractors, the military unit, the agency
 * that sponsors the clearance and the certification bodies; cities and states are real.
 */

import type {
  AnswerSpec,
  CertificationSpec,
  CredentialSpec,
  NamedSpec,
  OrgSpec,
  ProfileSpec,
  SkillSpec,
} from '../../corpus/types'

export const profile: ProfileSpec = {
  name: 'Casey Thornbury',
  email: 'casey.thornbury@example.com',
  phone: '(703) 555-0186',
  address: { name: 'Chantilly, VA', street_1: '410 Example Court', city: 'Chantilly', state: 'VA', zip: '20151' },
  urls: [
    { key: 'linkedin', url: 'https://social.example.com/in/casey-thornbury' },
    { key: 'github', url: 'https://code.example.com/casey-thornbury' },
    { key: 'blog', url: 'https://casey-thornbury.example.net' },
  ],
  salary_minimum: 168000,
  salary_target: 188000,
  salary_stretch: 215000,
}

export const answers: AnswerSpec[] = [
  { field_kind: 'work_auth.us', value: 'Yes' },
  { field_kind: 'work_auth.sponsorship', value: 'No' },
  { field_kind: 'eeo.gender', value: 'Decline to self-identify' },
  { field_kind: 'eeo.race', value: 'Decline to self-identify' },
  { field_kind: 'eeo.veteran', value: 'Protected Veteran' },
  { field_kind: 'eeo.disability', value: 'Prefer not to say' },
]

export const industries: NamedSpec[] = [
  { key: 'defense', name: 'Defense', description: 'Defense programs and mission systems' },
  { key: 'federal-civilian', name: 'Federal Civilian Government' },
  { key: 'intelligence', name: 'Intelligence Community' },
  { key: 'cloud', name: 'Cloud Computing' },
  { key: 'cyber-services', name: 'Cybersecurity Services' },
]

export const roleTypes: NamedSpec[] = [
  { key: 'security-engineer', name: 'Security Engineer' },
  { key: 'security-architect', name: 'Security Architect', description: 'Zero trust, segmentation and identity architecture' },
  { key: 'isso', name: 'Information Systems Security Officer' },
  { key: 'detection-engineer', name: 'Detection Engineer' },
  { key: 'security-manager', name: 'Security Engineering Manager' },
]

export const skills: SkillSpec[] = [
  { key: 'python', name: 'Python', category: 'language', domains: ['software_engineering', 'security'] },
  { key: 'go', name: 'Go', category: 'language' },
  { key: 'bash', name: 'Bash', category: 'language' },
  { key: 'powershell', name: 'PowerShell', category: 'language' },
  { key: 'kubernetes', name: 'Kubernetes', category: 'infrastructure', domains: ['devops', 'systems_engineering'] },
  { key: 'terraform', name: 'Terraform', category: 'infrastructure', domains: ['devops'] },
  { key: 'ansible', name: 'Ansible', category: 'infrastructure', domains: ['devops', 'systems_engineering'] },
  { key: 'docker', name: 'Docker', category: 'infrastructure', domains: ['devops'] },
  { key: 'linux', name: 'Linux', category: 'platform', domains: ['systems_engineering'] },
  { key: 'windows-server', name: 'Windows Server', category: 'platform', domains: ['systems_engineering'] },
  { key: 'zero-trust', name: 'Zero Trust Architecture', category: 'security', domains: ['security', 'systems_engineering'] },
  { key: 'vulnerability-management', name: 'Vulnerability Management', category: 'security', domains: ['security'] },
  { key: 'incident-response', name: 'Incident Response', category: 'security', domains: ['security'] },
  { key: 'pki', name: 'Public Key Infrastructure', category: 'security', domains: ['security'] },
  { key: 'security-control-assessment', name: 'Security Control Assessment', category: 'security', domains: ['security'] },
  { key: 'siem-engineering', name: 'SIEM Engineering', category: 'security', domains: ['security'] },
  { key: 'threat-modeling', name: 'Threat Modeling', category: 'security', domains: ['security'] },
  { key: 'digital-forensics', name: 'Digital Forensics', category: 'security', domains: ['security'] },
  { key: 'detection-engineering', name: 'Detection Engineering', category: 'security', domains: ['security'] },
  { key: 'suricata', name: 'Suricata', category: 'tool', domains: ['security'] },
  { key: 'zeek', name: 'Zeek', category: 'tool', domains: ['security'] },
  { key: 'osquery', name: 'Osquery', category: 'tool' },
  { key: 'openscap', name: 'OpenSCAP', category: 'tool', domains: ['security'] },
  { key: 'nmap', name: 'Nmap', category: 'tool' },
  { key: 'git', name: 'Git', category: 'tool' },
  { key: 'tls', name: 'TLS', category: 'protocol' },
  { key: 'ipsec', name: 'IPsec', category: 'protocol', domains: ['systems_engineering'] },
  { key: 'kerberos', name: 'Kerberos', category: 'protocol' },
  { key: 'saml', name: 'SAML', category: 'protocol' },
  { key: 'rmf', name: 'Risk Management Framework', category: 'methodology', domains: ['security'] },
  { key: 'devsecops', name: 'DevSecOps', category: 'methodology', domains: ['devops', 'security'] },
  { key: 'network-segmentation', name: 'Network Segmentation', category: 'concept', domains: ['security', 'systems_engineering'] },
  { key: 'least-privilege', name: 'Least Privilege', category: 'concept', domains: ['security'] },
  { key: 'elasticsearch', name: 'Elasticsearch', category: 'data_systems' },
  { key: 'technical-leadership', name: 'Technical Leadership', category: 'soft_skill', domains: ['leadership'] },
  { key: 'mentoring', name: 'Mentoring', category: 'soft_skill', domains: ['leadership'] },
  { key: 'stakeholder-communication', name: 'Stakeholder Communication', category: 'soft_skill', domains: ['leadership'] },
  { key: 'technical-writing', name: 'Technical Writing', category: 'soft_skill' },
  { key: 'public-speaking', name: 'Public Speaking', category: 'soft_skill' },
]

export const orgs: OrgSpec[] = [
  {
    key: 'battalion',
    name: '418th Expeditionary Signal Battalion',
    org_type: 'military',
    tags: ['military'],
    industry: 'Defense',
    worked: true,
    employment_type: 'military_active',
    status: null,
    aliases: ['418th ESB'],
    locations: [
      {
        key: 'garrison',
        name: 'Garrison Headquarters',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Fayetteville, NC', street_1: '1 Example Parade Road', city: 'Fayetteville', state: 'NC', zip: '28301' },
      },
    ],
    daysAgo: 556,
  },
  {
    key: 'potomac-valley',
    name: 'Potomac Valley University',
    org_type: 'education',
    tags: ['university'],
    industry: 'Higher Education',
    size: '24,000 students',
    worked: false,
    website: 'https://potomacvalley.example.org',
    status: null,
    aliases: ['PVU'],
    locations: [
      {
        key: 'main',
        name: 'Fairfax Campus',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Fairfax, VA', street_1: '4400 Example Drive', city: 'Fairfax', state: 'VA', zip: '22030' },
      },
      { key: 'online', name: 'Online Graduate School', modality: 'remote' },
    ],
    daysAgo: 555,
  },
  {
    key: 'granite-point',
    name: 'Granite Point Systems',
    org_type: 'company',
    tags: ['company'],
    industry: 'Defense',
    size: '1,000-5,000',
    worked: true,
    employment_type: 'contractor',
    website: 'https://granitepoint.example.com',
    glassdoor_url: 'https://reviews.example.com/granite-point-systems',
    glassdoor_rating: 3.6,
    status: null,
    aliases: ['Granite Point', 'GPS Federal'],
    locations: [
      {
        key: 'hq',
        name: 'Columbia Headquarters',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Columbia, MD', street_1: '7200 Example Parkway', city: 'Columbia', state: 'MD', zip: '21046' },
      },
    ],
    daysAgo: 554,
  },
  {
    key: 'ridgeback',
    name: 'Ridgeback Federal Solutions',
    org_type: 'company',
    tags: ['company'],
    industry: 'Federal Civilian Government',
    size: '500-1,000',
    worked: true,
    employment_type: 'contractor',
    website: 'https://ridgeback-federal.example.com',
    linkedin_url: 'https://social.example.com/company/ridgeback-federal',
    status: null,
    aliases: ['Ridgeback', 'RFS'],
    locations: [
      {
        key: 'hq',
        name: 'Chantilly Headquarters',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Chantilly, VA', street_1: '14800 Example Boulevard', street_2: 'Suite 300', city: 'Chantilly', state: 'VA', zip: '20151' },
      },
      {
        key: 'customer-site',
        name: 'Customer Site (Washington)',
        modality: 'in_person',
        address: { name: 'Washington, DC', street_1: '900 Example Street NW', city: 'Washington', state: 'DC', zip: '20001' },
      },
    ],
    daysAgo: 553,
  },
  {
    key: 'dsfn',
    name: 'Directorate of Secure Federal Networks',
    org_type: 'government',
    tags: ['government'],
    industry: 'Federal Civilian Government',
    size: '5,000+',
    worked: false,
    website: 'https://dsfn.example.org',
    status: 'interested',
    aliases: ['DSFN'],
    locations: [
      {
        key: 'hq',
        name: 'Headquarters',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Washington, DC', street_1: '250 Example Avenue SW', city: 'Washington', state: 'DC', zip: '20024' },
      },
    ],
    daysAgo: 552,
  },
  {
    key: 'vcmn',
    name: 'Veterans Cyber Mentorship Network',
    org_type: 'volunteer',
    tags: ['nonprofit', 'volunteer'],
    industry: 'Workforce Development',
    worked: true,
    employment_type: 'volunteer',
    website: 'https://vets-cyber-mentors.example.org',
    status: null,
    daysAgo: 550,
  },
  {
    key: 'sseb',
    name: 'Secure Systems Engineering Board',
    org_type: 'nonprofit',
    tags: ['nonprofit'],
    industry: 'Professional Certification',
    worked: false,
    website: 'https://sseb.example.org',
    status: null,
    aliases: ['SSEB'],
    daysAgo: 549,
  },
  {
    key: 'occi',
    name: 'Open Cyber Credentialing Institute',
    org_type: 'nonprofit',
    tags: ['nonprofit'],
    industry: 'Professional Certification',
    worked: false,
    website: 'https://occi.example.org',
    status: null,
    aliases: ['OCCI'],
    daysAgo: 549,
  },
  {
    key: 'fapc',
    name: 'Federal Assurance Practitioners Council',
    org_type: 'nonprofit',
    tags: ['nonprofit'],
    industry: 'Professional Certification',
    worked: false,
    website: 'https://fapc.example.org',
    status: null,
    daysAgo: 548,
  },
  {
    key: 'summit',
    name: 'Mid-Atlantic Secure Systems Summit',
    org_type: 'nonprofit',
    tags: ['conference'],
    worked: false,
    website: 'https://securesystems-summit.example.org',
    status: null,
    daysAgo: 400,
  },
  {
    key: 'tessellate',
    name: 'Tessellate Cloud',
    org_type: 'company',
    tags: ['company', 'vendor', 'platform'],
    industry: 'Cloud Computing',
    size: '5,000+',
    worked: false,
    website: 'https://tessellate-cloud.example.com',
    linkedin_url: 'https://social.example.com/company/tessellate-cloud',
    glassdoor_url: 'https://reviews.example.com/tessellate-cloud',
    glassdoor_rating: 4.1,
    status: 'researching',
    locations: [{ key: 'remote', name: 'Remote (US Public Sector)', modality: 'remote' }],
    daysAgo: 300,
  },
  {
    key: 'kettlerock',
    name: 'Kettlerock Mission Systems',
    org_type: 'company',
    tags: ['company'],
    industry: 'Intelligence Community',
    size: '1,000-5,000',
    worked: false,
    website: 'https://kettlerock.example.com',
    glassdoor_url: 'https://reviews.example.com/kettlerock-mission-systems',
    glassdoor_rating: 4.3,
    status: 'exciting',
    aliases: ['Kettlerock'],
    locations: [
      {
        key: 'hq',
        name: 'Annapolis Junction Office',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Annapolis Junction, MD', street_1: '10 Example Way', city: 'Annapolis Junction', state: 'MD', zip: '20701' },
      },
    ],
    daysAgo: 180,
  },
  {
    key: 'halyard',
    name: 'Halyard Analytics Group',
    org_type: 'company',
    tags: ['company'],
    industry: 'Defense',
    size: '200-500',
    worked: false,
    website: 'https://halyard-analytics.example.com',
    status: 'interested',
    locations: [
      {
        key: 'hq',
        name: 'Arlington Office',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Arlington, VA', street_1: '1600 Example Street', street_2: 'Floor 9', city: 'Arlington', state: 'VA', zip: '22209' },
      },
      { key: 'remote', name: 'Remote (US)', modality: 'remote' },
    ],
    daysAgo: 160,
  },
  {
    key: 'capitol-beacon',
    name: 'Capitol Beacon Consulting',
    org_type: 'company',
    tags: ['company'],
    industry: 'Cybersecurity Services',
    size: '50-200',
    worked: false,
    website: 'https://capitolbeacon.example.com',
    status: 'researching',
    locations: [
      {
        key: 'hq',
        name: 'Downtown Office',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Washington, DC', street_1: '1100 Example Avenue NW', city: 'Washington', state: 'DC', zip: '20005' },
      },
    ],
    daysAgo: 140,
  },
  {
    key: 'larkspur',
    name: 'Larkspur Integrated Systems',
    org_type: 'company',
    tags: ['company'],
    industry: 'Federal Civilian Government',
    size: '200-500',
    worked: false,
    website: 'https://larkspur-integrated.example.com',
    status: 'excluded',
    daysAgo: 130,
  },
  {
    key: 'anvil-point',
    name: 'Anvil Point Cyber',
    org_type: 'company',
    tags: ['company'],
    industry: 'Cybersecurity Services',
    size: '50-200',
    worked: false,
    website: 'https://anvilpoint.example.com',
    status: 'acceptable',
    locations: [
      {
        key: 'hq',
        name: 'Aurora Operations Center',
        modality: 'hybrid',
        is_headquarters: true,
        address: { name: 'Aurora, CO', street_1: '3300 Example Circle', city: 'Aurora', state: 'CO', zip: '80011' },
      },
    ],
    daysAgo: 60,
  },
  {
    key: 'spruce-canyon',
    name: 'Spruce Canyon Technologies',
    org_type: 'company',
    tags: ['company'],
    industry: 'Defense',
    size: '200-500',
    worked: false,
    website: 'https://sprucecanyon.example.com',
    status: 'backlog',
    locations: [
      {
        key: 'hq',
        name: 'Colorado Springs Office',
        modality: 'in_person',
        is_headquarters: true,
        address: { name: 'Colorado Springs, CO', street_1: '55 Example Loop', city: 'Colorado Springs', state: 'CO', zip: '80903' },
      },
    ],
    daysAgo: 8,
  },
]

export const credentials: CredentialSpec[] = [
  {
    key: 'ts-sci',
    credential_type: 'clearance',
    label: 'Top Secret/SCI with CI Polygraph',
    status: 'active',
    orgKey: 'dsfn',
    details: { level: 'top_secret', polygraph: 'ci', clearance_type: 'personnel', access_programs: ['sci'] },
    issued: { monthsAgo: 34, day: 12 },
    daysAgo: 551,
  },
  {
    key: 'va-license',
    credential_type: 'drivers_license',
    label: 'Virginia Driver License (Class C)',
    status: 'active',
    details: { class: 'C', state: 'VA', endorsements: [] },
    issued: { monthsAgo: 40, day: 3 },
    expires: { monthsAgo: -56, day: 3 },
    daysAgo: 547,
  },
]

export const certifications: CertificationSpec[] = [
  {
    key: 'csse',
    short_name: 'CSSE',
    long_name: 'CSSE – Certified Secure Systems Engineer',
    cert_id: 'SSEB-CSSE',
    issuerKey: 'sseb',
    earned: { monthsAgo: 44, day: 18 },
    expires: { monthsAgo: -4, day: 18 },
    credential_id: 'CSSE-118204',
    credential_url: 'https://verify.sseb.example.org/csse/118204',
    credly_url: 'https://badges.example.com/sseb-csse/118204',
    in_progress: false,
    skills: ['security-control-assessment', 'threat-modeling', 'pki', 'zero-trust'],
    daysAgo: 546,
  },
  {
    key: 'ocih',
    short_name: 'OCIH',
    long_name: 'OCCI Certified Incident Handler',
    cert_id: 'OCCI-CIH',
    issuerKey: 'occi',
    earned: { monthsAgo: 66, day: 7 },
    expires: { monthsAgo: -6, day: 7 },
    credential_id: 'OCIH-55073',
    credential_url: 'https://occi.example.org/verify/OCIH-55073',
    in_progress: false,
    skills: ['incident-response', 'digital-forensics', 'detection-engineering'],
    daysAgo: 546,
  },
  {
    key: 'fapc-ap',
    short_name: 'FAPC-AP',
    long_name: 'FAPC Authorization Practitioner',
    cert_id: 'FAPC-AP',
    issuerKey: 'fapc',
    earned: { monthsAgo: 20, day: 25 },
    expires: { monthsAgo: -16, day: 25 },
    credential_id: 'FAPC-AP-30981',
    credential_url: 'https://fapc.example.org/registry/FAPC-AP-30981',
    in_progress: false,
    skills: ['rmf', 'security-control-assessment', 'technical-writing'],
    daysAgo: 545,
  },
  {
    key: 'tcss',
    short_name: 'TCSS',
    long_name: 'Tessellate Cloud Security Specialty',
    cert_id: 'TC-SEC-SPEC',
    issuerKey: 'tessellate',
    in_progress: true,
    skills: ['kubernetes', 'terraform', 'zero-trust'],
    daysAgo: 95,
  },
]
